Bubberstation/Bubberstation

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Title.
This is not Skyrat.
<details>
</details>
Not player-facing.
=> Changes mention of Skyrat to Bubber-Station in PR Template.

tgstation.dme
:cl:
add: Includes modular_zubbers/code/datums/ert.dm in tgstation.dme
/:cl:
=> Updates TGstation.dme for ERT modularity

code/modules/research/designs/mechfabricator_designs.dm, code/modules/research/techweb/all_nodes.dm
Re-adds the Medical cyborg Crew Pinpointer upgrade. Skyrat commented it out with some...shaky justification, and I've decided to re-add it.
:cl:
add: Medical cyborg crew pinpointer uncommented
/:cl:
=> Re-adds Medical Borg pinpointer

code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm, code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
:cl:
Add: enemy_roles to all midround antags
/:cl:
=> Adds enemy_roles to all midround and latejoin antags

_maps/map_files/Deltastation/DeltaStation2_bubber.dmm, _maps/map_files/IceBoxStation/IceBoxStation_bubber.dmm, _maps/map_files/VoidRaptor/VoidRaptor_bubber.dmm
=> Changes the access on the doors of the NT rep's doors to ACCESS_NTREP

code/modules/unit_tests/worn_icons.dm
=> Add our icon path to CI

code/modules/mob/living/basic/basic.dm, code/modules/mob/living/simple_animal/guardian/guardian.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/pai/pai.dm
:cl:
qol: you now know your exact health as a simple/basic mob
/:cl:
=> Better health viewing

code/modules/research/stock_parts.dm
Makes the alternate BRPED sound rarer.
I hate it, therefore it's good.
=> Nerfs RPED alt sounds.

code/datums/ai_laws/laws_station_sided.dm
Adds Crewsimov, and Crewsimov++ as proper alternatives to Asimov and Asimov++. Does not make them default.
:cl:
Add: correct Crewsimov
add: Crewsimov++ (asimov++ but crew)
/:cl:
=> Updates crewsimov to modern standards, adds crewsimov++

code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
I forgot to adjust how long the tentacles stun you for. Oops.
:cl:
fix: fixes goliath stunlocking miners
/:cl:
=> Fix goliath stunlock

code/game/objects/items/spear.dm, code/modules/mining/equipment/kinetic_crusher.dm
No idea why it had 110 effectiveness. Incentivizes people to carry a knife with them.
:cl:
balance: crushers and spears are now terrible at butchering
/:cl:
=> Nerfs butchering with the crusher/spear

code/modules/research/machinery/_production.dm, config/game_options.txt, modular_skyrat/master_files/code/modules/research/techweb/protolathe.dm, tgstation.dme
Title
:cl:
config: Lathe tax is now a config option
/:cl:
=> Makes the Lathe Tax a server config

code/game/objects/items/melee/baton.dm, code/modules/projectiles/guns/energy/stun.dm
Reverts the Skyrat stunbaton to the TG stunbaton
:cl:
Add: Changes some of the effects of the stunbaton back to TG
/:cl:
=> Reverts to TG stunbaton and disabler

_maps/map_files/MetaStation/MetaStation_bubber.dmm
Fixes #114 , by adding a fax machine at bridge
:cl:
add: Fax machine added to meta bridge
/:cl:
=> Adds fax machine to meta

tgstation.dme
fixes #190 not working as intended because the DME didn't commit this one file
=> Fixes a DME issue with 190

code/game/objects/items/melee/baton.dm, code/modules/jobs/job_types/warden.dm, modular_zubbers/code/game/objects/items/holy_weapons.dm, modular_zubbers/code/modules/status_indicators/status_indicator.dm
This reverts commit 05867699c530f80aca81c2a437731a3193c42495, reversing changes made to e7eb758cb6afa5937b78d0af995a507ea232e733.
:cl:
server: I fucked up
/:cl:
=> Revert "Merge pull request #197 from NullDagaf/cummenfarten"

_maps/map_files/tramstation/tramstation_bubber.dmm, code/game/objects/items/melee/baton.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/jobs/job_types/warden.dm, modular_zubbers/code/game/objects/items/holy_weapons.dm, modular_zubbers/code/modules/status_indicators/status_indicator.dm
• Reshi's glock17 for the warden moved to locker.
• Status indicator plane from -4 to -3.99 to satisfy plane unit tests.
• Papal staff nullrod now should look for the correct belt icon.
=> Clears the lint out of the washing machine

code/modules/projectiles/guns/energy/stun.dm
Check the title.
:cl:
Fix: disabler having a cell_type too large
/:cl:
=> Fixes disablers having a cell_type way too large (300 shots vs 20 like on TG)

modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_suit.dm, modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_under.dm
Adds 3 of Nikolai's 5 donor items to the loadout menu as donor items. Fixes line spacing from a previous donor PR.
:cl:
Add: Three under-suits to the loadout menu
Fix: Spacing issues on a previous donor PR
/:cl:
=> Fix a spacing issue, add donor items

modular_zubbers/code/datums/department_security.dm, tgstation.dme
Reimplements #134 modularly. 
Merge after #236
=> [MODULAR] Modularizes #134

code/datums/diseases/chronic_illness.dm
Adds a line to let the chronic illness disease bypass immunity. This lets hemophages be properly infected without removing their VIRUS_IMMUNE trait. Tested in game.
:cl:
balance: Allows Chronic Illness to function correctly on Virus Immune species, like hemophages.
/:cl:
=> Chronic Illness Immunity Bypass

modular_zubbers/code/modules/paperwork/fax.dm, tgstation.dme
One small issue with this PR is that all new factions are listed at the top of the list, while regular station faxes are shifted down. This needs to be resolved before the PR is merged. Otherwise, it works as intended.
Emag is required for most antagonistic factions.
Has no gameplay impact other than allowing anyone using a fax machine to direct a fax to a specific target. NT remains at the top of the list.
:cl:
Add: The ability to fax different factions, ship relays, et cetera in the sector, based on lore.
/:cl:
=> Adds new factions to the fax machine

code/game/objects/effects/spawners/random/entertainment.dm, code/modules/research/techweb/all_nodes.dm, modular_zubbers/code/game/machinery/computer/arcade.dm, modular_zubbers/code/modules/modular_computers/file_system/programs/minesweeper.dm
Now that I know it works, final touches:
(Mainly just stuff I forgot because I went thru like 70 errors and was tired of it)
:cl:
add: Minesweeper arcade machines finally introduced to the station
add: Reported overheats of certain minesweeper machines as a result of tampering
/:cl:
=> Finishes up minesweeper

modular_skyrat/modules/blueshield/code/blueshield.dm
=> Adds comments to the blueshield bubber edits

code/game/objects/items/robot/robot_upgrades.dm
Allows you to expand borgs, all borgs. boring no fun skyrat edits. Expand borg. 
:cl:
code: no more borg expansion restrictions
/:cl:
=> [TG Reset][Nonmodular]Expand Borg

modular_zubbers/code/modules/jobs/job_types/blueshield.dm, modular_zubbers/code/modules/jobs/job_types/nanotrasen_consultant.dm
Makes both Blueshield and NT Consultant command ONLY.
:cl:
Del: the CENTCOM department
/:cl:
=> Makes Blueshield and NTRep only command

modular_zubbers/master_files/code/modules/research/designs/biogenerator_designs.dm
I was offered money by BurningCold on Discord to make code to add several fruit juices to the biogenerator food list. I asked why it was necessary, since some of these are in the booze or soft drink dispensers and they told me it is because they regularly play as a prisoner, and some plants are not allowed in the prison due to certain hazards presented by mutations of the plants they are obtained from. Adding these allows for ghetto bartending in the prison. Alongside these, as a show of good will, I have also added Diethylamine and Saltpetre to the list of chemicals, and Soy Sauce to the food list so that there's an alternative for making it other than ordering it or having to grow nettles, which also present their own threat to sec officers. Never let it be said that I don't deliver. …
=> (Modular) Adds some new biogenerator products

code/datums/ai_laws/laws_station_sided.dm, modular_zubbers/code/datums/ai_laws/laws_neutral.dm, modular_zubbers/code/datums/ai_laws/laws_station_sided.dm, modular_zubbers/code/game/objects/items/ai_modules/full_lawsets.dm, tgstation.dme
Adds a crew variant of the Overlord lawset. Also moves our Crewsimov to the modular file while it's there.
:cl:
Del: non-modular Crewsimov
Add: modular Crewsimov
Add: Crewlord, Overlord but Crew instead of Human
/:cl:
=> [Modular] Moves Crewsimov, adds Crew Overlord

code/modules/mob/living/carbon/human/_species.dm, code/modules/mob/living/carbon/human/species_types/humans.dm, code/modules/mob/living/carbon/human/species_types/monkeys.dm
Not really good for a server like us. Not really fun, and encourages meta behavior like making custom species off humans to get the gamer items in sec/mining vendors round start. Policy nightmare, too. 
:cl:
balance: soft removed the payday modifier
/:cl:
=> soft removes the payday modifier

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage.dm
Gives hemophages Mutant colors
:cl:
qol: Returns hemophage mutant Colors
/:cl:
=> Hemophage Colors

.github/PULL_REQUEST_TEMPLATE.md
Reintroduces "Why It's Good For The Game"  from upstream /tg/'s PR template.
Reintroduces "Why It's Good For The Game"  from upstream /tg/'s PR template.
There's no real reason why this shouldn't be in the template. It's on upstream /tg/'s for a reason.
=> Reintroduce "Why It's Good For The Game" in PR template.

_maps/map_files/biodome/biodome.dmm
Various tweaks and fixes brought up between now and the last pr I did for Biodome: https://github.com/Bubberstation/Bubberstation/pull/370
Some of this is parity, some of this is "bug fixing" (removing or replacing things on the map that were causing unwanted effects.)
:cl:
add: [Biodome] Girders that are on top of water now have plating underneath so they no longer "float" in the water
add: [Biodome] Armoury now has a Smart Gun locker
add: [Biodome] The Teleporter Room now has shutters
del: [Biodome] The crab habitat has been relocated to make way for Teleporter Room shutters
del: [Biodome] Security has lost their cozy fireplace
fix: [Biodome] Replaced a tile that was generating infinite air
fix: [Biodome] The Detective's west shutters should now be linked properly to the open/close …
=> Small Biodome fixes before The Maintinencing

modular_zubbers/code/modules/cargo/packs/service.dm, tgstation.dme
Purchasable jukebox for 10k credits
WARNING: YOU WILL NEED BAR ACCESS
We added a shit ton of songs into it only for it to be admin only. There is no reason for it to not be accessible to crew
(And yes I know it spawns in ruins and on birdshot. That isn't easily accessible)
:cl:
add: Jukeboxes can now be purchased via the cargo shuttle
/:cl:
=> Jukeboksss Update

modular_zubbers/code/modules/cargo/bounties/blacksmith.dm
See "I wanted to testmerge this"
Also I kid you not I merged the fix for this no clue where it went
:cl:
fix: sword bounty now works
/:cl:
=> Fixes something about the new bounties

modular_skyrat/master_files/code/datums/traits/negative.dm
:cl:
spellcheck: Fixed a typo with examine text for the "Sensitive Snout" quirk.
/:cl:
=> Fixes sensitive snout typo

code/modules/admin/greyscale_modify_menu.dm, code/modules/admin/view_variables/topic_basic.dm, code/modules/tgui/states/greyscale_menu.dm, code/modules/vending/_vending.dm, modular_skyrat/modules/loadouts/loadout_ui/loadout_manager.dm
me when the mirrorr. The m The mirror https://github.com/Skyrat-SS13/Skyrat-tg/pull/22965
:cl: Huskil
fix: GAGS menu is fixed. Recolour your loadout items at will (you must make at least one hot pink)
/:cl:
=> grrr fixes gags menu cutely

modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_suit.dm
=> bangle item fix

tgstation.dme
closes https://github.com/Bubberstation/Bubberstation/pull/469
:cl:
fix: The new additions to the biogen are, once again, in the biogen.
/:cl:
=> ticks biogen file

code/game/objects/items/robot/items/hypo.dm
Remove Haloperidol, a sleep chemical from borgs. Haloperidol is a busted chemical for combat and it has to go. This is a bandaid fix to the instant injection issue, but until I can convince more people, this'll have to do. I will be experimenting with the injection timer. I removed Haloperidol from that list. This won't break.
Haloperidol is a busted chemical which puts the victim to sleep, allowing any borg to click-combat insta-inject with modsuit penetration any individual they want, taking them out of the fight in which they can then pump them full of more. Sorry but no.
:cl:
del: Removed Haloperidol from Medical Borg Hyposprays
/:cl:
=> Remove Haloperidol from Borgs

code/datums/quirks/neutral_quirks/neutral_quirks.dm
Re-Enables the Colorist quirk
(image just to show i didnt break anything re-enabling it)
Pros: 
-lets you customize your own character's hair colors without relying on another person; or getting money-checked by the vendor
Cons: 
-devalues barber slightly (literally who plays this job)
-no ear/tail dye anyways
:cl:
qol: The Colorist Quirk (neutral) is now re-enabled (Allows you to start with hair dye!)
/:cl:
=> Re-Enables the Colorist Quirk

_maps/map_files/biodome/biodome.dmm
=> Fixes biodome CI.

code/modules/surgery/bodyparts/dismemberment.dm
Fixes organ spilling organs that should be unspillable.
Bugfix.
:cl: BurgerBB
fix: Fixes organ spilling organs that should be unspillable.
/:cl:
=> Fixes organ spilling organs that should be unspillable

modular_zubbers/modules/customization/modules/mob/living/carbon/human/species/akula.dm, tgstation.dme
See name
The fishies need to bubble as they speak. **YOU** need this.
:cl:
add: Akulas now bubble when speaking
/:cl:
=> Akula say_verb is now "bubbles"

_maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm, _maps/map_files/LimaStation/LimaStation.dmm, _maps/map_files/biodome/biodome.dmm, _maps/map_files/burgerstation/burgerstation.dmm
Fixes map errors (Goodby bepsis)
=> Fixes mapping errors

_maps/map_files/biodome/biodome.dmm, code/game/objects/effects/spawners/random/random.dm, modular_zubbers/code/modules/hydroponics/plant_genes.dm
=> Fixes Biodome Linters + Other Linters

_maps/map_files/burgerstation/burgerstation.dmm
Fixes Burgerstation Disposals + Incinerator
Fixes Burgerstation Disposals + Incinerator
:cl: BurgerBB
fix: Fixes Burgerstation Disposals + Incinerator
/:cl:
=> Fixes Burgerstation Disposals + Incinerator

modular_zubbers/code/datums/id_trim/jobs.dm
Gives secmed morgue and medical accesses.
Please for the love of god they don't even get crew trackers and medbay just lets them inside to get whatever they need.
They dont even get guns anymore and sec would rather steal their medkits for themselves, it's better they can maybe get stuff from med so they can do the bare minimum of their jobs.
:cl:
add: Secmeds got medical access back. This is so they can get refills without bothering everyone and actually makes them able to do their job
/:cl:
=> Gives secmed back basic medical access

code/modules/mob/living/carbon/human/human_defense.dm
See name
Realism is cool and all but random chance to just die from any shock that can damage you is annoying as all hell, and randomness that can instakill simply isn't fun.
:cl:
del: Shocks no longer have a chance to kill you
/:cl:
=> Removes the shitty skyrat "Realism" change that just stops your heart when you get shocked

code/modules/vending/wardrobes.dm, modular_skyrat/modules/loadouts/loadout_items/loadout_datum_heads.dm, modular_zubbers/code/modules/clothing/head/jobs.dm
Simple donator item request for Gavla. Adds a beret for the coroner. Available in the MortiDrobe Vendor and in the loadout menu.
Preview: 
More mortician drip. Greyscale medbay is cool.
:cl:
add: Added a beret for Coroners. It is also in the loadout menu.
/:cl:
=> Adds a beret for coroners

modular_zubbers/code/modules/mob/living/examine.dm, tgstation.dme
makes it so that you can see if someone is ACTUALLY fixable like the hud
=> patches dnr examines

modular_zubbers/code/datums/components/crafting/utility.dm, tgstation.dme
See name.
Good to make something assistants can steal for bounties renewable
:cl:
qol: made paper bins craftable
/:cl:
=> Makes paper bins craftable

tgui/packages/tgui/interfaces/Changelog.js
Fixes Skyrat Space Station 13 with Bubberstation 13 on the changelog. We're not going to have an identity crisis any longer.
:cl: StrangeWeirdKitten
fix: fixed the changelog to properly show Bubberstation
/:cl:
=> Fixes the changelog to properly reflect our server

README.md
Plus a formatting fix on the documentation.
=> Forgot to update the contributer blurb

modular_zubbers/code/game/machinery/burger_reactor_sniffer/reactor_sniffer.dm, modular_zubbers/code/game/machinery/burger_reactor_sniffer/reactor_sniffer_processing.dm, modular_zubbers/code/game/machinery/burger_reactor_sniffer/reactor_sniffer_wires.dm
The RB-MK2 sniffer now actually works.
:cl: BurgerBB
fix: Fixes the RB-MK2 sniffer not actually working.
/:cl:
=> Fixes the RB-MK2 sniffer not broadcasting.

_maps/map_files/burgerstation/burgerstation.dmm
Reroutes some of the disposals in Burgerstation medbay (and virology) so that trash doesn't bounce back out.
Fixes a mapping error.
:cl:
fix: Fixed some of Burgerstation's medbay disposals
/:cl:
=> Fixes medbay disposals

modular_zubbers/code/game/objects/structures/beds_chairs/sofa.dm, tgstation.dme
Worthless coins galore, you can find iron coins (Or something special) under sofa pillows by rightclicking with an empty hand.
Fun interaction with no side effects whatsoever
:cl:
add: You can now rightclick with an empty hand to search sofa pillows for change
/:cl:
=> You can now dig through sofa pillows

README.md
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: Another test of the changelog bot!
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Fix CI suite badge in readme

modular_zubbers/code/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
Shark knows
:cl:
fix: Fixes an exploit with synth computers
/:cl:
=> Fixes a thing

tgui/packages/tgui/interfaces/AntagInfoRules.tsx
This PR replaces all of skyrat's antag rules with a link to our main rules.
We're not skyrat
:cl: The Sharkening
fix: removes skyrat rules from the antag TGUI
/:cl:
=> Removes Skyrat Rules from our antag TGUI [CI skip]

tools/build/build.js
Now build recompiles dme, if ONLY modular changes were present
P.S. Why wasn't it done yet?
:cl:
code: Now if ONLY modular content was modified, build recompiles dme correctly
/:cl:
=> Updates build.js to check for modular zubber changes

modular_zubbers/code/datums/quirks/neutral_quirks/waddle.dm, tgstation.dme
Adds a waddle to your movement.
Not species restricted, but could make it as such if requested
closes #759
I offered to moffington to do this, so here I am
You can now make your character more unique, free of charge!
:cl:
add: New quirk: Waddle
/:cl:
=> New quirk - Waddle

html/changelogs/AutoChangeLog-pr-741.yml, html/changelogs/AutoChangeLog-pr-771.yml, html/changelogs/archive/2023-11.yml
Because I felt like compiling it.
=> changelog 11 / 27 / 2023

modular_zubbers/modules/modular_items/code/idmaco_donator.dm
I completely overlooked this and it got merged. heck
=> Fixing the datum pathing in the idma donor item file

modular_zubbers/modules/modular_items/code/idmaco_donator.dm, tgstation.dme
Ticked the file that was otherwise unticked and didn't show up
=> unticked file in idma donor

code/modules/jobs/job_types/quartermaster.dm, html/changelogs/AutoChangeLog-pr-777.yml, html/changelogs/AutoChangeLog-pr-778.yml, html/changelogs/AutoChangeLog-pr-781.yml, html/changelogs/AutoChangeLog-pr-783.yml, html/changelogs/AutoChangeLog-pr-796.yml, html/changelogs/archive/2023-12.yml
This makes it so the Quartermaster has sunglasses which show whether other people have a permit or not.
QM should be able to tell if you have a permit to order a weapon with! Much in the same way that the customs agent can. Gives them a neat little extra tool.
:cl:
add: QM permit sunglasses
/:cl:
=> QM spawns with permit sunglasses

modular_zubbers/code/modules/paperwork/fax.dm
Pink because this seems to be the clown colour (the stamp, for example.), same with the Mime.
People already fax to Clown Planet. This just means they're pressing the button that says the place they want it.
:cl: Cursour, dictated by the Joker (Jack Nicholson and Jared Leto versions) and Pogo.
add: One may now directly fax Clown Planet. Mime Planet too if you hate trees.
/:cl:
=> [Modular] Adds Clown & Mime Planet to the Fax.

_maps/map_files/LimaStation/LimaStation.dmm
See name
It wasn't there. Now it is. Calling arrival shuttle good, no?
:cl:
fix: Lima now has an arrival shuttle console
/:cl:
=> Adds arrival shuttle console on lima

code/datums/quirks/negative_quirks/claustrophobia.dm
Why is this a thing
People run quirks here more often and this makes their characters unplayable.
Basically, the feature is funny. For everyone BUT the player who runs the quirk
:cl:
del: Santa claus no longer makes claustrophobes die
/:cl:
=> Removes santa claus (From making claustrophobes die)

html/changelogs/AutoChangeLog-pr-770.yml, html/changelogs/AutoChangeLog-pr-810.yml, html/changelogs/AutoChangeLog-pr-812.yml, html/changelogs/AutoChangeLog-pr-814.yml, html/changelogs/AutoChangeLog-pr-815.yml, html/changelogs/AutoChangeLog-pr-816.yml, html/changelogs/AutoChangeLog-pr-818.yml, html/changelogs/AutoChangeLog-pr-820.yml, html/changelogs/archive/2023-12.yml
=> changelog 12/6/2023

html/changelogs/AutoChangeLog-pr-795.yml, html/changelogs/AutoChangeLog-pr-803.yml, html/changelogs/AutoChangeLog-pr-830.yml, html/changelogs/AutoChangeLog-pr-836.yml, html/changelogs/AutoChangeLog-pr-839.yml, html/changelogs/archive/2023-12.yml
=> Changelog 12/14/2023

modular_skyrat/master_files/code/modules/jobs/job_types/clown.dm, modular_zubbers/code/modules/jobs/job_types/clown.dm, tgstation.dme
Title. Skyrat disabled it because they hate fun. We don't.
Say a Clown dies. Is arrested, or is just a bit shit.
What can you do?
Jackshit.
Pray, fax Clown Planet, but why wait on God or the Clown in the High Castle when you can do it yourself?
This also let's Antags, or Clowns summon more friends. Assuming people in the lobby wanna be a clown.
P.S. I commented out and unticked the Skyrat file for double safety. Tried to just override it, didn't work. If you have a better idea for this. You have the floor.
:cl:
add: Clown slots are re-openable by royal decree. The incident between Nanotrasen and King Honkington has been resolved.
/:cl:
=> Grants the ability to open Clown slots once more.

.github/PULL_REQUEST_TEMPLATE.md
Adds a proof of testing to the PR template.
=> Proof of Testing requirement

tgui/packages/tgui/components/TextArea.tsx
See https://github.com/tgstation/tgstation/pull/80656
fixes #904
=> [UPSTREAM MIRROR] Fixes TextArea not updating on props change (#80656)

tgstation.dme
=> Ticks the actual vote change because I can't trust anyone else to actually test their code changes

_maps/map_files/biodome/biodome.dmm
closes: #945
:cl:
fix: Biodome now has the bitrunner vendor
/:cl:
=> Biodome now has the bitrunner vendor

code/game/objects/items/storage/garment.dm, modular_zubbers/code/game/objects/items/storage/garment.dm, tgstation.dme
Does what it says on the tin.
It's a piece of CMO clothing and should be in the garment bag. The only reason it isn't is because the fruit man said no on an entirely different server two years ago. https://github.com/tgstation/tgstation/pull/64223
:cl:
fix: added cmo turtleneck/skirtleneck to garment bag
/:cl:
=> Adds CMO turtleneck/skirtleneck to garment bag

code/game/machinery/computer/crew.dm, modular_skyrat/master_files/code/datums/traits/neutral.dm, modular_skyrat/master_files/code/modules/mob/living/carbon/human_helpers.dm, modular_skyrat/modules/company_imports/code/armament_datums/sol_defense.dm, modular_skyrat/modules/death_consequences_perk/death_consequences_trauma.dm
Makes it so all DNR does is make keyless mobs again - so it functions as intended without weird traits. Easy to fix, easy to cause, easy to diagnose. 
:cl:
fix: dnr behavior is consistent again
/:cl:
=> Makes DNR more reliable and simple again

modular_zubbers/code/modules/paperwork/fax.dm
Reverts Bubberstation/Bubberstation#668
=> Revert "[Event Testmerge Only] Adds reverie to the fax list"

code/modules/clothing/masks/gasmask.dm
Holy shit
Everyone hates it
I would actually resign if this was proven to not be tested (I did test it on the regular gas mask)
:cl:
del: The mask FOV is gone
/:cl:
=> Removes the mask FOV

modular_skyrat/modules/borgs/code/robot_upgrade.dm, modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/lustwish.dm
Adds a dominatrix borg module to lustwish (unfortunately someone still has to purchase it for the borg)
The module, when installed, adds a kinky shocker, whip, paddle, and tickle feather to the borg's repertoire
Gives borgs some kinky items for erp
:cl:
add: Borg dominatrix module to lustwish that gives them some dominatrix toys
/:cl:
=> Add dominatrix borg module to lustwish

tgui/packages/tgui/components/Dropdown.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/RandomizationButton.tsx
Mirror of https://github.com/Skyrat-SS13/Skyrat-tg/pull/26001
Fixes #1045 and fixes #1021
I promise
:cl:
fix: Dropdown options for quirks should now function properly
fix: Randomize button in character prefs should look normal
/:cl:
=> [SKYRAT MIRROR] Fixes some character prefs issues (#26001)

modular_zubbers/code/__DEFINES/send2relay.dm
Adds the new Singapore relay to the list
I didn't.
:cl:
server: We've added a new relay, located in the city of Singapore!
/:cl:
=> Add Singapore relay

modular_zubbers/modules/clothing/code/donator_clothing.dm, tgstation.dme
Renames it to "Elaborate dresscoat". Remvoes the mention of the tiziran noble house.
mista isnt nobility here
:cl:
spellcheck: The nobility dresscoat has been reflavored to not be nobility
/:cl:
=> [NO GBP] Updates my nova donator item, the Nobility Dresscoat, to better reflect the owner's status on bubber

modular_zubbers/code/modules/surgery/organs/internal/lungs/_brain.dm, tgstation.dme
Reverts Bubberstation/Bubberstation#751
Lots of bugs. So many bugs.
=> [DNM] Revert "Makes roundending significantly harder by making the brain (Almost) indestructible"

modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
Just donators from Skyrat asking for their stuff to be relocked.
N/A
N/A
:cl:
config: Relocked some donator items from Skyrat on request
/:cl:
=> Relocks Hypnobot Nut

modular_zubbers/modules/loadouts/overrides/loadout_items/loadout_datum.dm
Fixes early runtime issue with loadouts. Lists weren't being added properly.
Lists weren't being added properly.
If it compiles and passes linters, it werks.
:cl: BurgerBB
fix: Fixes early runtime issue with loadouts.
/:cl:
=> Fixes early runtime issue with loadouts.

code/datums/greyscale/_greyscale_config.dm
Needed for https://github.com/Bubberstation/Bubberstation/pull/1001
If it passes checks it works
:cl:
code: Bubber modular greyscale files permitted
/:cl:
=> Adds support for bubber modular GAGS files 

modular_skyrat/master_files/code/modules/reagents/medicine_reagents/medicine_reagents.dm
200 -> 20
See https://github.com/Skyrat-SS13/Skyrat-tg/pull/26422
=> Fixes using rezadone in linghusks (#26422)

modular_zubbers/modules/blooper/atoms_movable.dm
=> Give proper attribution for vocal barks code

modular_zubbers/modules/security/secmed/automapper.dm, tgstation.dme
Fixes #800 
Bugfix
I saw it with my very eyes
:cl:
fix: Void raptor now has the secmed locker
/:cl:
=> Fixes voidraptor not spawning secmed locker

config/game_options.txt, modular_zubbers/code/modules/mob/living/carbon/human/species_types/zombie.dm
Adds zombie hair and also adds abductors and zombies to the default config because it is kinda hard to debug something when it isn't configured for it.
Hair on zombie
:cl:
add: Zombie can now have hair
/:cl:
=> Zombie hair + updates root config

code/modules/projectiles/gun.dm, modular_skyrat/modules/gun_safety/code/safety_additions.dm
Removes gun safeties. BETTER FOLLOW RULE 1 OF GUN SAFETY BETTER NOW!
This is actually extremely noninvasive as far as uhhh uhhh uhhh modularity goes because it's just ONE file, all I had to do was disable the add component part of the proc but the proc is still defined so it doesn't error out on the guns that get the proc in other files.
I just find them really annoying.
Also the bigger thing, there's a very strong supermajority for removing it in the [suggestions](https://discord.com/channels/1059199070016655462/1071095123145924679/1212230353561849857) channel.
I loaded in, joined as captain, picked up all the guns in the armory and didn't see safeties on ANY of them.
:cl:Swiftfeather
del: Removed gun safeties.
/:cl:
=> RULE 1: Always keep the muzzle pointed in a safe direction

_maps/RandomRuins/IceRuins/skyrat/icemoon_underground_syndicate_base1_skyrat.dmm, _maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm, _maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_syndicate_base1_skyrat.dmm, _maps/RandomRuins/SpaceRuins/skyrat/interdynefob.dmm, tools/UpdatePaths/Scripts_Skyrat/26596_machineframe_state.txt, tools/UpdatePaths/Scripts_Skyrat/26798_machineframe_update_secured.txt
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26798
Some pretty nice fixes, dauntless mapfix included
:cl:
fix: Dauntless frames are no longer broken
/:cl:
=> Fixes machines on a few maps

modular_skyrat/modules/teshari/code/birdman_food.dm
See https://github.com/Skyrat-SS13/Skyrat-tg/pull/26819
FUCKING CHICKEN BURGERS LET'S FUCKING GOOOOOO
YOU. YES, **YOU**. This is so essential I am merging it right after an upstream. That's how important it is
=> Fixes chicken meatballs being uncraftable (#26819)

code/game/objects/structures/false_walls.dm
fixes #940
Finally, inner peace
:cl:
fix: False walls appear again
/:cl:
=> Fixes the false wall bug

modular_skyrat/modules/pet_owner/pet_owner.dm, modular_zubbers/code/datums/bubber_quirks/petowner.dm, tgstation.dme
see title
i got asked to do this and i understand completely why. this quirk has no reason to require a negative quirk because having a pet has no advantage.
observe how it has no cost
pet owner now costs 0 instead of 4 points
:cl:
balance: pet owner is free
/:cl:
=> Changes Pet Owner from 4 to 0

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/akula.dm, modular_zubbers/code/datums/akula_overrides.dm, tgstation.dme
Allows more customization
I don't like arbitary restrictions on species.
One line change
:cl:
config: Removes Akula Lore protection (Allows edit to species)
/:cl:
=> Removes Akula Lore Protection

code/modules/cargo/packs/imports.dm, modular_zubbers/code/modules/cargo/packs/metalsheets.dm, tgstation.dme
Reverts that thing. For the love of god, it was not fixed at all....random 15 milions bah...30 milions on cargo budget.
We dont need to ask people to not go overboard with it and punish people with inflation.
=> Revert "Re-enables the Galactic Materials Market as it's been fixed upstream."

modular_skyrat/modules/customization/game/objects/items/plushes.dm, modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm, modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
Edits items on request for Fuzlet, essentially genericfying them of name references.
Nah
=> Item Edits 3: Fuzlet

modular_zubbers/code/game/objects/items/reshirevolver.dm
Cost reduced
While 3,200 is mathematically obtainable. (1 hours and 20 minutes of bounties) I forgot to account that, human being do not like doing that.
N/A
:cl:
balance: Colt reevaluated their contract, the M1911 is cheaper now
/:cl:
=> Reduce m1911 cost to 2,600 credits instead of 3,200

_maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm
This PR adjusts some map properties:
* Removes budget display in spine hallway
* Add lock to bathroom located in kitchen
* Removes window from brig officer's dorms
The budget screen display should only be located in the bridge and the cargo. All bathrooms should have locks for privacy reasons, and the brig window is ill-fitting in the newer layout.
I have ran this map on my local server and confirm it works.
:cl:
add: Add door lock to dauntless restroom, and various map tweaks
/:cl:
=> Dauntless base map tweaks

code/game/machinery/computer/_computer.dm, code/game/machinery/computer/communications.dm, code/game/machinery/computer/law.dm, code/game/objects/items/circuitboards/computer_circuitboards.dm
https://github.com/tgstation/tgstation/pull/82574
=> (Early Pull) Moves the GPS component from the upload computers and communications console to the boards themselves when used

modular_skyrat/modules/company_imports/code/armament_datums/deforest_medical.dm
We are not adding the elite nanotrasen defib into cargo
=> Kills the Nanotrasen Elite Defib in the crib

_maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm, modular_zubbers/code/modules/mining/equipment/survival_pod.dm
=> Two integration test fix

modular_skyrat/master_files/code/modules/clothing/under/skirts_dresses.dm, modular_skyrat/modules/GAGS/json_configs/pants_shorts_skirts_dresses/jean_skirt.json, modular_zubbers/code/game/objects/structures/chalkboard.dm, modular_zubbers/code/modules/antagonists/bloodsucker/structures/crypt.dm, modular_zubbers/modules/shelves/shelf.dm
If you want this back do it upstream.
removes adjustability of jean skirts
=> removes adjustability of jean skirts (CI fix)

modular_skyrat/modules/title_screen/code/title_screen_html.dm
This reverts commit 499e688291338f4cdeffb0404bc13eea38c590ab.
We love unannounced changes directly to the master branch. Gotta be my favorite gender
There is a thing known as "Terrible UI design" and a Marquee is very much part of the things you do NOT want to use under any circumstance. (Aside from a meme with the announce/narrate verbs)
Please the lobby now looks way too dumb
A revert.
:cl:
fix: Fixes horrendous ui design
/:cl:
=> Revert "kia soul"

modular_zubbers/code/game/machinery/computer/orders/order_items/mining/order_pka.dm, modular_zubbers/code/game/objects/items/more_pkas.dm
What it says on the tin. Due to a bug, they currently have no firing cooldown, including the very high damage railgun (Though that one gets turbo screenshake. 
As the one who made that port, I feel responsible, but I also don't have the coding skills to figure out a fix, so I feel like the best course of action is to disable them until someone steps up to do it.
Very easy to abuse bug with high potential for abuse in PVP situations. 
It compiles I guess.
:cl:VrazzleDazzle
del: The PKA variants have been temporarily pruned due to a licensing issue with Kahraman Industries.
/:cl:
=> [LAZY REVERT] Disables the PKA alt-models

_maps/map_files/moonstation/moonstation.dmm
Improves Moonstation Disposals + Fixes missing wires for Medical Storage and NTRep office.
Improves Moonstation Disposals + Fixes missing wires for Medical Storage and NTRep office.
Improves Moonstation Disposals + Fixes missing wires for Medical Storage and NTRep office.
:cl: BurgerBB
add: Improves Moonstation Disposals + Fixes missing wires for Medical Storage and NTRep office.
/:cl:
=> Improves Moonstation Disposals + Fixes missing wires for Medical Storage and NTRep office.

code/game/objects/items/handcuffs.dm
=> [Upstream] Fixes handcuffs (oops) 

modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_under.dm
My last look at these, where I GaGsified it, I forgot to make it selectable by all members of command. There we go now.
Slutty command wants, slutty command gets.
:cl:
fix: fixed command access to slutty outfits.
/:cl:
=> Command stripper outfit to all of command.

code/datums/emotes.dm, code/modules/mob/emote.dm, code/modules/mob/living/carbon/human/emote.dm
https://github.com/Skyrat-SS13/Skyrat-tg/pull/27595
=> [EARLY MIRROR] [FIX] Various emote fixes

tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/bubbers/entombed.tsx
entomed was broken apparently, so was linters. So let's fix that
=> fixes linters and entombed

modular_skyrat/modules/blueshield/code/energy_resholver.dm
Removes the energy carbine with tasers from blueshield loadout
it's rapid fire tasers 
:cl:
del: Blueshields no longer get a taser gun in their choice beacon.
/:cl:
=> [Non-modular] Removes blueshield defender energy carbine 

modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
=> small item ckey update

modular_zubbers/code/modules/antagonists/bloodsucker/powers/feed.dm
Untested and unhinged
:cl:
fix: Bloodsucking no longer shows a cog above your head
/:cl:
=> Fixes bloodsucker sucking being obvious no matter what

_maps/ss13_construct.json
=> I am drunk

code/modules/bitrunning/server/threats.dm
…has a null ref, somehow
See title
Most of the time, due to this, a glitch won't even spawn
Went ingame, tested it, spawned as a glitch
:cl:
fix: Bitrunner glitches should now spawn properly more often
/:cl:
=> Fixes bitrunner glitches not spawning if the reference list has a invalid ref

_maps/map_files/moonstation/moonstation.dmm
Fixes Moonstation SM pipes from Atmos
Fixes Moonstation SM pipes from Atmos
Fixes Moonstation SM pipes from Atmos
:cl: BurgerBB
fix: Fixes Moonstation SM pipes from Atmos
/:cl:
=> Fixes Moonstation SM pipes from Atmos

code/game/objects/effects/spawners/random/maintenance.dm
EVERYTHING IS FINE
AAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
:cl: BurgerBB
fix: Fixes maint loot being absurd.
/:cl:
=> everything is fine

modular_zubbers/code/modules/borgs/code/robot_upgrade.dm
As the tin says
BRPED was removed on accident from a change that was not noticed because it was not modularized I have since modularized the change.
Tested locally it compiled and made sure it did as intended
:cl:
fix: engineering borg BRPED upgrade re-added
/:cl:
=> Re-adds the blues space RPED for engineering cyborgs

modular_zubbers/code/modules/research/designs/ai_module_designs.dm, modular_zubbers/code/modules/research/techweb/all_nodes.dm, tgstation.dme
We should probably have stuff that's in the code usable outside of bussing.
See above.
:cl:
add: Crewimov related modules are printable now.
/:cl:
=> Crewimov is printable now.

modular_zubbers/code/modules/storyteller/storytellers/storyteller_tellers.dm
as said
:cl:
qol: allows the ghost to be voted for at any pop
:/cl:
=> allow the ghost to be votable at any time

code/modules/events/_event.dm
fix annoying linter problem
problem go bye bye, no more linter scream
I press F5, I see no red lines, probably good then!
no cl
=> fix dum linter issue by commenting out a if

modular_zubbers/code/modules/mob/living/carbon/human/species/tajaran.dm
Fix runtime caused by upstream changes
Fix bug
:cl:
fix: Tajaran photocopier booty sprite fixed
/:cl:
=> Fix tajaran photocopier sprite

modular_zubbers/code/modules/taur_mechanics/serpentine_taur.dm
https://github.com/Bubberstation/Bubberstation/pull/1792
Title.
Turns out those args were needed after all.
bug ggbg bad
https://github.com/user-attachments/assets/db2bbbcc-8345-4514-9a03-2ee9efab5a28
:cl:
fix: Naga footstep sounds now work properly
/:cl:
=> [NO GBP] Hotfixes broken naga footstep sounds

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/LimaStation/LimaStation.dmm, _maps/map_files/biodome/biodome.dmm, _maps/map_files/moonstation/moonstation.dmm
Bubber map edits for https://github.com/Skyrat-SS13/Skyrat-tg/pull/28559
Map consistency
In previous changelog
=> Removes all security cameras from bathrooms and showers [Bubber]

modular_zubbers/code/modules/loadout/categories/~donator/donator_personal.dm
Updates donator_personal.dm to add snailomi to the ckey whitelist for the "Holographic Suit V4000".
Giving more tools to players is good! Sorry theres not much to say here
I have gotten approval from the original person to make the pr! I've asked them to comment affirming this so hopefully that follows
_I think that means it works_
:cl:
code: updated donator_personal.dm
/:cl:
=> Updates donator_personal.dm

_maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm, _maps/RandomRuins/SpaceRuins/bubberstation/space_dauntless.dmm, modular_zubbers/code/modules/vehicles/mech_fabricator.dm
Quick fix for another issue we have with tech webs related to the Justice exosuit in this case and the mech fab.
Found an oddball technet bug earlier, offers a fix for it until we can figure out the main issue. 
It compiles, you can build the exofab and disassemble it to get the right board. Still can be emagged. I'll post a video or screenshot if needed.
:cl:
fix: Made interdyne exofab circuit board actually work and made the exofab drop the right board
/:cl:
=> Dauntless exofab fix

code/modules/deathmatch/deathmatch_lobby.dm, modular_zubbers/code/modules/mob/living/carbon/human/species_types/abductor.dm
Does as the title says
closes #1661 
:cl:
fix: fixed abductors in deathmatch talking to station abductors
/:cl:
=> [Fix - Modular] fixes death match abductors being able to hear and talk to station abductors

modular_zubbers/code/_globalvars/lists/maintenance_loot_one_of_a_kind.dm
=> Fixes an oversight where looting trash piles had an about 0.005% chance to dust you.

modular_zubbers/code/game/objects/items/ai_modules/full_lawsets.dm
Adds a missing period to law 2 of the NT OS Safeguard V1.0 lawset.
OCD has been pleased.
:cl:
fix: Added a missing period to law 2 of the NT OS Safeguard V1.0 lawset.
/:cl:
=> Adds a missing period to the safeguard lawset

modular_skyrat/modules/quirks/neutral.dm
Fixes feline traits speech modifier
PurrrrrrrrrRRRRRRRRrrrrrrr
:cl: LT3
fix: Feline traits will give purr speech modifier
/:cl:
=> Fix feline traits giving speech modifier

modular_zubbers/code/modules/storyteller/event_defines/disabled_event_overrides.dm
=> Stops slaughter demons rolling

modular_skyrat/modules/jukebox/code/jukebox_subsystem.dm
Per title. 100 volume will be 50 percent volume.
My. Fucking. Ears....
It compiles.
:cl:
qol: Divides Jukebox volume by 2
/:cl:
=> [Salt PR] Divides the Jukebox volume by 2

code/datums/votes/map_vote.dm
Fixes a typo in map voting code that prevented the fallback "no maps to vote for" code to work.
I'm upset I didn't catch this.
Untested.
:cl: BurgerBB
fix: Fixes a typo in map voting code that prevented the fallback "no maps to vote for" code to work.
/:cl:
=> Fixes a typo in map voting code that prevented the fallback "no maps to vote for" code to work.

code/game/objects/items/climbingrope.dm, modular_zubbers/code/modules/surgery/organs/external/wings.dm
fixes #2042
Bugfix, and no more shit copypaste code
Worked in local testing
:cl:
fix: Moth climb works again
/:cl:
=> Moth wings can now climb again

_maps/map_files/moonstation/moonstation.dmm
Fixes Moonstation Library Wiring and Disposal Pipe
Fixes Moonstation Library Wiring and Disposal Pipe
Fixes Moonstation Library Wiring and Disposal Pipe
:cl: BurgerBB
fix: Fixes Moonstation Library Wiring and Disposal Pipe
/:cl:
=> Fixes Moonstation Library Wiring and Disposal Pipe

modular_zubbers/code/modules/antagonists/bloodsucker/powers/targeted/haste.dm
This PR reduces the range of haste to 5
Hastes has been often complained about being far too oppressive, and one of the issues is that haste has essentially full range anywhere you can see, 
:cl:
balance: The range of haste is now 5 tiles.
/:cl:
=> Reduces haste's range to 5

code/datums/storage/storage.dm
Early bugfix since this annoyed me too much.
=> Fixes backbacks becoming bricks

_maps/map_files/moonstation/moonstation.dmm
Fixes missing Moon Station wire.
God damn it.
a
:cl: BurgerBB
fix: Fixes missing Moon Station wire that caused Engineering (just the area outside the SM) to not be connected to the grid.
/:cl:
=> Fixes missing Moon Station wire that caused Engineering (just the area outside the SM) to not be connected to the grid.

modular_skyrat/modules/cargo/code/packs.dm
why did they add these. I, as much as the next dragon, think pitbulls suck, but this is kinda unnecessary. 
Lol. Lmao.
If github compiles it, it works
:cl:
del: Removed hostile pitbull crates.
/:cl:
=> Removes pitbull gorillas from cargo

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/moonstation/moonstation.dmm
Read changelog
Feel free to DM me with Box and Moon stuff with minor adjustments or QOL not worth its own PR. I'm not doing major room remaps or reorganizations. 
Minor map fixes and QOL
:cl:
add: Holofans and Pipescrubbers to Moon and Box's ordnance
add: Unbolted doors to the ordnance freeze chambers
fix: Missing power wire to QM's office on Box
del: Smart Organ storage in the middle of Box' medbay
/:cl:
=> Moonstation and Boxstation minor mapping fixes

modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/life.dm
Removes the malus for blood level gain for drinking from ghouls/vassals, as it's just unnecesary as feed already prevents from drinking too much from non-unique people.
It's a big too tough and kind of punishes for making ghouls/vassals, which I don't want
Compiles
:cl:
balance: Drinking from ghouls/vassals as a bloodsucker is no longer is 1/4th less effective than drinking from non ghouls/vassals
/:cl:
=> removes the malus for blood level gain for drinking from ghouls/vassals

README.md
Removes rule 2 on the repo's readme and adds an entry to rule 1.
- Bubberstation does not operate a strict "goodboy" points system or have defined goals, and anyone is welcome to contribute to this project. That being said, the maintainers of this project are free to curate comments as seen fit to uphold a respectful environment.
=> Repo Rule update

modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/life.dm
I am dumb and nobody checks my code, and unconditionally trusts me.
Fixes blood thickening point gain
Bloodsuckers can't level past 3
Tested ingame
:cl:
fix: Bloodsuckers now get blood thickening points
/:cl:
=> fixes blood level gain

code/datums/sprite_accessories.dm
Fixes https://github.com/Bubberstation/Bubberstation/issues/2225.
I'm 99% sure they were removed by accident given I never saw a PR specifically removing them.
I got no errors on my end and it worked fine. 
<details>
</details>
:cl:
fix: fixed the Big ears being removed, presumably by accident
/:cl:
=> Fixes the 'Big' cat ears being missing

code/modules/mob/living/carbon/carbon_defense.dm
Title.
TG upstream pull broke it, I fix it.
I tested it.
:cl:
fix: Headpats show a feedback message again.
/:cl:
=> Fixes headpatting

modular_skyrat/modules/company_imports/code/armament_datums/deforest_medical.dm
I forgot to add the medical combitool to cargo, because I honestly forgot you could buy advanced tools. I am a dum-dum.
If you can buy the others, why not this.
<details>
</details>
:cl:
fix: added combitool to deforest's cargo orders, I forgot to before.
/:cl:
=> Medical combitool to Deforest cargo.

html/changelogs/archive/2024-09.yml
Fixes https://github.com/Bubberstation/Bubberstation/issues/2226
=> Fix September 2024 changelog

modular_skyrat/master_files/code/modules/surgery/organs/internal/cyberimp/augments_arms.dm
This PR merely adds bonesetters and blood filters to the surgical implant, since they were added AFTER the implant was created and likely never considered.
Less space taken up by needing to carry the two extra tools if you have the implants.
<details>
</details>
:cl:
qol: added two extra tools to the surgical toolset; Bloodfilter and bonesetter.
/:cl:
=> Adds bonesetters and bloodfilters to surgical implants.

code/modules/client/preferences.dm
Adds 20 more slots I'm out of character slots I must create more creatures
I'm out of slots and need more
i changed a number
:cl:
add: Adds 20 more slots for free players and up to 100 slots for BYOND members
/:cl:
=> [NON-MODULAR] Adds 20 more slots I'm out of character slots I must create more creatures

_maps/map_files/moonstation/moonstation.dmm
Reverts Bubberstation/Bubberstation#2242
Dirty map merge. 
Byond's native tools squash your ambishions and dreams and is depreciated. Use strong.dmm to edit maps.
https://github.com/SpaiR/StrongDMM
Plus it's a LOT easier to use.
=> Revert "Removes GMM from Moonstation"

modular_zubbers/master_files/code/modules/reagents/reagent_containers/cups/_cup.dm
Plastic beaker capacity missed in https://github.com/Bubberstation/Bubberstation/pull/2301
:cl: sippykot
del: XL beaker is 150u again
/:cl:
=> Plastic beaker is 150 units

modular_skyrat/modules/cryosleep/code/cryopod.dm
Fixes https://github.com/Bubberstation/Bubberstation/issues/2306
It seemed unintended for them to be breakable given how they spam admin logs when broken
I didn't get any errors or runtimes.
<details>
</details>
:cl:
fix: fixed cryogenic consoles being destroyable
/:cl:
=> Makes cryogenic consoles indestructible

config/maps.txt
Remove entries for blueshift, limastation, and ss13_construct from `config/maps.txt`
They just cause errors at server start now
<details>
</details>
:cl:
config: Removed config entries for archived maps
/:cl:
=> Remove archived map config entries

modular_zubbers/code/modules/credits/credits.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/bubber/see_credits.tsx
As the title says, it's found in the Gameplay section of game preferences.
I've seen a lot of people asking for it, plus it doesn't immediately cover your screen if you have it off, so you can continue whatever you were doing without getting your screen covered by it.
It compiled and ran on local host
:cl:
qol: you can now toggle seeing end credits in preferences
/:cl:
=> Adds a toggle credits preference

code/__DEFINES/~~bubber_defines/chat.dm, tgstation.dme, tgui/packages/tgui-panel/chat/constants.ts, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/skyrat/looc.tsx
Adds options to TGUI chat filtering for LOOC and RLOOC.
Decide where you do or don't want to see these messages.
<details>
https://github.com/user-attachments/assets/4c66f4c1-243c-4fbf-9060-82b072b8f51d
</details>
:cl: LT3
qol: LOOC can now be individually enabled/disabled on chat tabs
/:cl:
=> Adds LOOC chat filter

_maps/bubber/automapper/templates/generic/interlink_adminoffice.dmm
Wrong boozeomat, just hard merge this.
Fix
it's the right objpath this time
=> Fix for #2328

modular_zubbers/code/modules/storyteller/storytellers/data/_track.dm, modular_zubbers/code/modules/storyteller/storytellers/tellers/storyteller_chill.dm
This makes the Default roll less mundane events, to 9 from 18. Mundane events would run every 10 minutes, and do things like give diseases, cause scrubber overflows, and more. These are important events, but should be less common.
Less mundane event spam. I did this on the Chill previously and it had a significant positive impact.
<details>
</details>
balance: Default Andy will spawn mundane events half as frequently.
/:cl:
=> Nerfs the Default slightly

code/controllers/subsystem/job.dm, code/modules/mob/dead/new_player/new_player.dm, modular_skyrat/modules/alternative_job_titles/code/job.dm
Add `?` operator to `alt_job_titles` accesses
Fixes #2209 
Spawned in as a guest with my proper equipment and title.
<details>
</details>
Nothing relevant to players
=> Fix guests spawning in naked

code/datums/actions/items/beserk.dm, code/modules/mining/lavaland/tendril_loot.dm
Does as the title says, cleans up the code a bit and modernizes it, as well as making it call its parent.
It's more readable this way, plus it properly calls its parent proc now.
It's merged on /tg/
=> [Cherry-Pick] Rewrites the code in beserk.dm

code/modules/clothing/suits/lasertag.dm, modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
Noticed these three items being configured to a digi variant that doesn't exist. They don't even need a digi variant as they are very short.
Less black and purple squares going on for my digi-dudes.
:cl:
fix: Fixed some broken digi outfit variations 
/:cl:
=> Digi variation fixes

html/changelogs/archive/2024-11.yml
=> Fix some busted changelog entries

modular_zubbers/code/modules/loadout/categories/~donator/donator_personal.dm
<details>
</details>
N/A Not Player facing
=> Update IIDMA WL

tgui/packages/tgui/interfaces/FoodPreferences.tsx
=> Spellcheck DLC

modular_zubbers/code/modules/vending/multisec.dm
Same as the title, its a one line change
Strangely it lacks it, and beret doesnt have mutli variant options. Extra drip
One line of change, it works. 
:cl:
add: Added white sec beret to their clothing vendor. 
/:cl:
=> Adds white beret variant to multisec vendor. 

modular_zubbers/code/datums/wounds/permanent_limp.dm
Quick fix to test, hopefully this stops people from getting limp wounds from falling over in a light breeze.
=> Hopefully fix everything making you limp

tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx
Brings back the species menu nuked in https://github.com/Bubberstation/Bubberstation/pull/2519
Closes https://github.com/Bubberstation/Bubberstation/issues/2583
:cl: LT3
fix: The select species menu is back
/:cl:
=> Bring back the species menu

code/modules/power/supermatter/supermatter.dm
Adds the missing description for the festive supermatter
<details>
</details>
=> Festive supermatter description

code/modules/clothing/glasses/engine_goggles.dm
Early pull of https://github.com/tgstation/tgstation/pull/88075
Bugg
<details>
</details>
:cl:
fix: fixes atmos goggles not showing the temperature of turfs.
/:cl:
=> Fixes atmos goggles not showing the temperature of turfs

_maps/map_files/biodome/biodome.dmm
Fixes a couple pipe errors on Biodome that prevent disposals from working
Fixes #2611
Trust ‼️ 
:cl:
map: fixes some disposal pipes on Biodome.
/:cl:
=> Biodome pipe fixes

modular_skyrat/modules/company_imports/code/armament_datums/deforest_medical.dm
(re?)adds the "civil defense symptom support kit" to cargo
why couldn't you import this again? it's a bunch of chems to stop someone from puking their guts out or such, and helps out people with bad quirks - maybe it should be added to medical orders as a crate, but at that point you can just cook some of these
i swear i tested it
:cl:
add: you can buy a civil defense symptom support kit from company imports
/:cl:
=> Cdef symptom kit

code/modules/antagonists/space_dragon/space_dragon.dm
re-adds missing return in dragon code
mistakes that may cause edge cases
null
<details>
</details>
:cl:
no cl
/:cl:
=> Re-adds missing return in dragon code

tgui/packages/tgui/interfaces/PreferencesMenu/loadout/ModifyPanel.tsx
Oops!
Editing items good!
<details>
</details>
:cl:
fix: Loadout items can be edited again.
/:cl:
=> Fixes A Fucky Wucky With Loadouts

_maps/RandomRuins/IceRuins/bubberstation/icemoon_persistence.dmm, _maps/RandomRuins/LavaRuins/bubberstation/lavaland_persistence.dmm
Various fixes and clean up items for persistence
So far the list includes
- Readding IV drip to medical
- Readding smithing tools
- floating lights removal
- correction of chap vendor for morale officer have density
- fix for morale officer disposals
We like it more when shit works.
I'll add this properly later.
<details>
</details>
:cl:
fix: Various persistence bug fixes 
/:cl:
=> Persistence bug fixes

modular_zubbers/code/datums/quirks/negative_quirks/sol_weakness.dm
Fixes sol quirk having wrong the's
It bothers people when the english is actually engrish.
<details>
</details>
:cl:
fix: Sol quirk should properly use the when appropiate
/:cl:
=> fix sol quirk messages

code/modules/holiday/holidays.dm, modular_zubbers/master_files/code/modules/holiday/holiday.dm
Extends the Xmas holiday to start at 18 December. Adds alternate colour palettes.
Jollymaxxing
:cl: LT3
balance: Xmas week has been extended to start at 18 December, get your jollymaxxing on
/:cl:
=> Makes the xmas period longer

modular_zubbers/code/modules/antagonists/bloodsucker/clans/clan_nosferatu.dm
p_they is confusing, sorry, fixes nosferatu examine
it's currently bad engrish
i hide my shame with no changelog
=> fix nosferatu examine

modular_skyrat/modules/title_screen/code/new_player.dm
Fixes this one thing for possible future memes.
=> Fixes the swap server button

modular_zubbers/maps/offstation/persistence/code.dm
Just disables persistance on it.
=> The first code modifications to this branch.

code/controllers/subsystem/ticker.dm, config/bubbers/bubbers_config.txt, modular_skyrat/master_files/code/controllers/configuration/entries/skyrat_config_entries.dm, modular_zubbers/maps/offstation/persistence/code.dm
Basically allows you the option to either have a default storyteller, or to have voting.
It works
:cl:
config: You can set a default storyteller to bypass voting.
/:cl:
=> Storyteller Config Option

modular_zubbers/code/game/machinery/flatpacker.dm, modular_zubbers/master_files/code/modules/holiday/holiday.dm
Extending Christmas season was not meant to give those postal workers two weeks off!
:cl: LT3
fix: All the letters from Santa that have been horded at the postal service have been recovered and delivered
/:cl:
=> Fix the Christmas postal strike

code/modules/events/holiday/xmas.dm
Reverts Bubberstation/Bubberstation#912
Please be nice, I'm feeling festive :)
=> Revert "Makes the christmas tree safe" (Please use broken gear responsibly)

code/modules/antagonists/malf_ai/malf_ai_modules.dm, modular_zubbers/code/game/gamemodes/objectives/overrides.dm
=> Reenable more antag stuff

code/game/machinery/computer/communications.dm
Title. Fixes #2706 
</details>
:cl:
fix: Fixes comm consoles being able to change alert level during Delta+
/:cl:
=> Fixes people changing the alert level from Delta or above

modular_skyrat/master_files/code/game/objects/structures/sauna_oven.dm
Split item interaction for sauna ovens from an `attackby` to `wrench_act` and `item_interaction`
New standards for attack chain stuff
You gotta trust me on this one
:cl:
code: cleaned up sauna oven item interaction code.
/:cl:
=> Sauna oven attack chain refactor

modular_zubbers/master_files/code/controllers/subsystem/tts.dm, tgstation.dme
Test merge for the test server.
=> Disables the TTS disable.

README.md
removed duplicate images in the readme.md
It was doubled up
<details>
Master:
My branch:
</details>
nothing player facing
=> Fixes merge skew with Readme.md

modular_skyrat/modules/ghostcafe/code/robot_ghostcafe.dm
Fixes #2821
Bugfixman good
Compiled and work on a private server
<details>
</details>
:cl:
fix: fixes the cafeborg shakers
/:cl:
=> Fixes cafeborg synthesizers

code/__DEFINES/logging.dm, code/__HELPERS/logging/debug.dm, code/controllers/subsystem/tts.dm, code/datums/http.dm, code/modules/logging/categories/log_category_debug.dm
Logs whenever there's a HTTP error on the DM side of TTS.
Can help identify bugs and errors.
=> Adds TTS logging when something goes wrong (#88841)

code/game/machinery/dance_machine.dm
Early pull of https://github.com/tgstation/tgstation/pull/88822
Skyrat jukebox code had this and then I ripped it out so technically I can call this a bug fix
I promise
=> Add currently playing song name to jukebox examine text (#88822)

code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/silicon/silicon.dm
Actually buffs borg health. I accidently put the edits inside carbon instead of silicon. Whoops
#2644 
It works now.
=> Actually Buffs borg health to 135. 

_maps/map_files/biodome/biodome.dmm
Biodome had multiple missing disposal pipe segments and routing issues, this fixes them all
The mail never stops
I wrote a tool to test all disposal units on station making it to disposals and every mail destination ending up in the right place and everything passed
:cl:
map: fixes Biodome disposals issues.
/:cl:
=> Unfucks Biodome disposals

SQL/bubber_schema.sql, code/modules/paperwork/fax.dm
Faxes get logged into the SQL server, for discord retreival. Will integrate with my bot. 
More admins responding and seeing your faxes. 
:cl:
admin: Faxes now get sent to the database. 
/:cl:
=> Faxes get logged into the SQL server, for discord retreival.

modular_skyrat/modules/server_overflow/code/client_procs.dm
=> Fixes the overflow server prompt

code/__DEFINES/~~bubber_defines/chat.dm, code/__DEFINES/~~bubber_defines/span.dm, modular_skyrat/modules/verbs/code/subtle.dm, tgui/packages/tgui-panel/chat/constants.ts, tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss, tgui/packages/tgui-panel/styles/tgchat/chat-light.scss, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/bubber/subtle_sound.tsx
Adds an optional soft notification sound for subtle, using the same pref as the subtler notification.
It's nice to have the option to have subtle sounds as well, particularly now that interactions use them.
:cl: LT3
sound: Subtle now has a sound notification alongside subtler
qol: Subtle/subtler now has a TG chat filter
/:cl:
=> Subtle notification sound/chat filter

code/controllers/subsystem/pai.dm, code/game/machinery/computer/records/medical.dm, code/game/machinery/computer/records/records.dm
I don't think the PAI one is actually a major issue but it might be so
I'm just bein safe
Anyways sanitizing input is probably a good
quickport of https://github.com/tgstation/tgstation/pull/89049
no CL
=> [s] Records / PAI patching (#89049)

tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
One more adjustment for consistency
=> Brighter dark mode subtle/subtler spans 2

html/changelogs/archive/2025-01.yml
Fix the hypo changelog as i forgot to edit it when I changed the PR's features around
A accurate changelong really helps to understand what changes have occured
<details>
</details>
do NOT update changelog for this PR
=> Fix the hypo changelog

modular_skyrat/modules/death_consequences_perk/death_consequences_trauma.dm
Title.
bugs bad
<details>
</details>
:cl:
fix: Death degradation no longer instantly downs you
/:cl:
=> Fixes death degradation stamina damage always downing you

modular_skyrat/modules/records_on_examine/code/examine.dm
Title. Now if you see the link, you know itll give you something.
bugs bad
<details>
</details>
:cl:
fix: Record links now only appear if there are records to view
/:cl:
=> Fixes record links appearing for empty records

code/__HELPERS/randoms.dm
Title.
very funny when it happens but it probably shouldnt
none
:cl:
fix: Silver slimes can no longer produce fucking contagious changeling zombie virus
/:cl:
=> Removes CSV from the silver slime pool

modular_skyrat/master_files/code/modules/loadout/categories/donator_personal.dm
the path for the caged dress was wrong so it was a missing texture
missing texture bad, also dress cute
=> Fix caged dress from loadout menu

code/modules/mapfluff/ruins/spaceruin_code/hilbertshotel.dm, modular_skyrat/modules/ghostcafe/code/hilbertshotel_ghost.dm, modular_skyrat/modules/hotel_rooms/prisoninfdorm.dmm
Adds a new hotel room as of the request of Leathergnome who also made said hotel room, all credit goes to him i just PRed it, ontop of that this PR also fixes https://github.com/Bubberstation/Bubberstation/pull/3078 as said rooms were forgotten to be added to the selectable list, shit happens love the new rooms by the way.
Another dorms room to enjoy and fix for already PRed ones
Works and Complies on localhost
:cl:
map: Added new Hotel room
fix: Fixed the other hotel rooms not showing up from a different PR
/:cl:
=> Fixes hotel rooms and adds new one

modular_zubbers/code/modules/research/techweb/all_nodes.dm
Add missing parent call to override
Fixes #3120 
<details>
</details>
:cl:
fix: fixed the utility cyborg upgrades node missing stuff
/:cl:
=> Fix missing utility borg upgrades

code/modules/mapfluff/ruins/spaceruin_code/hilbertshotel.dm, modular_skyrat/modules/ghostcafe/code/hilbertshotel_ghost.dm, modular_skyrat/modules/hotel_rooms/corporateoffice.dmm, modular_skyrat/modules/hotel_rooms/grotto - Copy.dmm, modular_skyrat/modules/hotel_rooms/grotto.dmm, modular_skyrat/modules/hotel_rooms/grottoalt.dmm, modular_skyrat/modules/hotel_rooms/recovery.dmm
Hello! Since I've been bored, I decided to test my mapping muscles, and so I come to you with 3 Infinite Dorms maps.
**1. Corporate Office** 
First one's quite easy and simple, a rather large Corporate Office, comes with all the expected amenities; fake bookcases, coffee, donuts, luxury alcohol, cigars, stamps, paperwork, intercoms, Italian maple desks, comfy chairs, secure consoles, motion-sensitive camera that keeps blinking red for whatever reason. Ideal for anyone with more interests in the 'corpo' side, or just for people who want to ERP in an office environment. 
**2. Recovery Wing**
A more hospital-themed dorm, thought of as the Recovery Ward of the whatever Facility that NT uses to keep putting spessmen together after they have been blown up twenty times during one shift. Comes …
=> Adds 3 (well, technically 4) More Infinite Dorms Maps

modular_skyrat/modules/modular_items/code/recipes_misc.dm
Chisel is craftable 1 wood 1 iron screwdriver, people wanted in suggestions channel with like fuckign 12 voters in 24 hours so that's insane amounts and here you go
[
](url)
I rest my case
:cl:
add: Chisels can be crafted [1 wood, 1 iron, screwdriver]
/:cl:
=> Craftable chisels [suggestions channel post]

code/controllers/subsystem/statpanel.dm, html/changelogs/AutoChangeLog-pr-3164.yml
Changes the warning message to inform that 515 isn't supported.
=> Version 515 warning message

html/changelogs/archive/2024-10.yml, html/changelogs/archive/2024-11.yml, html/changelogs/archive/2024-12.yml, html/changelogs/archive/2025-01.yml, html/changelogs/archive/2025-02.yml
Fixes the last four months of changelogs cause they got fucked up in the upstream pull. This was done with an automated tool but I glanced over it and it looks like everything came out okay, and it works in game without bluescreening.
Fixes #3241 
oh i promise
=> Fix the changelog

_maps/bubber/automapper/templates/NebulaStation/nebulastation_supermatter.dmm
ef3095bffcb12e8073380d0bab55ee1b74f821cb changed the wiring in the nebula SM room and our automapper template needs to be updated to accommodate this
I am hopelessly dependent on the green checkmark
<details>
</details>
=> Fix Nebulastation failing unit tests

tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/MainPage.tsx
welcome to my awesome cherry pick
:cl:
fix: fixed character prefs bluescreening for certain species
/:cl:
=> Fix Plasmamen Prefs Issues Due To Plasmamen Lacking Content (#90029)

code/modules/antagonists/malf_ai/malf_ai_module_picker.dm, code/modules/antagonists/malf_ai/malf_ai_modules.dm, modular_skyrat/modules/alt_vox/code/vox_procs.dm
Title
the process was cock and ball torture before
it works, source:dude trust me
<details>
</details>
:cl:
admin:makes it easier for admins to bus malf nuke
/:cl:
=> makes it easier for admins to bus malf nuke

code/controllers/subsystem/ticker.dm, modular_zubbers/code/modules/quote_of_the_round/ticker.dm
I toppled a house of cards when I merged in the new changes to game announcements
Being notified when a new round starts is good
<details>
</details>
=> Fix discord round announcements being broken

modular_zubbers/code/modules/vending/clothmate.dm
As it says on the tin
:cl: LT3
add: Miniskirt now available in the clothesmate
/:cl:
=> Add miniskirt to clothesmate

modular_zubbers/code/datums/quirks/neutral_quirks/seamless_clothes.dm
description
fix
<details>
</details>
:cl:
fix: Modsuits no longer delete the seamless heels quirk.
/:cl:
=> Fixes modsuits deleting seamless heels.

modular_zubbers/code/modules/skub/skub.dm
the override should append to the global maint loot list not replace it
I'm anti-skub
I did this PR from my phone in bed because there's no power
=> Fix every fucking piece of maint loot being skub

modular_zubbers/code/datums/mood_events/_mood_event.dm, modular_zubbers/code/modules/languages/empathy.dm, tgstation.dme
BASED ON SANITY SHADEKIN EMPATHY WILL:
-Take more or less time to send
-At lowest levels of sanity the message starts to break down some
-Be a different color in chat
Shadekin empathy is communication through FEELINGS so it being better/worse based on how you're FEELING makes sense (to me)
<details>
</details>
:cl:
balance: shadekin empathy is better/worse based on mood
/:cl:
=> Adds more flavor to shadekin empathy

modular_zubbers/code/modules/emotes/emotes.dm
Adds a Sad Kweh emote from the two unused raptor sound files.
You can now sad birdly.
It compiles and was tested locally.
https://github.com/user-attachments/assets/bc5f31fb-ad12-4026-be94-d28d2db542df
:cl:
add: *skweh emote to be sad
/:cl:
=> Allows players to be sad like raptors

_maps/RandomRuins/IceRuins/bubberstation/icemoon_persistence.dmm, _maps/RandomRuins/LavaRuins/bubberstation/lavaland_persistence.dmm
Make them speak on cybersun frequency
Fixes #3446 
<details>
</details>
:cl:
fix: fixed persistence medbots speaking on wrong radio frequency
/:cl:
=> Fix persistence medbots speaking on syndicate frequency

code/modules/shuttle/mobile_port/mobile_port.dm, code/modules/shuttle/mobile_port/variants/arrivals.dm, code/modules/shuttle/mobile_port/variants/emergency/emergency.dm, modular_skyrat/master_files/code/modules/shuttle/shuttle.dm
The code for these things got lost in an upstream because shuttle code got split into multiple files
Fixes #3251 
I tested it and the shuttle went bwwwwrrmmmmm pshewww and the door bolts went chk 
:cl:
fix: fixed shuttles missing landing/take off engine sounds
fix: fixed shuttles not bolting/unbolting their doors when moving
/:cl:
=> Fix shuttles no longer making sounds or (un)bolting doors

modular_skyrat/modules/primitive_structures/code/storage_structures.dm
Title!
Bugfix, my immersion was ruined
<details>
</details>
:cl:Goku
fix: Fix wooden shelves turning into metal rack parts when broken.
/:cl:
=> [FIX] Fixes Wooden shelves turning into metal racks when broken.

modular_skyrat/modules/hev_suit/code/hev_suit.dm
`ADD_TRAIT`/`REMOVE_TRAIT` don't take lists you need to use a proc for that
Fixes #3484
<details>
</details>
:cl:
fix: fixed HEV suit not turning on properly
/:cl:
=> Fix HEV armor not fully initializing

code/datums/mood.dm, modular_skyrat/modules/alcohol_processing/code/alcohol_processing.dm
Fix the alcohol status moodlet to work with our blood alcohol system.
:cl: LT3
fix: Mood will show your correct drunkenness status
/:cl:
=> Fix alcohol moodlet

modular_skyrat/modules/deforest_medical_items/code/storage_items.dm, modular_zubbers/code/game/objects/items/storage/medkit.dm
Fixes delayed release for the surgery pain meds.
:cl: LT3
fix: Fixed lidocaine/amollin pills having delayed effect
/:cl:
=> Fix lidocaine/amollin pill delayed release

modular_skyrat/modules/sec_haul/code/misc/gun_redemption.dm, modular_zubbers/code/modules/syndicate_offstation/selection_beacons/weapon_redemption.dm
fix compile by adding missing quotes
guh
=> fix compile by adding missing quotes

_maps/map_files/generic/CentCom_skyrat_z2.dmm
Adds a SAD to the interlink. Shrimple as.
Admin request.
Closes https://github.com/Bubberstation/Bubberstation/issues/3531
I didn't. Strong DMM hasn't failed me yet.
<details>
</details>
:cl: UvvU
add: Added a SAD to the interlink
/:cl:
=> Adds a SAD to the interlink.

modular_zubbers/code/modules/storyteller/storytellers/tellers/_storyteller.dm
Creates better logs for what events are selected at roundstart
None
=> Improved logging for roundstart event selection

code/__HELPERS/~bubber_helpers/lists.dm, modular_zubbers/code/modules/storyteller/gamemode.dm, modular_zubbers/code/modules/storyteller/storytellers/tellers/_storyteller.dm, tgstation.dme
More storyteller logging data
None
=> Improved storyteller logging 2

modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/romulus_technology/rifle.dm
Projectile Damage Multiplier 1 -> 0.75
Projectile Wound Bonus -35 -> -20
<p class=MsoNormal><b><u><span style='font-size:12.0pt;line-height:107%;
font-family:"Times New Roman",serif;mso-ansi-language:EN-GB'>Method:<o:p></o:p></span></u></b></p>
<p class=MsoNormal><span style='font-size:10.0pt;line-height:107%;font-family:
"Times New Roman",serif;mso-ansi-language:EN-GB'>The following tests were all
done on a standard HOS-outfitted human on the version that this PR is on. There
are no discrepancies between server and test server the data was taken on.<o:p></o:p></span></p>
<p class=MsoNormal><span style='font-size:10.0pt;line-height:107%;font-family:
"Times New Roman",serif;mso-ansi-language:EN-GB'>The method for taking the rate
of fire of the weapons is recording the screen from the …
=> Nerfs the RomTech Carbine to sec standards

modular_skyrat/master_files/code/modules/loadout/categories/donator_personal.dm, modular_zubbers/code/modules/loadout/categories/~donator/donator_personal.dm
I said I'd make the med stuff open to all once I had GAGS for the bag, but really never got around to it. They're in the medical clothes vendor now too. Enabling the cat stamp to go along with giving the HoP approved/denied stamps.
None
=> Remove ckey whitelists from a few loadout items

code/__DEFINES/~~bubber_defines/traits/nanites.dm, code/game/machinery/scanner_gate.dm, modular_zubbers/code/datums/components/nanites.dm, modular_zubbers/code/modules/nanites/items/boards.dm, modular_zubbers/code/modules/nanites/machines/nanite_chamber_computer.dm, modular_zubbers/code/modules/nanites/machines/nanite_cloud_controller.dm, modular_zubbers/code/modules/nanites/nanite_programs/utility.dm, tgui/packages/tgui/interfaces/NaniteChamberControl.tsx, tgui/packages/tgui/interfaces/NaniteCloudControl.tsx, tgui/packages/tgui/interfaces/ScannerGate.jsx
Add a new signal to nanites to get their cloud ID, implement the nanite detection function on scan gates to match cloud ID
This was half implemented now its full implemented
<details>
</details>
:cl:
add: scanner gates can now be set to detect certain nanite cloud IDs
/:cl:
=> Implement nanite scanner gate detection

modular_zubbers/code/modules/antagonists/malf/remove_malf.dm
moffson now should work at anytime. 
doesn't behave weird anymore.
<details>
</details>
:cl:
code: moffson should work without needing an ai to be damaged now. 
/:cl:
=> Moffson Patch

code/modules/events/fake_virus.dm
proc passes the list of victims instead of the current victim in the loop and it runtimes
Bug
No
No
=> Fix runtime in fake virus event

config/skyrat/skyrat_config.txt, modular_skyrat/master_files/code/controllers/configuration/entries/skyrat_config_entries.dm, modular_skyrat/modules/decay_subsystem/code/decaySS.dm
Adds some configuration values for SSDecay, and enables by default.
Nothing player facing
=> SSDecay config values

modular_zubbers/code/modules/nanites/nanite_programs/suppression.dm, modular_zubbers/code/modules/nanites/program_designs.dm
fix nanites leaving bad moods stuck forever
bug bad
nope
<details>
</details>
:cl:
fix: fix nanites leaving bad moods stuck forever
/:cl:
=> fix nanites leaving bad moods stuck forever

modular_skyrat/modules/colony_fabricator/code/machines/ore_silo.dm
I don't fucking know what happened here
This thing is runtiming like crazy because its constantly overwriting its own signal listeners
I didn't but I physically cannot make it worse than it already is
Nothing player facing
=> Fix colony ore silo trying to add a new repackable element to it every time someone inserts materials

modular_zubbers/maps/offstation/persistence/area.dm
I added rustoleum.
:cl:
fix: Percy no longer rusts away.
/:cl:
=> Percy has been rust-proofed.

modular_zubbers/code/modules/loadout/categories/pocket.dm
Adds table clocks as a loadout item
someone wanted it
:cl:
add: Table clocks are now a loadout item.
/:cl:
=> Tableclocks are now loadout items

tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/loadout/ItemDisplay.tsx
=> Fix loadout tab bluescreen

code/modules/uplink/uplink_devices.dm, modular_zubbers/code/modules/opposing_force/code/equipment/antagonist_powers.dm, modular_zubbers/code/modules/uplink/uplink_devices.dm, tgstation.dme
(Informal PR, I apologize sincerely but I cannot stay serious with 4 PR's today fixing issues and stuff)
Hello Snajper. You might not remember this, but I do. It's been a year since this happened, but it just popped into my memory. I asked for 25 TC and the "empty uplink". And the uplink... had 20 TC... and I felt GUILTY about asking for MORE TC. 
Thank you for being memorable enough to make me randomly access that memory right now and FIX that stupid thing FOREVER! 
LIES, LIES, LIES, FALSEHOODS! 
I am an honest man and will say the code didn't compile at first due to taur-related things, but after mashing compile it is now errorless.
:cl:
fix: corrected a misleading opfor item
/:cl:
=> Fixes a BLATANT LIE in the OPFOR SYSTEM 

modular_zubbers/maps/offstation/dauntless/ID_trims.dm, modular_zubbers/maps/offstation/persistence/ID_trims.dm
Fixes Persistence/Dauntless Cargo tech/miner access, letting them use the ORM
It's a bit silly for the person responsible for mining to not have access to their machines.
<details>
</details>
:cl:
fix: Persistence cargo techs can access their ORM. 
/:cl:
=> Persistance cargo tech ORM access 

code/modules/mod/mod_activation.dm
A recent upstream changed how modsuits overslotting on clothing is handled.
This is a temporary revert back to old behavior, until it's decided how we're going to handle this.
=> Revert of Modsuit overslotting changes

modular_skyrat/modules/decay_subsystem/code/decaySS.dm
Fixes init order of SSdecay
:cl: LT3
fix: Station dirt and grime spawns properly
/:cl:
=> Fix SSdecay

modular_skyrat/modules/deforest_medical_items/code/healing_stack_items.dm
Ports: https://github.com/NovaSector/NovaSector/pull/4818
people have been complaining about some items not working, and nova has a pr about that so, yeah
the death of skyrat and its consequences...
hopefully fixes bugs people been talking about in #medical
I didn't
it compiled though
:cl:
fix: fixed some deforest items not working
/:cl:
=> ports Nova's Fix wound treatment medical items #4818

.github/CODEOWNERS
Changes codeowners as most everyone doesn't exist or review PR's
Fixes old stuff that nobody updated
<details>
</details>
:cl:
/:cl:
=> Updates codeowners to something sane

code/datums/storage/subtypes/belts.dm
Got lost in the last last upstream
Fixes #3751 
<details>
</details>
:cl:
fix: you can fit a trash bag on the janibelt again
/:cl:
=> Fix trash bag not going on janitor belt

modular_zubbers/code/modules/antagonists/bloodsucker/structures/coffin.dm, modular_zubbers/code/modules/antagonists/bloodsucker/structures/crypt.dm
fix coffin locking and candelabrum toggling & remove alt click UI from these
bug fix good
<details>
</details>
:cl:
fix: coffin locking
fix: candelabrum toggling with right click
/:cl:
=> fix coffin locking and candelabrum toggling & remove alt click UI from these

modular_skyrat/modules/black_mesa/code/mobs/bullsquid.dm, modular_skyrat/modules/black_mesa/code/mobs/headcrab.dm, modular_skyrat/modules/black_mesa/code/mobs/houndeye.dm, modular_skyrat/modules/black_mesa/code/mobs/vortigaunt.dm
This is supposed to be a bitfield but these mobs give it a list which runtimes
Bug fix
I didn't
N/A
=> Fix mob_biotypes on xen mobs

modular_skyrat/master_files/code/modules/client/preferences/brain.dm, modular_skyrat/modules/customization/modules/client/augment/organs.dm, modular_skyrat/modules/modular_persistence/code/modular_persistence.dm
`/datum/modular_persistence` wasn't keeping things tidy
Hard del bad
Yes
N/A
=> Fix brain hard delete

modular_zubbers/code/modules/nanites/nanite_programs.dm, modular_zubbers/code/modules/nanites/nanite_programs/healing.dm, modular_zubbers/code/modules/nanites/nanite_programs/suppression.dm, modular_zubbers/code/modules/nanites/nanite_programs/utility.dm
Makes nanite sting actually work and nanite defib now starts your heart
Programs that do what you expect is good.
Tested indeed
<details>
</details>
:cl:
fix: Nanites sting now actually works and has better feedback
fix: Nanite defib now restarts your heart, or gives you a heart attack if you're alive.
/:cl:
=> Makes nanite sting actually work and nanite defib now starts your heart

_maps/bubber/automapper/templates/NebulaStation/nebulastation_sauna.dmm
Fixes broken disposals pipe at NebulaStation sauna.
<details>
</details>
:cl: LT3
fix: Fixed NebulaStation disposals dumping into the sauna
/:cl:
=> Fix NebulaStation disposals

_maps/RandomRuins/IceRuins/bubberstation/icemoon_persistence.dmm, tools/maplint/lints/window_spawner.yml
Fix some linter failing hedges on Persistence
=> Fix Persistence linters

modular_skyrat/modules/records_on_examine/code/record_manifest.dm, tgui/packages/tgui/interfaces/RecordManifest.jsx
Closes https://github.com/Bubberstation/Bubberstation/issues/2487
Also updates the head list.
Bugs bad
<details>
</details>
:cl:
fix: The exploitable manifest now works
/:cl:
=> Fixes the exploitable manifest

code/datums/storage/subtypes/belts.dm
Fixes oversight with the wizard's magic wand belt.
Fixes oversight with the wizard's magic wand belt.
Fixes oversight with the wizard's magic wand belt.
:cl: BurgerBB
fix: Fixes oversight with the wizard's magic wand belt.
/:cl:
=> Fixes oversight with the wizard's magic wand belt.

_maps/bubber/automapper/automapper_config.toml, _maps/bubber/automapper/templates/lavaland/lavaland_turbines.dmm, _maps/map_files/Mining/Lavaland.dmm
I am making this PR on behalf of Nyatsuki.
Adds wind turbines to the Lavaland mining base
The lavaland base is a TG map file, and rounds on tg rarely last more than 90 minutes. With our 150-180 minute average rund time, the SMES units on the lavaland base usualy run dry towards the end of the round, killing power to the entire mining base.
<details>
</details>
:cl:
map: Adds wind turbines to the Lavaland mining base.
/:cl:
=> Changes Lavaland Mining Base

modular_skyrat/modules/title_screen/code/new_player.dm
The timetable has been accelerated
Yes
Yes
:cl: Bubberstation Staff
balance: Time is almost up.
/:cl:
=> Change vetted deadline to June 16 2025

modular_zubbers/code/game/objects/items/plushes.dm
Updates the lazy synth plushie with more attack verbs. 
Work wanted me to learn github anyway so i thought i'd do a little thing at least.
He does more than just squish all over you now. 
Honestly i wanted to make him have a chance to pop out an egg when squeezed, but thats a bit too complex for me stilll, pretty sure i lost a few cells trying to understand the cooldown system, so its only a few more attack verbs for now.
<details>
</details>
:cl:
add: More attack verbs to the lazy synth plushie
/:cl:
=> Lazy plush update.

modular_zubbers/code/modules/loadout/categories/~donator/donator_personal.dm
Gives the 2 winners of the event the hat
Event Good
no
<details>
</details>
No need to CL this
=> Event Reward Golden Pinwheel Hat Ignore Freeze PLS

code/modules/surgery/advanced/brainwashing.dm, code/modules/surgery/advanced/lobotomy.dm, code/modules/surgery/blood_filter.dm, code/modules/surgery/brain_surgery.dm, code/modules/surgery/gastrectomy.dm, code/modules/surgery/organ_manipulation.dm, code/modules/surgery/sleeper_protocol.dm, modular_skyrat/modules/synths/code/surgery/robot_brain_surgery.dm
fixes: #3958 
Proteans can now be lobotomized and brainwashed
Maintaining my shitcode good. Broken thing bad.
Works
:cl:
fix: Proteans can now be brainwashed with surgery
fix: Proteans can now be lobotomized
/:cl:
=> Proteans can now be lobotomized and brainwashed.

config/maps.txt
The people have spoken and they want Catwalk removed from rotation
:cl:
config: Catwalkstation has been removed from voteable map rotation, pending review in three months time
/:cl:
=> Send Catwalkstation to a nice farm upstate for three months

modular_zubbers/code/modules/quirks/neutral_quirks/body_temp.dm
grammar
<details>
</details>
:cl:
spellcheck: abnomal body temperature
/:cl:
=> abnomal > abnormal body temperature

modular_skyrat/modules/customization/modules/clothing/storage/belts.dm, modular_skyrat/modules/modular_items/code/tailoring.dm
- Fixes https://github.com/Bubberstation/Bubberstation/issues/3909
- Removes two redundant lines in the lists
- Makes one line into two lines for better readability
Bugs are bad, and code being readable is good.
Worked on my localhost.
:cl:
fix: fixed crusader belts spawning without the storage pouch
/:cl:
=> Cleans up the crusader belt code a tiny bit and fixes the storage pouch not spawning

modular_skyrat/master_files/code/modules/clothing/under/akula_jobs.dm, modular_skyrat/modules/barricades/code/barricade.dm, modular_skyrat/modules/marines/code/smartgun.dm, modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm, modular_skyrat/modules/mounted_machine_gun/code/mounted_machine_gun.dm, modular_skyrat/modules/stasisrework/code/stasissleeper.dm, modular_skyrat/modules/xenoarch/code/modules/research/xenoarch/xenoarch_machine.dm, modular_zubbers/code/game/objects/structures/beds_chairs/sofa.dm, modular_zubbers/code/game/objects/structures/chalkboard.dm, modular_zubbers/code/game/objects/structures/lewd_portals.dm, modular_zubbers/code/modules/antagonists/bloodsucker/structures/crypt.dm, modular_zubbers/code/modules/nanites/machines/nanite_cloud_controller.dm, modular_zubbers/code/modules/nanites/machines/nanite_program_hub.dm, modular_zubbers/code/modules/nanites/machines/nanite_programmer.dm, modular_zubbers/modules/primitive_cooking/code/cauldron.dm
Make sure our `attack_hand_secondary` overrides are calling parents and respecting cancel returns from higher up in the call stack, also make sure the overrides themselves are returning a `SECONDARY_ATTACK_` define
Cleanup and runtime prevention
Naw
No
=> Touch up modular attack_hand_secondary overrides

code/modules/mod/mod_activation.dm
I changed it from clothing to all items you can equip, I am a bad coder thats done like 4 months of Cyber Security in uni pls be gentle this my first pr here. Tested to ensure it didn't break gear that already worked too, it didn't!!
Bug fix good!
https://i.imgur.com/eVWpVMs.png
https://i.imgur.com/s1ta68L.png
:cl:
fix: MODSuits now go over all items like they should!
/:cl:
Closes: #3999
=> Fixes MODSuits Not Allowing Certain Items Over Them Like CatEar Headphones, Flowers, And Other Stuff No Thanks To TG

modular_skyrat/modules/customization/modules/client/augment/organs.dm
🦈👅
lets people bubble
:cl:
add: new tongue option in character creation, aquatic (it's akula)
/:cl:
=> shorg tongue (please speedmerge)

modular_skyrat/master_files/code/datums/components/fullauto.dm
Fixes https://github.com/Bubberstation/Bubberstation/issues/4314
<details>
https://github.com/user-attachments/assets/c1f77f43-eb19-4792-99e6-4b4902d51373
</details>
None required
=> Fix bubble alert runtime on gun safeties

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/skrell.dm, modular_zubbers/code/modules/mob/living/carbon/human/species_types/skrell.dm
This PR introduces Skrell lore onto the species page, covering their history and a description of their traits and notable information about them.
This should make them much easier to write for, and is mostly ready to go for the server. Still out for revision before the PR is merged, but as I understand everything is in order.
New Skrell lore so we don't have to delete the species. This is for you, that one person who started playing Skrell right as I was planning to delete them
Godspeed
<details>
</details>
:cl: ReturnToZender, Okithedoki (lore)
add: New Skrell lore to sink your teeth into! Enjoy :)
/:cl:
=> Skrell lore update

modular_zubbers/code/modules/mob/living/carbon/human/species_types/shadekin.dm
This PR gives Shadekin lore to work with, including guidelines on how to roleplay one and how variations in the species come about.
Thank you to those who participated in the Shadekin lore thread all those months ago for helping me finish this! This would have taken substantially longer without it.
This has yet to be fully approved, so this is just a draft for now. It will be marked as ready for review when I have that.
This gives some generous guidelines for roleplaying Shadekin that should stir the mind.
More description will lead to better characters!
<details>
</details>
:cl: ReturnToZender, gr33d (lore)
add: Shadekin now have some lore for you to sink your teeth into!
/:cl:
=> Updates Shadekin lore

modular_skyrat/modules/morenarcotics/code/thc.dm
Does as the title says.
Fixes https://github.com/Bubberstation/Bubberstation/issues/4386
It worked fully on my end.
:cl:
fix: fixed dried cannabis not being removed from grinders after being ground
/:cl:
=> Fixes dried weed not being deleted after being ground

modular_zubbers/code/modules/emotes/emotes.dm
Reuses the "leaplush" sound for an emote. Done upon popular request
https://github.com/user-attachments/assets/08a9d13a-fa82-4bae-bc8b-8de2211f8f65
:cl:
add: Added new *mah emote
/:cl:
=> Deer Emote Sound

tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/bubbers/species_features.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/skyrat/species_features.tsx
Explains more clearly what each text box is meant to hold, which should make them more accessible to new players just starting out.
Fully tested, it works!
<details>
</details>
add: The descriptions of the various flavor text tooltips have been made a little more helpful.
/:cl:
=> Updates flavor text tooltips to be a little more helpful

modular_skyrat/modules/customization/modules/language/skrell.dm
remove definitely and potentially regex-damaging syllables from skrelluq
traitors becoming mute because the codeword picker got a * is not fun
I'm not testing a rare as fuck bug
<details>
</details>
:cl:
fix: Remove ! and * syllables from the skrelluq language as it's used for random names and can potentially break as it's used for regex
/:cl:
=> remove definitely and potentially regex-damaging syllables from skrelluq

tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/SpeciesPage.tsx
This PR removes the description section title at the top of every species description, because the name of the species indicates that the description will be underneath
This makes more description fit into the space on the UI, and removes an extra unnecessary element.
before
after
del: More space in descriptions underneath a species on the species page
/:cl:
=> Removes the description title from the section on speciespage.tsx

modular_skyrat/modules/better_vox/code/vox_species.dm, modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/vox.dm
This PR updates the existing Vox lore on the server, making it clean and accessible.
Currently undergoing review, so drafted for now. This PR will be marked as ready when it's read over and approved.
Updated Vox lore will be more accessible and hopefully lead to more people playing the species.
:cl: ReturnToZender (code), Hoygn (lore)
add: New Vox lore has been made, cleaning up the old and bringing it in-line with our other species descriptions.
/:cl:
=> Updates Vox lore

_maps/shuttles/skyrat/pirate_nri_raider.dmm, modular_skyrat/modules/encounters/code/nri_raiders.dm, modular_skyrat/modules/novaya_ert/code/ert.dm, modular_skyrat/modules/novaya_ert/code/outfit.dm
This PR renames a couple overlooked non-station roles that slipped in the original PR ~6-9 months ago and fixes the fax machine name. Also, adds Teshari to list of available species for the police crew by Halas' request.
Fixes inconsistency and more teshari gaming.
N/A, Limited changes
:cl:
fix: Fixed couple names related to the PSC.
add: Teshari can now interact with the "Police" pirates by joining.
/:cl:
=> Minor PSC/NRI Text Fix + Teshari Inclusiveness

modular_skyrat/modules/dogfashion/code/head.dm
title
things should work
it compiles
:cl:
fix: Dogs are no longer Real_Name when wearing the Yankee.
/:cl:
=> Fixes Ian's Rapper Hat

modular_zubbers/master_files/code/modules/holiday/holiday.dm
Does as the title says.
If people can put up Christmas decorations in November, I can have Halloween for a whole month... Jokes aside, it sets the spooky vibes and doesn't do anything game breaking, let the people have their fun.
One line change.
:cl:
qol: Made Halloween last all month long!
/:cl:
=> Makes Halloween all month long - Spooky!

modular_zubbers/code/modules/status_indicators/status_indicator.dm
fixes https://github.com/Bubberstation/Bubberstation/issues/4718
fixes https://github.com/Bubberstation/Bubberstation/issues/4699
bug fix
<details>
</details>
:cl:
fix: fixed army crawling showing status indicators
/:cl:
=> fix voluntary flooring army crawling indicator

modular_skyrat/modules/player_ranks/code/subsystem/player_ranks.dm, modular_zubbers/code/modules/vetted/vetted.dm
fix vetted command, ozzo broke it in https://github.com/Bubberstation/Bubberstation/commit/b731a16ab39be891db9305a7e85d89754d0d6e95
admins need it apparently
tested this on a local DB
:cl:
admin: vetted command works again
/:cl:
=> fix vetted command

modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
edge case
fixes https://github.com/Bubberstation/Bubberstation/issues/4765
bug fix good....
<details>
</details>
:cl:
fix: ethereal lights are refreshed by the sad
/:cl:
=> fix ethereal lighting being removed from the SAD

modular_skyrat/modules/primitive_catgirls/code/smelling_salts.dm
fixes https://github.com/Bubberstation/Bubberstation/issues/4705
also tweaks the defines
bug fix
<details>
</details>
:cl:
fix: fixed smelling salts revival
/:cl:
=> Fixes smelling salts revival
