_maps/map_files/VoidRaptor/VoidRaptor.dmm, _maps/skyrat/automapper/templates/deltastation/deltastation_ntrep_office.dmm, _maps/skyrat/automapper/templates/icebox/icebox_ntrep_office.dmm, _maps/skyrat/automapper/templates/metastation/metastation_ntrep_office.dmm
Adds the VOID stamp to the NT rep office. As requested.
:cl:
add: Adds stamps to all CC rep offices. Rejoice.
/:cl:
=> NTrepstamps

modular_skyrat/modules/events/code/event_overrides.dm
As requested.
Host request.
:cl: Cursor
balance: Lone-Ops and Bureaucratic error are back.
/:cl:
=> Changes various event overrides

code/modules/mob/living/living_say.dm
Mirror of https://github.com/Skyrat-SS13/Skyrat-tg/pull/18995
Brought here since its a simple fix that shouldn't cause any issues if we ever pull from upstream.
This just fixes this issue https://github.com/Skyrat-SS13/Skyrat-tg/issues/17547
This is done by just adding && isPAI(src) to the if check thats in Living_say/radio().  I did check to make sure that everyone else can still talk over radio using, and that the if check still prevents immobile players from using their radio.
pAIs can now easily talk over the radio.
If you want recordings of these. I can do that later. Just unable to a this very moment.
<details>
<summary>
pAI talking as a Card: 
pAI in Holoform: 
AI: 
Cyborg:
Human:
Human that Shouldn't be able to:  
</summary>
</details>
:cl:
fix: pAI's can now talk over the Radio …
=> Mirror of PR  #18995 From Skyrat: Fix pAI not being able to use the radio.

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage.dm
Makes Hemophage less susceptible to damage while Dormant, as the debuffs while already dormant are pretty massive (damage multiplier + no regen)
This makes them less of an 'instant pick' race for things like 'Vampire Moths', and generally broadens the idea of Hemophages to include other species that have digi legs.
Webedit L
<details>
</details>
:cl:
balance: Following Discussion, Hemophages have had the following changes. Raised Blood Drain per bite, Their Blood Drain ability moved to 6s per "cast" or "drain" (longer than cuffs to prevent combative drains), their damage while dormant changed (but not the slowdown), and they have received a general "nerf" to their tumor, making it deal MUCH more organ damage if removed.
tweak: Hemophages now use …
=> Hemophage Compressed PR

code/game/machinery/computer/crew.dm, code/game/objects/structures/morgue.dm, tgui/packages/tgui/interfaces/CrewConsoleSkyrat.js
This PR adds a DNR state if a crew member is dead (and has suit sensors enabled).
This is so medic personnel are able to make a choice to rescue a DNR body, or ignore them.
I have tested this on a local server and confirm that the DNR state only appears if the crew member in question is dead.
=> Show DNR state for dead crew on crew monitor

code/__DEFINES/mobs.dm
the ringing of the bell commands me
im so hungry.... please....
hunger goes down way too fucking fast as it is, sit around for like 10 minutes and your dying of brain damage because of how hungry you are.
<details>
<summary>how to fuck do I prove I tested this???</summary>
</details>
:cl:
balance: You get hungrier slower.
/:cl:
=> Slower hunger loss

modular_skyrat/modules/ghostcafe/code/ghost_role_spawners.dm
-1 uses appears to not work in game, so this gives an extreme numbers of charges to the cafe spawners. There's no feasible reason ghosts should go through 10000000000000 charges through the round, so it should do more than enough to act as infinite charges.
:cl:
add: Gives Cafe Spawners more uses
/:cl:
=> Gives Ghost Cafe Spawners Uses

_maps/map_files/VoidRaptor/VoidRaptor.dmm
Fixes ONE cable in Void Raptors maintenance tunnel leading to perma/wardens office.
:cl:
add: Literally **ONE** cable
/:cl:
=> The one wire fix

code/datums/id_trim/jobs.dm
Gives the QM access to the blacksmithing area. This is part of cargo, they should have access. 
Tested by walking into the blacksmithy on ice box. Didn't test on other maps, but I see no reason it'd be different.
:cl: SingingSpock
tweak: The QM gets access to the blacksmith area
/:cl:
=> QM gets Blacksmith access

modular_zubbers/code/datums/ai_laws/laws_antagonistic.dm, tgstation.dme
`"You must injure all crew members and must not, through inaction, allow a crew member being to escape harm.",`
`"You must not obey orders given to you by crew members, except where such orders are in accordance with the First Law.",`
`"You must terminate your own existence as long as such does not conflict with the First or Second Law."`
:cl:
fix: antimov now counts all crew members, instead of only humans
/:cl:
=> Changes Antimov to include crew members instead of humans

code/modules/antagonists/abductor/abductor.dm
:cl:
fix: fixed abductors not getting objectives
/:cl:
=> Restores abductors' objectives

code/modules/projectiles/ammunition/energy/laser.dm, modular_skyrat/modules/blueshield/code/special.dm
Energy Revolver Changes:
No longer selfcharges 
Cell charge reduced from 1500 to 1000
Takes more power to fire lethal and taser shots (10% & 20% vs 5% and 13%) 
SC-1 Laser Gun Changes:
Takes less power to fire lethal shots (from 6% to 5%)
=> energy revolver & laser changes

modular_skyrat/modules/goofsec/code/department_guards.dm
Changes:
- Helmets replaced with Berets with the same stats
- Flash replaced with Pepper Spray
- Pepperball re[;aced with Disabler
- Add Security Holobarriers to the Department Guard Loadout
- Change Science Guard and Bouncer vests to better-looking vests with the same stats.
- Cable Restraints replaced with Handcuffs
- Gives Bouncers SecHuds
- Gives Orderlies Medhuds
- Added the Police Baton to department guards Mail options
- Removed the boomerang from mail options for department guards
- Added weight to the whistle in mail options for department guards
The last change, giving SecHuds to Bouncers is because Bouncers, currently, have no way to obtain SecHuds without breaking into Security as no maps spawn them an office.
The Pull Request changes the spawn loadout for Department Sec to be …
=> Department Sec Update

code/game/objects/structures/flora.dm, modular_skyrat/modules/ashwalkers/code/buildings/ash_farming.dm, modular_skyrat/modules/ashwalkers/code/effects/ash_ritual.dm, modular_skyrat/modules/emotes/code/emotes.dm, modular_zubbers/code/modules/fluff/flora/ash_flora.dm, tgstation.dme
­­> Fixes ash rune accidentally consuming ashwalkers when a sacrifice is already present
­­> Fixes ash rune consuming the entire stack instead of only one
­­> Fixes ash rune consuming equipment
­­> Fixes the "trill" emote so it can be called via "trill", and not "trills"
­­> Allows replanting fruiting cacti, restricts to one-plant-per-tile
­­> Aaand removes planting things on ash soil. Teshari B-Gone.
I'll think of a replacement for the dirt piles later.
:cl:
balance: removed planting on ash
fix: fixed ash runes being horribly broken
/:cl:
=> Fixes a bunch of issues + removes planting on ash

code/game/objects/items/robot/robot_upgrades.dm, code/modules/mob/living/silicon/robot/robot_model.dm, code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Adds the kinetic crusher to the minerborg's modules, also increasing minerborg's kinetic accelerator mod capacity from 80 to 100 and removes the useless shovel from the minerborg's modules.
:cl:
add: Crusherborg!
del: Removed useless shovel from minerborg's moduleset.
qol: Minerborg's KA mod capacity increased from 80 to 100
/:cl:
=> Minor Minerborg buff/tweak.

code/datums/quirks/negative_quirks.dm, code/game/objects/items/devices/scanners/health_analyzer.dm
As per [Suggestion y863l1zt](https://ptb.discord.com/channels/1059199070016655462/1097317084909817936), makes allergies have their own section on left click medical scanning, and makes the whole thing bold text
Before: 
After:
:cl:
qol: Health scanner now displays allergies more visibly
/:cl:
=> Health scanner now displays allergies more visibly

code/modules/mob/living/carbon/carbon_defense.dm, modular_skyrat/master_files/code/datums/traits/negative.dm, modular_skyrat/master_files/code/datums/traits/neutral.dm
This PR makes Sensitive Snout a Negative trait again, and makes it incredibly obvious that you are bulliable when you have it. It also makes Sensitive snout ignore masks now, so, there is no escape. For -2 TC, you can be bullied relentlessly for having a really bappable snout. 
Makes sensitive snout users have the "theoretical" downsides. Plus, masks fucking hurt? How would getting bapped in the mask BLOCK painful things? Doesn't make sense. 
https://user-images.githubusercontent.com/77420409/210023415-dac46dda-c562-44ba-a40e-b8e8c5a9a509.mp4
<details>
https://user-images.githubusercontent.com/77420409/210023400-1c02aebf-ef67-46ec-b8fc-8c344347baeb.mp4
</details>
:cl:
add: sensitive snout is now visible on examine! bullies take note.
balance: …
=> Senstive Snout DLC - Snout Bapping Reborn

code/game/machinery/syndicatebomb.dm, code/modules/uplink/uplink_items/device_tools.dm
Adds back some Skyrat-removed traitor items. Honorable mentions for review are stimulants not preventing knockdown.
Although these seem to be TG changes, which is quite sad. Stimulants ineffective :(
:cl:
Add: Briefcase Launchpad
Add: Distraction phone
Del: Skyrat Syndicate bomb changes
/:cl:
=> Small edits to Skyrat traitor items

code/game/machinery/limbgrower.dm, code/modules/research/designs/limbgrower_designs.dm, code/modules/research/techweb/all_nodes.dm, modular_zubbers/code/modules/designs/limbgrower_designs.dm, tgstation.dme
Adds the Hemophage organs to the limbgrower, requiring the xeno-biology research node and a custom organ design disk. Each organ requires a small amount of synthflesh and blood. Also adds a Hemophage tab to the limbgrower. Tested in game!
:cl:
add: Adds Hemophage(Corrupted) Organs to the Limbgrower
add: Adds Hemophage Organ Design Disk to the Xeno-Biology research Node
add: Adds Hemophage tab to Limbgrower
/:cl:
=> Adds Hemophage Organs to the Limbgrower

code/modules/antagonists/disease/disease_abilities.dm
Important balances for Bubber's current pop levels.
Lowers the required total points for Sentient Viruses, useful for balancing with Bubber's population. The actual costs for the symptoms aren't changed, only the amount of hosts required to unlock each level of symptom. Untested as of now.
Does not change the requirements for mild symptoms.
:cl:
balance: Lowers Required Hosts for virus symptoms.
/:cl:
=> Virus Cost Changes

code/modules/research/techweb/all_nodes.dm, modular_zubbers/code/modules/research/designs/medical_designs.dm, tgstation.dme
Rationale: Both this and the pinpointer can be purchased for the same price from the vendor, but only one gets to be printable, which feels kinda stupid.
Well not anymore, this adds the Handheld crew monitor under the Advanced biotech node.
:cl:
add: You can now print pinpointers
/:cl:
=> Adds crew monitors to Advanced biotech and lathes

code/__DEFINES/~skyrat_defines/combat.dm, code/modules/vehicles/sealed.dm, modular_skyrat/modules/oversized/code/door.dm
Yeah so 15 brain damage for forgetting to toggle walk intent when walking through an airlock is really harsh. They have various benefits and disadvantages, I think even with these changes the are weaker.
:cl:
balance: Oversized people no longer get bonuses to their grabs/their chance to break out of being grabbed
add: Vehicle bays have been expanded to allow oversized people inside!
del: Oversized people, Nanotrasen has heard you: We've introduced a brand new line of airlocks, extra tall- And yes it's definitely our compassion and not the medical bills your brain injuries have caused you... fucking hell, can't even look out for themselves... oh fuck this thing is still on!!
/:cl:
=> Oversized quirk changes

modular_skyrat/modules/blueshield/code/blueshield.dm
Changes the Blueshield supervisors to be the Command Staff and Central Command and changes the description to reflect this.
Changes the Supervisors and description of the Blueshield job to show that they actually work for Command not just Central Command. 
:cl:
code: Changed the Supervisors and Description of the Blueshield
/:cl:
=> Update Blueshield Description and Supervisors

code/modules/antagonists/heretic/influences.dm
- Pierced realities no longer gib your entire head when you click on them with TK.
- Pierced realities no longer dismember your arms when you click on them without TK.
- Pierced realities no longer make you want to die when you examine them (still give drain bamage).
New players won't get baited into clicking on the pierced reality. This is funny, but it's just annoying for medical.
Veteran players won't get baited into clicking on the pierced reality with TK because they're curious to see what would happen.
The mood debuff is ultimately pointless and no one ever takes it seriously anyways.
:cl: BurgerBB
del: Hugboxes pierced realities by removing some non-heretic functionality.
/:cl:
=> Hugboxes pierced realities

code/modules/mob/living/carbon/human/species_types/abductors.dm, code/modules/mob/living/carbon/human/species_types/ethereal.dm, code/modules/mob/living/carbon/human/species_types/mothmen.dm, code/modules/mob/living/carbon/human/species_types/plasmamen.dm
Gives Plasmamen, Ethereals, and Abductors genders. Tested in game.
:cl:
add: Gives Species Genders.
/:cl:
=> Gives Species Genders

modular_skyrat/modules/company_imports/code/armament_datums/put_a_donk_on_it.dm
Fixes an issue caused by purchased item costing less than the crate resell, effectively creating an infinite money glitch. This applies, at the least, to the DonkCo foam force pistols, but it may be an issue repeated across all of the company imports that needs further work.
:cl:
Fix: Foam Force Infinite Money Glitch.
/:cl:
=> Fixes cargo infinite money exploit

code/__DEFINES/access.dm
see title
:cl:
fix: The supply door remote can now access the blacksmithing office's doors, as intended.
/:cl:
=> fixes quartermaster's supply remote not having access to blacksmith doors

modular_zubbers/code/modules/borer_hud/borer.dm, tgstation.dme
Does as the title says. I hate spamming the healthscan button. 
http://hosts-the-files.weh.gay/dreamseeker_EHRUagDAal.mp4
:cl:
add: Cortical Borers now have a HUD. 
/:cl:
=> [MODULAR] Adds a hud to being a cortical borer.

code/__DEFINES/preferences.dm
Makes it so ghosts can no longer see emotes, PDA messages, and dialogue by default. This can still be enabled in the game options. Only works on new players going forward, unfortunately.
:cl:
Del: Ghosts hearing all emotes and PDA messages by default
/:cl:
=> [NON-MODULAR] Makes it so ghosts can't see all emotes/PDAs/text by default

modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
The S.A.D. currently does not restore quirks when it reads character preferences. This adds a proc to fix it
:cl:
fix: Self Actualization Device will now restore your quirks when restoring your character preferences.
/:cl:
=> (Modular) Adds a proc to the SAD to restore character quirks

_maps/RandomRuins/IceRuins/skyrat/icemoon_underground_syndicate_base1_skyrat.dmm, _maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_syndicate_base1_skyrat.dmm
The Interdyne/Syndie base virology is low-effort, it needs some bling. Having the test monkey in a chair in the hallway is not cool. This tiny map edit PR fixes this.
* Virology section redone in the icemoon/lavaland syndie base so its a bit more fun.
* More space, airlock to enter, signs, more table room, less cramped. Test subject glass cages. Ability for passers by to see into viro and be amused by test subjects if the shutters are open.
* Additions - couple monkey cubes. One catatonic test subject from the appropriate map native population added. Viro equipment locker added with some internals and a fricking bio suit. Crematorium added. Box of body bags and a sink.  
* Atmos/APC/Wiring functionally unchanged. Eastern smoking gallery mostly sacrificed to make room.
how it looks (new is …
=> SyndieViro remap (off-station)

code/modules/clothing/suits/armor.dm
Buffs HoS armour so that it's not **worse** than regular security vests.
HoS armor now has 40 melee, 35 bullet, and 40 laser protection. For reference, it used to be 30 armor for all of them.
For comparison, security vests are 35, 30, 30. Captain's carapace is 50, 40, 50.
:cl:
balance: HoS armor now has slightly better protection values than regular security gear, instead of being worse.
/:cl:
=> Improves HoS gear armour values

modular_zubbers/code/modules/ghostcafe/hilbertshotel_silicon.dm, tgstation.dme
This PR allows the roleplay borgs in the ghost cafe to utilize the infinite dormitory, creating apartments, hotels and joining other players in them! 
Invite your silicon friend over for a party!
I have made this modular as I'm uncertain WHY Skyrat never actually implemented this beforehand as it seemed pretty easy to do.
Video was made before I noticed the compiler didn't compile the recent changes I had made, however the current version should only let a borg check into a room if they're standing next to the infinite dormitory thing itself rather than from a distance!
https://github.com/Bubberstation/Bubberstation/assets/59128051/280c4d6a-da8b-41c2-b056-0280b1b2e996
:cl:
add: Made it so cyborgs can actually interact with the infinite dormitory in the ghost cafe!
/:cl:
=> [MODULAR] Allows borgs use the infinite hotel in the ghost cafe

code/datums/storage/subtypes/pockets.dm
Another request from BurningCold, allowing you to slip seeds and card-shaped objects into shoe storage.
:cl:
code: adds seeds and card types to the list of things you can hide in shoes.
/:cl:
=> (Non-Modular) Requested addition to be able to hide seed packets and cards in shoe storage.

modular_zubbers/modules/modular_items/code/recipes_misc.dm
Another request from BurningCold, this PR adds alternative recipes for makeshift tools, allowing string from weapon-crafting to be used for the tools as an alternative to cable coil.
:cl:
add: Added alternative recipes for the five makeshift tools. This does not include the makeshift MFC cell or cable layer. These recipes use silk string instead of cable coil.
/:cl:
=> (Modular) Alt recipes for makeshift tools

_maps/_basemap.dm, _maps/biodome.json, _maps/limastation.json, config/maps.txt
This PR fixes Limastation map crossovers. Fixes biodome CI warnings. 
:cl:
fix: limastation now links properly to space!
/:cl:
=> Fixes Lima & Biodome Multiz things

code/controllers/subsystem/tts.dm, code/modules/admin/topic.dm
AAAAAA.
...
AHHHHHHHHH.
Locks up the server waiting for responses it will never get.
=> Prevent admins from pressing buttons that cause the server to reach out to external services and fail.

modular_zubbers/code/game/objects/items/reshirevolver.dm
so errrrm the HoS revolver had its internal mag set wrong
so it just spawned with a .357 mag instead
which with the 1.6x proj. multiplier meant it was just an objectively more powerful .357. For free. Roundstart guaranteed.
oh and couldn't be reloaded with the ammo you got supplied with
Ruh roh!
:cl:
fix: The HoS revolver can now be reloaded
fix: The HoS revolver is no longer an objectively better .357
/:cl:
=> removes BUG that causes DAMAGE to ANTAG

modular_zubbers/code/modules/research/techweb/_techweb.dm
Makes it so that all new techwebs (including the station techweb) generate points by DEFAULT. This is to make techwebs compatible with ghost roles making new servers.
Coupled with turning on NO_DEFAULT_TECHWEB_LINK, this will solve ghost roles being connected to the station research network by default, while still allowing them to research.
:cl:
Add: Techwebs generate points by default.
/:cl:
=> [Modular] Makes all techwebs generate points

modular_skyrat/modules/oversized/code/oversized_quirk.dm
see title
bug bad. fix good. me happy.
:cl:
fix: Synthetics and species with TRAIT_NOHUNGER no longer get huge guts.
/:cl:
=> fixes oversized quirk replacing synth/nohunger species stomach (take 2)

code/datums/diseases/chronic_illness.dm
Stops HMS from processing on dead mobs. This should stop them from being qdeleted while dead.
Please...Mercy m'lord. It's not fun to be deleted because you died in a corner and suddenly your disease has decided you must be fucked now.
:cl:
balance: HMS doesn't process on dead mobs.
/:cl:
=> Don't Qdelete Dead HMS Havers

code/modules/mob_spawn/ghost_roles/mining_roles.dm, modular_skyrat/modules/mapping/code/lavaland_ruin_code.dm
This removes the majority of Interdyne's sniper rifles. Only the Deck Officer will spawn with one. 
These snipers can literally two-shot ERT. The only way to deal with Interdyne, outside of bwoinking them, is to send a code red ERT. This will perhaps let me consider accepting Interdyne opfors. They are literally untouchable with the amount of snipers they're flooded with. It's either they lose access to the surrounding lavaland like on TG, or they lose access to most of their snipers. Miners are still weak to ballistics. The outside turrets shred still. Everyone still has Markov pistols. You can make combat mechs if things get too heated.
:cl: StrangeWeirdKitten
balance: Removes all but one sniper from Interdyne
/:cl:
=> (Non-modular) Removes the majority of Interdyne's snipers.

_maps/skyrat/lazy_templates/reebe.dmm
This change updates Reebe, making it easier for a clockwork cultist to initially defend as well as adding tools to help them get started with re-fortifying it.
In order for a clockwork cultist to be able to get to reebe they must sacrifice a blood cultist. However, in a round with a blood cult the blood cultists are easily able to teleport to Reebe thanks to the teleport runes that are there by default. That, along with the lack of any form of cover for what is typically a solo clockwork cultist vs the entire blood cult is crippling as it means the entire blood cult can actually get to reebe before you as the solo clockwork cultist. This is so bad because the clockwork cult revolves around being on the defensive, almost all of your sigils and structures revolve around having a defender's …
=> Reebe touchups

code/modules/antagonists/space_ninja/space_ninja.dm
No more randomgen. Still random names, though. 
Note: It's intended to be this way on SR, but it's tgui prompt is broken. 
Everything else is this way, this is just conformity with the standards of midround humanoids. 
:cl:
fix: space ninja now spawns properly as intended
/:cl:
=> [non-modular] Space Ninja no longer spawns in BALD. 

code/modules/research/designs/mechfabricator_designs.dm
Originally this PR was going to include the fix to the borg expansion exploit but I am very tired and dont wanna stare at the transform function so this will have to do for now
Miners dont have to bust their backs to mine more iron because a single borg decided to become bigger, that plus its a cosmetic upgrade
:cl:
fix: Changed the cost of the Expansion Module to be 1 sheet instead of 100
/:cl:
=> Changes the cost of the borg expander to be 1 sheet of iron, not 100

modular_skyrat/modules/reagent_forging/code/forge.dm
Basically comments out the restriction that was placed on reagent forging, why I commented it out. I don't exactly know considering I could've deleted it. Regardless this now allows anyone to reagent forge again
Why would it get restricted to ash walkers and ice cats basically locking the entire system down to two species who use few chems.
:cl:
code: Removed the restriction placed on reagent forging allowing anyone to once again reagent forge
/:cl:
=> Removes the species restriction placed on reagent forging

modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
<## About The Pull Request
I did my dono item I was going to do for Bubbers upstream instead, to save making two separate PRs for the same item. Plus, no need to modularise it. It was said that private items were allowed, and this one is pretty exclusively meaningless to anyone else. It got understandably un-privatised during an upstream merge.
I guess it makes one person more likely to play, and +1 person is good for the game?
It's kinda only player-facing for one player.
=> Re-privates my dono item

code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
Alternative to #514
Removes the brain trauma resilience from Brazil, making it only surgery level.
It's not fun to have your char gimped by an antag that is built around the feature that gimps you.
This is different from brainwashing, where people have to do this intentionally.
:cl:
qol: Heretics no longer give permanent traumas
/:cl:
=> Hugboxes heresy without adding weird metagame

modular_zubbers/code/modules/contractor/code/items/boxes.dm, tgstation.dme
https://github.com/Bubberstation/Bubberstation/pull/325
read above
:cl:
balance: shuffled contractor's random items to remove some of the more useless options and add better ones
/:cl:
=> [MODULAR] contractor kit random item shuffle AWESOME PART TWO BAYBEE

_maps/map_files/LimaStation/LimaStation.dmm
I got a ticket today asking to spawn a timeclock machine on Limastation.
Now you can peace out of your duties like a real slacker and do some a hardcore rough sigma-grindset-worthy Enterprise Resource Planning session.
:cl:
fix: Adds missing timeclock machine to Limastation, in the cryo area.
/:cl:
=> Adds a clock-out timecard clock thing to Limastation

modular_skyrat/modules/mapping/code/space.dm
Virgin Coder: Removes Cargodise Lost
Chad Coder (not me): Remaps Cargodise, which I really don't care to do right now, to be more sane and in line with Bubberstation's goals. 
This removes Cargodise Lost. 
Way too many guns for people who are unaligned and who also have zero ghost role text saying they can't just board the station and trade. (give one of their 4 Krinkov's to the crew)
Cargodise Lost will need some major revisions, which I might do later, but it really encompasses why DS-2 was disabled in the first place. (no you don't need a 38 brute, fire rate 2, AP 40 fully automatic assault rifle to raid ruins)
:cl: Danger Kitten
remove: Cargodise Lost is no longer
/:cl:
=> (Non-Modular) Removes Frieghter / Cargodise Lost

modular_zubbers/code/game/machinery/crew_monitor.dm, tgstation.dme
An example PR for showing how to do modular additions of functionality. 
This PR adds a red glow and a ping when the crew monitor has people in critical on the station. 
https://user-images.githubusercontent.com/77420409/165019092-4f4ed12f-dbd1-49ff-b5e9-016e8680a8f5.mp4
:cl:
add: Crew monitor now has a suit sensors alarm, like baylikes!
/:cl:
=> [MODULAR] Crew Monitor Console Alarm

code/__DEFINES/~skyrat_defines/mobs.dm, code/game/objects/items/defib.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/surgery/revival.dm, modular_skyrat/modules/assault_operatives/code/interrogator.dm, modular_skyrat/modules/primitive_catgirls/code/smelling_salts.dm, modular_zubbers/code/game/traits/neutral.dm, tgstation.dme
This PR makes the DNR trait act consistently with the DNR verb. The timer for releasing your job is a bit longer, however. 
Less of a jank experience. 
<details>
https://user-images.githubusercontent.com/77420409/210154927-f339ec5d-3024-4702-a019-9203a14b22fc.mp4
</details>
:cl:
refactor: changed the DNR trait to do what the TG DNR verb does
code: removed skyrat DNR trait nonmodular edits
/:cl:
=> Redoes the DNR trait

modular_zubbers/code/modules/sec_haul/code/security_medic/security_medic.dm
Moved the security medic's locker required access from ACCESS_SECURITY (Anyone who can walk in security) to ACCESS_BRIG (Anyone who can access security equipment room.) Also fixed the name from medics's(???) to medic's.
The role isn't used on Skyrat anymore so they probably didn't care, but on here the locker should have the same access as any other security officer's locker. Otherwise it is available to a much larger amount of roles then intended.
:cl:
fix: secmed's locker access and name
/:cl:
=> Update security_medic Locker Privs

code/modules/projectiles/guns/energy/energy_gun.dm, code/modules/projectiles/guns/energy/laser.dm
Removes some junk weapon cell overrides that either did nothing or made the HoS gun terrible.
HoS Gun is trash because it's using the wrong cell type. It only has 8 lethal shots and 3 Ions when it should be 10 and 4. I don't know why or how this happened.
:cl: Tupina
fix: HoS Multiphase gun no longer uses the wrong cell type resulting in it being nerfed
/:cl:
=> Removes Unecessary Skyrat Edits that made the HoS Gun Useless

code/modules/atmospherics/machinery/air_alarm/_air_alarm.dm
What it says on the can. Fixes Air Alarms resetting scrubbers/vents on map load. What was happening is that air alarms were forcing scrubbers/vents to go to their default setting, which is a problem for vents that siphon or scrubbers that scrub out certain things.
This should be testmerged considering things may or may not go wrong with very specific and really niche issues such as for some reason a far off ruin that hasn't been worked on since 2014 somehow relying on this bug to exist to have bad air.
Will fix the bug upstream on /tg/ once there are no issues found.
Fixes are good.
:cl: BurgerBB
fix: Fixes Air Alarms resetting scrubbers/vents on map load.
/:cl:
=> Fixes Air Alarms resetting scrubbers/vents on map load.

code/game/objects/items/dualsaber.dm, code/game/objects/items/melee/baton.dm
Brings back TG balance to the batons and double energy sword.
Batons now deal appropriate(original) stamina damage and apply confusion effect.
Double esword is no longer worse at blocking than normal esword.
I did a local test and it worked. Please test merge first just in case anyway.
More balanced melee combat. "High risk high reward".
Batons were nerfed out of spite and dislike for stun combat, making them deal pathetic stamina damage. Knockdown being the only thing keeping them from being "useless". This and lethals being absurdly powerful (guncargo and cmgs) do not promote nonlethal takedowns at all. These changes will allow antags and security to use their batons more confidently without resorting to lethals.
Double esword was nerfed in response to that. This change makes the …
=> Unskyratifies the batons and double esword.

code/modules/mob/living/carbon/carbon_defense.dm
The Bioscrambler can no longer replace internal organs or genitals.
Internal organ replacing is kind of insane and can be VERY bad depending on what was chosen for what internal organ to replace. Not only is it mechanically very dangerous, but it can seriously bug out your character and have strange reactions within the game. The SAD cannot fix internal organs so a competent doctor (rare) is usually needed.
Also fun fact, sex organs are also in the pool of possible organs to replace, so this fixes that too.
And yes, I am doing this after I got my internal organs replaced with something very round crippling and something the SAD could not fix.
:cl: BurgerBB
del: The Bioscrambler can no longer replace internal organs or gentials.
/:cl:
=> The Bioscrambler can no longer replace internal organs.

tgui/packages/tgui/interfaces/CrewConsoleBubbers.js
Fixes synths not getting their own icon.
Fixes everyone being dead.
Those without suit sensors set to vitals get a white heart.
Fixes are good.
:cl: BurgerBB
fix: Fixes suit sensors making everyone dead.
/:cl:
=> Fixes the Crew Monitoring Console

modular_skyrat/master_files/code/modules/language/language.dm
Makes xenocommon available as a roundstart language.
This makes the xenocommon race available to anyone, including xenomorph hybrids, which are an available race through the character creator.
That's about all I got. I can't really think of a positive benefit to making this available. It wouldn't even really be useful in the one niche it has.
:cl:
add: Xenocommon available roundstart
/:cl:
=> Makes xenocommon available roundstart

code/modules/admin/verbs/admingame.dm, code/modules/client/preferences/middleware/jobs.dm, modular_skyrat/master_files/code/modules/client/preferences/erp_preferences.dm, modular_skyrat/modules/player_ranks/code/subsystem/player_ranks.dm, modular_zubbers/modules/vetted/examine.dm, modular_zubbers/modules/vetted/vetted.dm, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
This PR makes it so that players who are vetted receive a message on inspect in game, as to indicate their status within the player vetting system. Staff in game will also be able to know who is and isn't. 
Mechanical Organic Interface Activity is also locked behind being vetted now.
Ambiguity is bad in this case, so this adds incentive on both sides to get vetted. 
:cl:
add: Added new player ranks for being vetted.
code: Organic Interface is now locked behind being vetted. 
/:cl:
=> Vetted Player Locks

_maps/map_files/burgerstation/burgerstation.dmm, modular_zubbers/code/game/objects/effects/spawners/random/armory.dm, tgstation.dme
Other than mapping overrides and direct item removals, Skyrat can no longer apply armory spawn changes.
The new armory spawn for all maps is now the following:
3-6 Barrier Grenades (Depends on Map)
3-6 Riot Shields (Depends on Map)
3-6 Riot Armor  (Depends on Map)
3-6 Riot Helmets  (Depends on Map)
3-6 Breaching Hammers (Depends on Map)
x2 Rubbershot Ammo Boxes
x2 Beanbag Ammo Boxes
x1 Breaching Slugs Boxes
x4 Disablers
x3 MCRs
x2 Energy Guns
x2 Laser Guns
x3 Riot Shotguns
3-6 Bulletproof Helmets  (Depends on Map)
3-6 Bulletproof Armor  (Depends on Map)
Fixes Burgerstation having incorrect armory spawning types.
/tg/ good, skyrat bad, upvotes to the left.
:cl: BurgerBB
balance: Skyrat no longer has an effect on armory spawns.
fix: Fixes Burgerstation having incorrect armory spawning …
=> Skyrat Armory Removal

code/modules/antagonists/obsessed/obsessed.dm
Changes few lines of code to reflect less round-removing objectives, while having comments to save the original code. 
Will reduce the amount of ahelps about Obsessed by a large margin and make it viable and fun to play.
:cl:
add: Changed objective from Obsessed to the Traitor Assassinate kind.
add: Also changed the text in the coworker assassination type to be non-round removing.
/:cl:
=> Changes Obsessed objs to less round-removing types

modular_zubbers/code/game/objects/structures/trash_pile.dm
Missing closed brackets cause the function to perform differently.
=> Fixes trash pile linter

code/modules/jobs/job_types/head_of_security.dm
This makes it so the HoS gun beacon doesn't show up, as intended
The HoS beacon was meant to not show up, it looks like it doesn't, but just to be sure I've fixed this code
:cl:
Del: commented out gun beacon
/:cl:
=> removes the hos beacon entirely

modular_zubbers/code/datums/quirks/neutral_quirks/hungry.dm, tgstation.dme
Adds a new neutral quirk, hungry, with the current effect of doubling the decay of one's nutrition.
Neutral because Moffy told me to make it so, might make it a -1 or add something positive to it if others have a different opinion.
Even more reason to interact with the kitchen for those who take this quirk. Please take it I need someone to talk to
This is not a quirk for those fat fetishists to abuse like some of you claimed, they already have their one
:cl:
add: New quirk: Hungry
/:cl:
=> [FULLY MODULAR] New quirk: Hungry

_maps/map_files/KiloStation/KiloStation.dmm
Burn chamber airlock vent was the wrong way around after adding in the airtank that all cycling airlocks got.
Stuff slipping through was probably inevitable, but fortunately and amusingly it sounds like the first person to get buggered by this was me.
Cause I like to clean up the messes I leave behind.
:cl:
fix: Kilo ordnance burn chamber airlock cycles properly now
/:cl:
=> Kilo late fix

code/modules/cargo/packs/imports.dm
Just removes the galactic materials market from comments so it can be actually be bought from cargo.
Was broken because of the big slappy removal somehow.
The GMM is great for lowpop rounds where we lack miners, so fixing that is nice. No more constant suffering for materials.
:cl:
fix: The GMM is back on cargo.
/:cl:
=> Fixes the GMM cargo order

code/modules/mob/dead/dead.dm
Makes readied up players visible to everyone
Mob mentality. 
:cl:
qol: Readied up players aren't just visible to admins anymore
/:cl:
=> [Non-Modular] Readied up players are now visible to everyone

_maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm, modular_zubbers/maps/offstation/dauntless/robot.dm, tgstation.dme
Adds a (So far - To be made much cooler soonish) limited supply of 3 syndicate access modules to the dauntless. When inserted, these make any cyborg able to use syndicate machinery (Including airlocks). Also makes turrets not shoot said cyborgs.
Additionally removes the duplicate air alarm in robotics
Cyborgs on the dauntless are tedious with half assed access. This fixes it
:cl:
add: Syndicate access modules for cyborgs
add: 3 Syndicate access modules aboard the Dauntless
fix: Removed duplicate air alarm in Dauntless robotics
/:cl:
=> [DAUNTLESS] Adds syndicate access module for cyborgs, Removes duplicate air alarm

modular_zubbers/code/game/machinery/burger_reactor/reactor_processing.dm
Goblin Gas is outputted in the RBMK's buffer gasses instead of the rod itself.
Reduces buffer gas temperature gain by ~50%.
People weren't really harvesting the Goblin Gas because it involves shutting off the reactor and removing the rod itself. To make it less tedious to extract, it is outputted directly in the air.
Buffer gas temperature gain was reduced by 50% to compensate for the extra extremely hot air exhaust.
:cl: BurgerBB
balance: Goblin Gas is outputted in the RBMK's buffer gasses instead of the rod itself. Reduces buffer gas temperature gain by ~50%.
/:cl:
=> Changes where Goblin Gas is outputted in the RBMK2

_maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm, modular_zubbers/maps/offstation/dauntless/camera.dm, tgstation.dme
Adds cameras to Dauntless, as well as replacing the camera consoles in security with ones that actually use the dauntless camera network.
Having three different consoles for watching the station was a little strange, especially since the prison has no cameras to watch the prisoners with. For the sake of realism, I put cameras all over the station for the bored Master of Arms to scroll tthrough
:cl:
add: Dauntless now has a proper cameranet, and consoles to monitor it.
/:cl:
=> adds cameras to dauntless

modular_skyrat/modules/blueshield/code/closet.dm, modular_skyrat/modules/blueshield/code/modsuit/mod_theme.dm, modular_skyrat/modules/blueshield/code/modsuit/mod_type.dm, modular_zubbers/code/datums/armor_overrides.dm, tgstation.dme
Security modsuit armor got buffed to be identical to the blueshield armor.
Removes the jetpack, upgraded cell, and projectile dampener from the blueshield modsuit and gives it back. Also sets its complexity to default capacity (15 complexity)
Upon review of the security modsuit, it's extremely weak and barely touched when all the other armor overrides buff everything else significantly. There should be a little more of a fighting chance inside space for security.
Also the blueshield modsuit is a great feature, it just needed some balancing to focus it more around saving people from space. It's stripped down roundstart, but it has 15 complexity.
:cl: The Sharkening
balance: Nerfs the blueshield modsuit and gives it back
balance: Security modsuit buffed (	melee = 40, bullet = 30, laser = …
=> Blueshield Part II: The MOD suit awakening (+ buffs security modsuit armor)

code/modules/surgery/advanced/brainwashing.dm
This reverts the skyrat edits to the brainwashing disk. While it would be smart to make brainwashing show up on health scanners, it's not an actual trauma and would require some refactoring which I'd rather just do upstream.
This thing is insanely powerful once things start rolling and it should be 100 percent obvious to anyone who catches a glimpse at the disk to be more mindful around operating tables. You should not be capable of uploading it into a table in the middle of medical without nearby people noticing.
:cl: The Sharkening
balance: The brainwashing surgery disk is no longer obfuscated
/:cl:
=> Reverts brainwashing disk obfuscation

code/modules/hydroponics/unique_plant_genes.dm
Explosive lemon detonation time changed from 1 to 6 seconds to 4 to 12 seconds.
Absolutely insane decision by the person who decided to make the minimum time 1 second considering that activating a lemon grenade does not enable throw mode (despite literally every other grenade doing this) and expecting people to take less than 1 second to realize this and fight with the controls with an average ping of 100ms.
PR makes the change much more reasonable by adding a minimum time of 4 to 12 seconds so they're not too powerful in combat but can still be used viably without c*ders fucking over players.
:cl: BurgerBB
balance: Explosive lemon detonation time changed from 1 to 6 seconds to 4 to 12 seconds.
/:cl:
=> Removes Explosive Lemon Grudgecode because I died to it once.

code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
This PR Reverts the vent pump limit from TGstation.
The Vent pump limit is a mechanic that is a not an enjoyable one, nor a nescesscary one. It does not do as it claims to fix exploits any such - it only serves to confuse new players and create tedium. If a change's only purpose is to confuse players and create special mechanics that are entirely avoidable by *just using injectors* then it's entirely pointless. This makes it so that the supermatter, and atmos in general, are mechanically the same across SS13 servers once more. 
Note: The overclock mechanic is still there. Mostly for sabotage purposes. 
As stated above. 
:cl:
balance: vent pumps are unlimited again, as the forefathers intended. 
/:cl:
=> [non-modular] revert the tg vent pump limit

tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss, tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
Reverts the CSS styling for announcements back to TG/Effigy original as in https://github.com/tgstation/tgstation/pull/79071, https://github.com/tgstation/tgstation/pull/79236.
There's no technical need to override this, the announcements overhaul should be implemented as designed. Bubber doesn't need SR's override. 
:cl: LT3
code: Announcement CSS is reverted to TG default
/:cl:
=> Revert announcement CSS back to TG

code/modules/cargo/packs/imports.dm, modular_zubbers/code/modules/cargo/packs/metalsheets.dm, tgstation.dme
closes #789 
Disables the GMM completely until TG gets around to fixing it. You can revert this when they maintain their code.
Because I don't want cargo to make 180 million credits
:cl: The Sharkening
add: Readds the ability to buy metal and glass
del: Removes the GMM from cargo due to infinite money.
/:cl:
=> Disables the Galactic Materials Market completely

modular_zubbers/code/_globalvars/lists/maintenance_loot_uncommon.dm
Bulletproof armor and helmets can no longer be found in maintenance. Exceptions apply to the justice/siren helmet.
There was a misunderstanding of what "old" meant as a subtype. It didn't mean the degrading variant, but rather just an old sprite of the armor.
:cl: BurgerBB
balance: Bulletproof armor and helmets can no longer be found in maintenance. Exceptions apply to the justice/siren helmet.
/:cl:
=> Removes bulletproof armor from maintenance because I lived once.

modular_zubbers/modules/gladiator/code/game/objects/items/gladiator_items.dm, tgstation.dme
- Removes annoying alternative and very loud sound from Gladiator loot.
- Dragonslayer/Marked One/Gladiator/Beserker sword now has a 0% block chance.
- Dragonslayer/Marked One/Gladiator/Beserker no longer has a 100% chance to reflect energy while beserking.
I always thought that the armor just had Anti-Magic, but the reality is that it's just the Immortality Talisman that had it and the Berserker armor actually had a 100% chance to reflect energy during Berserk on top of the sword that had a 25% chance to block. These are just extremely insane stats for a non-shield to have.
:cl: BurgerBB
balance: Removes the 100% reflect energy chance from Marked One armor and the 25% block chance from the Marked One sword.
/:cl:
=> Removes the 100% energy reflect chance from Marked One armor and the 25% block chance from the Marked One sword because my attacks got blocked once.

code/game/machinery/bank_machine.dm
See name
I'll admit, it was pretty funny seeing the dauntless drain the station dry. But this is one of the things that can be used to completely fuck over the station, with no counterplay. Imagine a funny little antagonist going to deep space with one of these. You'll never find them, and even if it were to have a gps signal by the time you were out to the location they could (And most like will) be long gone, or in a different ruin entirely.
This isn't even a salt PR I wasn't in the round, it didn't affect me directly. I am looking at this solely from the objective perspective of "This is really easy to exploit"
:cl:
balance: Disallows siphoning credits outside of station
/:cl:
=> Disallows siphoning credits outside of station

modular_zubbers/code/game/machinery/burger_reactor_sniffer/reactor_sniffer_processing.dm
Fixes the linter issue for the rbmk2, there really should not be any functional changes due to this.
You really shouldn't have linter errors on master.
:cl:
code: /obj/machinery/rbmk2_sniffer/process() no longer checks private variable atom_jntegrity, instead it uses the function get_integrity. No functional changes except removing the error this caused.
/:cl:
=> Fixes a linter issue with the rbmk2

modular_skyrat/modules/horrorform/code/true_changeling.dm
Now okay. I get it. It's huge, it's obvious, it's slow... I don't care if it has more health and sustain than a tank spider or blobbernaut. What I care is that it can fit into vents.
You can kill a changeling horror form with enough manpower. It's hard but it's doable. But the fucking fact it can just... Ventcrawl into any vent and if you don't see the tiny icon during the shitshow and push it? Sorry but that is just absolute aids gameplay. Usually the monsters with ventcrawl are pretty weak to make up for it. But not horrorling. I'm sorry but if you have;
1. 750 health
2. 40 fucking damage swings (A double esword is 34 damage)
3. Passive, CONSTANT life regen
4. Lifesteal off dead bodies
You do **_not_** need ventcrawl. 
Do I really need to explain why having this almost unkillable …
=> Horrorform changeling salt PR

tgui/packages/tgui/interfaces/ZubbersCharacterDirectory.js
Darkens the row colors on the character directory for better contrast with the white text, less searing of the eyes.
None required, really.
=> Darkened character directory rows

modular_zubbers/code/modules/surgery/organs/internal/lungs/_lungs.dm
Reduces the frequency of miasma notifications/coughing by requiring a high miasma count for an effect to take place.
Coughing spam bad.
:cl: BurgerBB
qol: Reduces the frequency of miasma notifications/coughing.
/:cl:
=> Reduces the frequency of miasma notifications/coughing.

modular_zubbers/code/modules/job_estimation/code/dead.dm
I accidentally removed an ! in the job estimation menu, meaning only people who switched it on actually showed on the menu.
Of course, people didn't know this, and didn't turn off their preference. This fixes that.
Job estimation my beloved
fix: job estimation actually works again
/:cl:
=> Oops! Broke Job Estimation!

modular_skyrat/modules/company_imports/code/armament_datums/nakamura_modsuits.dm
Removes the buyable Armour Booster MOD Module from Nakamura, with an emagged cargo console
Requested by SWK
buyable armour booster lmao
This basically was ez free armour for any modsuit, who thought this was a good idea to add?
tbh this removal is going to mean little soon when I introduce modsuit-specific armour boosters for most armoured modsuits (as a nerf), but having this buyable from cargo is incredibly silly.
:cl:
balance: You can no longer purchase armour booster modules for MODsuits from emagged cargo console imports
/:cl:
=> Removes armour booster MOD module from hacked cargo console imports

modular_zubbers/code/modules/jobs/job_types/nanotrasen_consultant.dm
Skyrat/TG maps / automapper don't use our subtype, and don't get our access changes. This fixes it. 
:cl:
fix: ntr gets locker access again
/:cl:
=> Fixes NTR Locker Access

code/datums/elements/immerse.dm, code/modules/power/turbine/turbine.dm
Mirrors 
- https://github.com/tgstation/tgstation/pull/80594
- https://github.com/tgstation/tgstation/pull/80593
New ability unlocked: PR Mirroring
Immerse was causing harddels due to it having references to mobs. Makes it use weakrefs for mobs instead.
The delete the world test was showing that the turbine's non-core parts, the compressor and outlet were causing runtimes, so I made the deactivation of the core remove the references from the secondary turbine parts
Less harddels means less lag, hopefully
Immerse would cause harddels if a mob was deleted while it was in it's list. It could probably also happen if a turf was deleted too, but doing that here would be much harder.
no CL since nothing playerfacing
=> [TG UPSTREAM MIRROR] (#80593) (#80594) (Fixes CI on biodome + other CI fixes)

modular_zubbers/code/game/machinery/crew_monitor.dm
The animation is broken, and this is the fastest way to fix it. 
I won't be reasoning this on bad shifts they just run away so nobody will watch sensors anyhow
:cl:
del: Removes broken stealthmerge change
/:cl:
=> Removes the spasm animation from sensors

code/modules/mob/dead/observer/observer.dm
Reverts a PR that causes observing to break.
https://github.com/tgstation/tgstation/pull/80407 broke it, which was ported to bubber.  But then was also reverted in https://github.com/tgstation/tgstation/pull/80470 for the same issues we are haivng.
It's really rather useful being able to see inventories conveniently.
:cl:
fix: Observing works again.
/:cl:
=> reverts Fixes observers spamming admin logs when observing themselves

_maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm, modular_zubbers/maps/offstation/dauntless/robot.dm
The syndicate access override on the Dauntless gives borgs the radio key as well.
Robotics is now more open so it's easier to spawn a possessed posibrain
No longer do you have to plead Dauntless crew for radios as a borg, or sit in the baby jail until someone notices you
:cl:
add: The syndicate access override on the Dauntless now includes the radio key
add: Windows on Dauntless robotics
/:cl:
=> More dauntless ministuff - robotics edition

code/modules/mob/living/carbon/carbon_defense.dm
Read title
Because sensitive snout here knocks you on your butt
imagine having to test your PRs :^)
:cl:
fix: You can no longer dodge nose boops if you have a sensitive snout
/:cl:
=> Sensitive snout? You can no longer dodge nose boops with quick reflexes

code/modules/antagonists/malf_ai/malf_ai_modules.dm
Malfunctioning AIs can no longer purchase the "Nuke Station" module.
I'm tired of rounds where literally nothing happens for 2 hours and then the AI goes code delta because the Captain called them a mean word in command radio or because the shuttle transfer was called and the AI wants their dogshit gimmick that only involves 2% of the crew to go out with a bang.
It's incredibly bad gameplay design to have a crutch for dogshit malf players to go code delta for no reason and for the crew to enter nukies-tier fight or flight mode where half the crew fucks off to interlink because they're tired of malf rounds, and the other half of crew are required by rules to stay and fight or they want an excuse to use the 50 powerful items they've been hoarding in their dufflebag because they've been …
=> Malfunctioning AIs can no longer purchase the "Nuke Station" module.

tgui/packages/tgui/interfaces/ZubbersCharacterDirectory.jsx
Fixes the character directory to open at a proper size where all the columns are visible by default.
:cl: LT3
fix: Character directory will show all fields without resizing
/:cl:
=> Character directory proper size on opening

modular_skyrat/master_files/code/modules/research/techweb/all_nodes.dm
Simply allows medical borgs to get the crew monitor upgrade again
We have a ton of medical chaos and they need a little help. This was removed on Skyrat because of worries that borgs encroach on their job. Are some of these worries valid? Yes. But medical here always has plenty of work to go around.
:cl:
balance: gives medical borgs back their crew monitors
/:cl:
=> Gives medical borgs back their crew monitor

_maps/skyrat/automapper/automapper_config.toml
Moves the emergancy shuttle from the interlink to the normal centcomm dock.
This will allow the EORG to be easier to understand rule wise and you would not have to worry about Interlink dorms
:cl:
code: Switches the emergancy shuttle to Centcom instead of the Interlink
/:cl:
=> Moves the emergancy shuttle off the interlink

code/game/machinery/computer/crew.dm, modular_zubbers/code/game/machinery/crew_monitor.dm, modular_zubbers/code/modules/mob/living/carbon/human/human.dm
Fixes a lot of the silly sensor console beeping code. (Why was there no break statement)
Makes people on low sensor settings and DNR no longer beep!
Introduces `/mob/living/carbon/human/proc/get_dnr()`
Let's be completely honest, the beeping of the console rarely does anything but annoy the living shit out of people. And having it beep on a random sensorless assistant dying somewhere in a secret maint base that nobody can find is getting on everyone's mind. Same goes for DNR people.
Sources: Trust me
:cl:
qol: Crew monitor consoles receive a new firmware update to address recent complaints, removing the low health alarm on DNR and low sensor settings
code: Introduced get_dnr() proc
/:cl:
=> DNR and suit sensor adjustments

modular_zubbers/code/modules/spells/spell_types/disabled_spells.dm, modular_zubbers/code/modules/spells/spell_types/nerfed_spells.dm
Removes Slaughter Demons from the wizard spellbook.
Laughter Demons cost 2 points (instead of 1), and are limited to 1 purchase per wizard.
Slaughter Demons are a little too crazy for bubberstation. They're extremely tanky, robust, etc etc and their only drawback is "They could kill the wizard" which never really happens. I'm 100% against ghost roles that have this much power to take out half the crew, but I still think they have some sort of place in Bubberstation, so laughter demons are being kept.
Untested. Uncompiled. Unhinged.
:cl: BurgerBB
del: Removes Slaughter Demons from the wizard spellbook.
balance: Laughter Demons cost 2 points (instead of 1), and are limited to 1 purchase per wizard.
/:cl:
=> I BROUGHT YOU INTO THIS WORLD, I CAN TAKE YOU OUT (Removes Slaughter Demons from wizards, limits laughter demons to one purchase)

_maps/map_files/moonstation/moonstation.dmm
Fixes some Moonstation things.
- Fixes mining shuttle not having power.
- Honkbot in clown's room starts unconstructed.
- Fixes missing Bar lighting.
- Fixes missing emergency atmos in maint.
- Fixes missing robodrobe.
:cl: BurgerBB
fix: Fixes some Moonstation things (Fixes mining shuttle not having power, Honkbot in clown's room starts unconstructed, Fixes missing Bar lighting, Fixes missing emergency atmos in maint, Fixes missing robodrobe)
/:cl:
=> Fixes some Moonstation things

code/modules/uplink/uplink_items/job.dm
Removes a fun little item that cuts the station in half.
:cl:
del: Removes the blast cannon from the traitor scientist uplink
/:cl:
=> Removes the blast cannon because I saw someone saw the entire station in half once.

modular_skyrat/modules/clock_cult/code/structures/prosperity_prism.dm
Makes it so that the healing from the prosperity prism is forced, thus making it so that slimepeople can also heal from it.
Clockwork cultist's have their healing self sustain in the form of the prosperity prism. If they just so happen to be a slime though then they're shit out of luck because it will kill them just as quickly as it heals them. This PR, similar to my previous Nanites no longer kill [slimepeople PR](https://github.com/tgstation/tgstation/pull/81458), makes them now heal toxin damage for everyone including slimes.
Tested locally and it didn't kill me. Huzzah!
:cl:
fix: Slimeperson Clockwork Cultists now heal toxins from the prosperity prism properly.
/:cl:
=> Prosperity Prism no longer kills slime clockies. Coggers!

tgui/packages/tgui/interfaces/ForceEvent.tsx
See https://github.com/tgstation/tgstation/pull/81541
closes #1165
Fixes the search logic about checking for nulls, mostly to prevent it from being broken if something else is wrong.
Less bugs, more reliable in the case of errors.
=> [TG MIRROR] Improves the ForceEvent TGUI Search Function (#81541)

modular_zubbers/modules/customization/modules/mob/living/carbon/human/species/xeno.dm, tgstation.dme
Removes Xeno Organs from Roundstart Xenomorph Hybrids. They no longer have plasma vessels, resin spinners, or hive nodes.
>give a roundstart race the ability to listen to hostile xenomorphs
>give a roundstart race the ability to literally shit out walls 
>give a roundstart race the ability to lay floors that are normally an indicator of a hostile antagonist (the floors itself benefit the xenomorphs)
:cl: BurgerBB
del: Removes Xeno Organs from Roundstart Xenomorph Hybrids. They no longer have plasma vessels, resin spinners, or hive nodes.
/:cl:
=> Removes Xeno Organs from Roundstart Xenomorph Hybrids because holy fuck

_maps/map_files/moonstation/moonstation.dmm, modular_zubbers/code/controllers/subsystem/mapping.dm, tgstation.dme
Fixes missing telecomms wire in Moonstation
Fixes missing telecomms wire in Moonstation
Fixes missing telecomms wire in Moonstation
:cl: BurgerBB
fix: Fixes missing telecomms wire in Moonstation
/:cl:
=> Fixes missing telecomms wire in Moonstation

modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/bloodsucker.dm, modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/procs.dm, modular_zubbers/code/modules/antagonists/bloodsucker/vassal/vassal_types/favorite_vassal.dm
Fixes sired 
bloodsuckers having duplicate powers, and also makes applying the bloodsucker datum check if you have a heart or not, so it can properly stop the bloodsucker life, so you don't get stuck in torpor loops as a result, later I need to add some way to get out of torpor loops better.
Checking if you have a heart at the start will also allow them to use the coffin in heart mechanic to gain one if need be.
Trying to make bloodsuckers bugless is a hard job and this is one step closer
:cl:
fix: Ventrue sired bloodsuckers will no longer have a copy of their abilities
add: Bloodsuckers that start out with no heart will be able to regain one, but it now properly checks if they have one or not, and disables their abiltiies accordingly, go into a coffin with a heart if you want to gain …
=> Fixes bloodsuckers sired by ventrue having duplicate powers 

_maps/map_files/moonstation/moonstation.dmm, modular_zubbers/code/_globalvars/lists/maintenance_loot_uncommon.dm, modular_zubbers/code/datums/mapgen/Cavegens/moonstation.dm, modular_zubbers/code/game/objects/effects/spawners/random/moonstation_random.dm, modular_zubbers/code/game/turfs/open/sand.dm
Fixes the following issues (and more)
- Fixes AI control turrets being blocked by a turret.
- Fixes atmos fuckery on the cave level when a turf is destroyed.
- Fixes missing APCs in some areas.
- Fixes missing new tram AC/DC plates.
- Fixes Demoralizer appearing in maintenance loot (Not supposed to be itemized).
- Fixes missing security records filling cabinet in some areas.
Adds the following features
- Adds randomly placed safes that contain 1 rare loot instance
- Adds stethoscopes to maintenance loot.
- Adds drains to below all showers.
- Adds missing steam vents to some maintenance areas.
- Adds unused mining rocks (beta feature to the new mining rework)  to the cave area.
- Adds missing disks and holopad to genetics.
Fixes and changes good.
I tested it okay.
:cl: BurgerBB
fix: Fixes …
=> Moonstation Fixes March 16 2024

modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/integration.dm
The same as the tittle suggests
Its a simple change, waterpig approved. 🦎 
:cl:
fix: Bloodsucker braincheck was missing a null check causing runetimes, its been fixed. 
/:cl:
=> Fixes Blooduckers missing null check which caused runetimes. 

code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
What it says on the tin, again. 
Dying to a death bolt, or getting hit with one while dead (Which isn't hard given they're specifically coded to hit corpses) normally dusts you, which is the one remaining instance of megafauna being a hard round removal. Some fauna, such as vileworm or legion, eat you, but those still allow recovery if the mob is killed, whereas even if a daring miner went to kill the wendigo that downed you, and you didn't get dusted already, you're almost guaranteed to be gone from a death bolt by the time the fight's over. 
Add to that the complete lack of feedback that it was in fact a death bolt that did it, and it can lead to people being dusted with no explanation when fighting colossus/wendigo. 
Spawned 3 wendigos and a colossus, got nuked by death bolt, corpse …
=> [SALT PR] Death bolts no longer dust corpses

code/modules/projectiles/projectile/energy/net_snare.dm
fixes #1067 
This was meant to be a thing. Looking at the gitblame it has been broken for **9 fucking years** (Ever since it was added):
How the hell did NOBODY notice for so fucking long
Actually makes something work as intended. Might make sec consider less lethal options when dealing with threats.
=> [TG MIRROR] Fixes DRAGnet net mode not dealing stamina damage

modular_skyrat/modules/colony_fabricator/code/design_datums/tools.dm, modular_zubbers/modules/colony_fabricator/code/design_datums/fabricator_flag_additions/tools.dm, tgstation.dme
Band-aid fix since https://github.com/Bubberstation/Bubberstation/pull/1298 is in dev hell. Prybars are no longer available in the RCF, and have been replaced with pocket crowbars.
I want to keep the scope fairly narrow so currently you can still order them standalone for 100 creds each.
I've seen a resurgence of departments just ordering a RCF at roundstart with the dept budget. Every department being able to mass-produce what's essentially jaws of life with zero research involved and only a tiny bit of titanium is quite bad.
But if you close your eyes...
:cl:VrazzleDazzle
del: Prybars are no longer available in the Rapid Construction Fabricator.
/:cl:
=> Removes prybars from the RCF

modular_zubbers/code/datums/station_traits/disabled_traits.dm, tgstation.dme
Disables the Station Blackout and Random Machine Language station traits.
Station Blackout would kill all the lights on station. This was awful, especially if there was no janitor.
Random Machine Language would give a random language to every machine that speaks and every bot. This was annoying since it affected cryo announcements and arrivals announcements.
:cl: BurgerBB
del: Disables Station Blackout and Random Machine Languages Station Traits
/:cl:
=> Disables Station Blackout and Random Machine Languages Station Traits

_maps/map_files/moonstation/moonstation.dmm, modular_zubbers/code/game/area/areas/moonstation.dm, modular_zubbers/code/game/turfs/closed/lunar_cave.dm, modular_zubbers/code/game/turfs/closed/lunar_surface.dm
- Adds public mining to Moonstation. It replaces the old biodome near evac.
- Fixes Lunar Cave and Surface Ore not being created correctly when mined (Thanks Skyrat).
- Fixes non-functional restroom button in evac restrooms.
- Morgue Office is now properly named.
- Adds a missing chatroom console in medical.
- Re-adds the stock market in cargo.
- Adds a departmental budget display in the vault and the QM office.
- Adds a bar sign to the strip club.
- Redoes the Bitrunner den for... reasons.
- Adds a special sink to the clown's bar room. For reasons.
- Fixes missing chapel office lights.
- Fixes bad air pipe in ordnance.
People have been asking for this.
Elevators tested. Access tested. Map stuff was run too.
:cl: BurgerBB
add: Adds Moonstation public mining.
fix: Fixes various Moonstation …
=> Moonstation Public Mining and Misc Fixes

modular_zubbers/code/game/objects/items/abductor.dm, tgstation.dme
30 second sleep instead of two minutes
Abductor needs a nerf, and I'll start with something simple to help shift the balance away from being capable of taking down an entire department with a 2 minute sleep.
It works
:cl:
balance: Abductor sleep is 30 seconds instead of 2 minutes
/:cl:
=> Abductor Baton Sleep Nerf

modular_zubbers/code/modules/clothing/under/jobs/command.dm, modular_zubbers/code/modules/command_vendor/vending.dm
No more needing to install CS:S mid ERP
:cl:
fix: Command members no longer have to install CS:S mid erp because they altclicked their stripper outfit
/:cl:
=> [FIX] Removes the ability to adjust the command stripper outfit

_maps/RandomRuins/IceRuins/bubberstation/icemoon_interdyne.dmm
This adjusts the access requirements for the brig armory closet and the suit storage. It changes `syndicate_leader` to `syndicate`
It means non-deck officer crew can use these without having to take an axe to the closets.
I have ran this on my local server and confirm it works.
:cl:
fix: Interdyne brig closets can be accessed by regular crew
/:cl:
=> Interdyne: Adjust access for brig lockers and suit storage

_maps/moonstation.json
Fixes the second layer of moonstation creating space turfs.
This bug was caused by a missing pathtype in the map config.
:cl: BurgerBB
fix: Fixes the second layer of moonstation creating space turfs.
/:cl:
=> Fixes the second layer of moonstation creating space turfs

modular_zubbers/code/modules/storyteller/event_defines/roleset/_antagonist_event.dm
Adds Departmental Guards to the Protected Pool for antag rolls, meaning they cannot become an antagonist like any other member of security (They can of course roll obsessed). Tested locally with the create antagonist function.
Makes all of security and departmental guards follow the same internal 'ruleset', as well as follows the old results of this poll, assuming that departmental guards being antagonists has not been an overlooked bug. https://discord.com/channels/1059199070016655462/1064014401172160542/1241791239133855784
:cl:
fix: Prevents Departmental Guards from rolling antagonist roles.
/:cl:
=> Adds Departmental Guards to the protected pool.

code/modules/events/_event.dm
:cl:
fix: Storyteller should only take two minutes instead of five to spawn events. 
/:cl:
=> fix two sets of delays on storyteller events

modular_zubbers/code/modules/quirks/code/positive_quirks/dominant_aura.dm
per title
bug fixes
It worked
:cl:
fix: Dead well-trained quirk holders will no longer respond to snaps
/:cl:
=> Fixes dead subs being effected by dominant aura

_maps/map_files/moonstation/moonstation.dmm, _maps/moonstation.json
Fixes moonstation having space turfs on turf destruction on the upper level.
Fixes weirdly placed camera monitors due to upstream changes.
Fixes a few randomly placed doors in some areas.
:cl: BurgerBB
fix: Fixes moonstation having space turfs on turf destruction on the upper level. Fixes weirdly placed camera monitors due to upstream changes. Fixes a few randomly placed doors in some areas.
/:cl:
=> Moonstation Space Fixes + Mapping Errors + Upstream induced mapping errors

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/LimaStation/LimaStation.dmm, _maps/map_files/biodome/biodome.dmm, _maps/map_files/moonstation/moonstation.dmm
Removes varedited SMES and replaces with subtypes and APC helper, keeping them up to TG standard.
Telecomms quits dying roundstart
Nothing player facing
=> Update Bubber telecomms SMES

_maps/map_files/moonstation/moonstation.dmm
Changes the contents of a "flask of holy water" containing what decidedly isn't holy water in the name of a tasteless pun to actually contain holy water.
"Jokes" of this nature leading to easy pref-breaks should not be tolerated here.
unneeded
=> Removes tasteless joke from moonstation

code/modules/mob/living/silicon/robot/robot_defense.dm
Reverts Bubberstation/Bubberstation#1528
Reverts the 2 second emag time. I was kind of vibing with this at the start, but I've really kind of changed my mind and I think this was a sloppy way to handle this mechanic.
1. Emagged borgs have substantial counters where emagging one already takes quite a bit of time (in the hall) for the average crewmember to do. You need to still hack its cover, crowbar the borg, *then do a 2 second do_after* which makes it not really any feasable. It basically railroads emagging borgs mostly to the roboticist now, which the diffrence between an instant action and a !do_after isn't going to make much of a diffrence.
2. Siliconnect litterally tells anyone who scans the borg who emagged it. See a cover glitch? Use it.
3. It's not uncommon for an AI to …
=> Revert "Nerfs No-Talk Borg Emags"

code/modules/surgery/blood_filter.dm
Updates the check for the blood filter's toxin removal so that the surgery step is allowed to start. Updates the removal proc to work similar to the new blood filtering clamp.
Toxin filtering to blood filter was added, but the surgery step check won't start unless there's reagents.
:cl: LT3
fix: Blood filter toxin removal feature now starts correctly
/:cl:
=> Fix blood filter filtering toxins

_maps/map_files/moonstation/moonstation.dmm, modular_skyrat/modules/liquids/code/liquid_systems/liquid_plumbers.dm, modular_zubbers/code/game/turfs/open/openspace.dm
Fixes a CI failure due to #1839 being untested and using the wrong path for holy water. (Seriously?)
https://github.com/Bubberstation/Bubberstation/actions/runs/10131978025/job/28015352052#step:4:149
Causes a holy water container *actually* contain holy water. Also fixes a CI failure.
https://github.com/Bubberstation/Bubberstation/blob/94449bc91e123a2cd6bbdaa63b0e3e2a838396ff/code/modules/reagents/chemistry/reagents/other_reagents.dm#L377
:cl:
fix: A holy water container on Moonstation now actually contains holy water.
/:cl:
=> Fixes a issue causing CI to fail

modular_zubbers/code/modules/alternative_job_titles/code/alt_job_titles.dm
Title.
It was added upstream. It's no longer needed down here.
:cl:
del: Duplicate Butler title is gone.
/:cl:
=> Removes the Butler title (because it was added upstream)

_maps/map_files/moonstation/moonstation.dmm
Remake of #1859 on a clean branch.
Fixes Moonstation linters (hopefully).
Fixes floating air alarm in the AI upload.
Repaths most of the water spawns.
Adds a hidden pulse rifle.
The public mining elevator can now go down to lavaland.
Adds more carpet to dorms.
Fixes good.
:cl: BurgerBB
fix: Fixes some moonstation issues.
/:cl:
=> Moonstation Linter Fixes and other stuff v2

code/game/machinery/rechargestation.dm, code/modules/surgery/organs/internal/stomach/stomach_ethereal.dm
Special thanks to Waterpig for help with this, this adds a new argument to the recharge station that allows you to set a limit on how much a thing is charged.  And adds an entry within the ethereal stomach that takes advantage of this new argument, allowing them to safely charge at cyborg chargers.  No more shall ethereals invoke the wrath of Zeus upon their compatriots for making the mistake of using a cyborg recharger!
Allows ethereals to safely use cyborg rechargers without instantly invoking the wrath of Zeus upon their fellow crewmen.  Also allows for potential future usage for other things if someone wants to include a reason to restrict the amount a cyborg recharger station can charge.
Tested locally, works flawlessly.  Borgs charge, modsuits charge, ethereals no longer overcharge …
=> Ethereal Cyborg Charging tweaks

_maps/map_files/moonstation/moonstation.dmm
For Moonstation:
- Fixes a floating fire alarm near dorms.
- Fixes the constant splooshing near the QM's office.
- Adds a pirate cannon to the armory. It requires command access to open.
- Fixes dim chaplain office.
- Fixes directional chemistry shutters.
- Fixes misplaced floor tile decals in virology.
- Scraps the disposals system in virology in favor of a new one that dumps it to the z-level below.
Fixes good.
If it compiles, it works.
:cl: BurgerBB
fix: Fixes even more moonstation issues.
/:cl:
=> Moonstation Even More Fixes + Feature

_maps/map_files/moonstation/moonstation.dmm, modular_zubbers/code/modules/power/lighting/light_mapping_helpers.dm, tgstation.dme
Fixes Moonstation Lighting being too dark.
I solved this by creating my own moonstation subtype of light fixtures so they can't be fucked with by upstream.
Fixes good.
Tested. Forgot to take a screenshot.
:cl: BurgerBB
fix: Fixes Moonstation Lighting being too dark.
/:cl:
=> Fixes Moonstation Lighting being too dark.

modular_zubbers/code/modules/bow_adjustments/arrow.dm
Title
closes #1853 
:cl:
fix: bows properly apply damage as ashwalker/icecat
/:cl:
=>  Arrows now properly apply their damage buff when used by ashwalkers and ice cats

modular_zubbers/code/modules/wizard_dize/wizard_dice_event.dm
Significantly Boosts the chances of the Wizardly Die of Fate event triggering.
The event now has a 20% chance not to announce the existence of a Wizardly Die of Fate
The event is now as common as the shuttle getting replaces by a disaster.
I've been getting complaints that this event is still extremely rare. This PR should fix that.
People want more wizard rounds. This should grant more wizard rounds.
The announcement chance tweak should also be more interesting.
Untested.
:cl: BurgerBB
balance: Significantly Boosts the chances of the Wizardly Die of Fate event triggering. The event now has a 20% chance not to announce the existence of a Wizardly Die of Fate
/:cl:
=> Significantly Boosts the chances of the Wizardly Die of Fate event triggering.

modular_skyrat/modules/quirks/neutral.dm, modular_zubbers/code/modules/mob/living/carbon/human/species/tajaran.dm
Removes the tajaran tongue override from https://github.com/Bubberstation/Bubberstation/pull/1985 instead moving the tongue to the augments menu, like the lizard forked tongue.
Consistency, people can equip Feline Traits to get the felinid features.
<details>
</details>
:cl: LT3
code: Tajaran tongue moved from Feline Traits quirk to augments menu
/:cl:
=> Remove tajaran tongue from feline traits

code/datums/quirks/negative_quirks/claustrophobia.dm
This makes it so that the claustrophobia quirk does not trigger inside vore bellies, as requested by @StrangeWeirdKitten 
As hilarious as this emergent gameplay is, it's not really nice to kill people for having any vore scenes when they have the claustrophobia quirk for reasons other than scene-ing.
I forgot to get a screenshot of the chat - there's just no negative moodlet for claustrophobia in a belly anymore. 
:cl:
fix: Claustrophobia no longer triggers inside vore bellies.
/:cl:
=> Make it so claustrophobia does not trigger in vore bellies (hilarious bug)

modular_zubbers/code/modules/storyteller/storytellers/tellers/storyteller_destructive.dm
Disables "The Bomb" storyteller from being votable 
Because of the limited amount of destructive events, the bomb tends to:
- Spawn a fuckton of anomalies and only anomalies during minor event rolls.
- Spawn extremely destructive round-ending major event rolls, like meteors.
- Somehow encourages antagonists to do bomb gimmicks because "That's what people voted for."
The bomb is voted for as a meme, much like tram. People want to see other people suffer. Let us put a stop to that.
Untested.
:cl: BurgerBB
del: Disables "The Bomb" storyteller from being votable because engineering cryos every time it's voted.
/:cl:
=> Disables "The Bomb" storyteller from being votable because engineering cryos every time it's voted.

modular_zubbers/code/modules/storyteller/storytellers/tellers/storyteller_predictable.dm
I am legitimately not sure why the number ended up being 20 instead of the hinted at 10. There might've been a good reason so It's now 15.
Predictable Chaos is boring.
Untested.
:cl: BurgerBB
add: Predictable Chaos now has 50% more antagonists.
/:cl:
=> Adds more antags for Predictable Chaos.

code/modules/transport/tram/tram_signals.dm
Fixes an early return and idle state when the signals don't bother processing if they're broken/misconfigured/tram missing.
=> [EARLY MIRROR] Fixes tram crossing signal because Cato got run over once

modular_zubbers/code/modules/mob/living/basic/space_fauna/space_dragon/space_dragon.dm, tgstation.dme
Makes Space Dragons immune to toxin + oxy damage because I saw a Space Dragon die to simplemobs on Moonstation Once
This is pretty much a moonstation exclusive problem since a whole bunch of toxic enemies spawn outside so yeah.
If it compiles, it works.
:cl: BurgerBB
balance: Makes Space Dragons immune to toxin + oxy damage because I saw a Space Dragon die to simplemobs on Moonstation Once
/:cl:
=> Makes Space Dragons immune to toxin + oxy damage because I saw a Space Dragon die to simplemobs on Moonstation Once

modular_zubbers/code/modules/quirks/code/negative_quirks/well_trained.dm
Literally unplayable.
Fixes a typo.
No.
:cl:
spellcheck: Fixed a typo in the message that appeared when someone with the Well-Trained perk examined someone with the Dominant Aura trait.
/:cl:
=> Fixes a typo when well-trained perk triggers.

modular_skyrat/modules/window_airbags/code/window_airbag.dm
patches airbags from interaction by non living
bugfix
:cl:
fix: airbags are no longer haunted
/:cl:
=> airbag patch

_maps/map_files/moonstation/moonstation.dmm
Removes the Mannequin in Moonstation engineering because a shaft miner died to it 5 times.
Removes the Mannequin in Moonstation engineering because a shaft miner died to it 5 times.
Removes the Mannequin in Moonstation engineering because a shaft miner died to it 5 times.
:cl: BurgerBB
del: Removes the Mannequin in Moonstation engineering because a shaft miner died to it 5 times.
/:cl:
=> Removes the Mannequin in Moonstation engineering because a shaft miner died to it 5 times.

modular_zubbers/code/game/objects/structures/aliens.dm, tgstation.dme
Buffs Xeno Weed temperature survivability in hotter environments. It was increased from 300K to 350K, which is only slightly higher than Moon Station's external temperature of 347.65K.
This should allow xenos to build nests in Moonstation while still suffering from flamethrowers.
:cl: BurgerBB
balance: Buffs Xeno Weed temperature survivability in hotter environments. It was increased from 300K to 350K, which is only slightly higher than Moon Station's external temperature of 347.65K.
/:cl:
=> Buffs Xeno Weed temperature survivability in hotter environments.

modular_zubbers/code/modules/antagonists/heretic/transmutation_rune.dm, tgstation.dme
Heretic Transmutation Runes can no longer have Fingerprints.
This does not affect "hidden" fingerprints aka fingerprints for admin logs.
This does not affect clothing fibers. 
It's funny that if you interact with a rune, your fingerprints are applied to it. This results in heretics getting caught extremely easily and early. It doesn't make sense to me that interacting with an eldritch rune would do this.
Untested.
:cl: BurgerBB
balance: Heretic Transmutation Runes can no longer have Fingerprints.
/:cl:
=> Heretic Transmutation Runes can no longer have Fingerprints.

modular_skyrat/modules/alternative_job_titles/code/alt_job_titles.dm, modular_zubbers/code/modules/alternative_job_titles/code/alt_job_titles.dm, tgui/packages/tgui/interfaces/common/JobToIcon.ts
We already have a boat-load; why not more?
**Blueshield:**
- Command Protection Officer
**Detective:**
- CID Officer
**Nanotrasen Representative:**
- Corporate Consultant
**Security Officer:**
- Security Specialist
- Defense Contractor
**Shaft Miner:**
- Dredger
- Contract Miner
I have not tested this. It _shouldn't_ have issues, given it's just a few more alt-job names, all properly formatted.
It gives players more options as far as who they feel they're playing as. I know there's a Security Union, for example, that may want to be represented differently. 
:cl: Bangle
spellcheck: Added some alt titles
/:cl:
=> More Alternate Job Names!

_maps/map_files/BoxStation/BoxStation.dmm
Removes the air alarm that's out in space near the incinerator on BoxStation because I don't think it's supposed to be there and it just gives a priority alert to Engineers all round that there's no air in Space.
I don't think we need to monitor the atmosphere in Space.
Trust me (or check the map diff)
:cl:
del: Remove air alarm in Space from BoxStation.
/:cl:
=> Remove random space air alarm from boxstation

code/datums/station_traits/negative_traits.dm, modular_skyrat/master_files/code/datums/station_traits/negative_traits.dm, tgstation.dme
Reverts https://github.com/Skyrat-SS13/Skyrat-tg/pull/24839 entirely
Imagine killing an event because engineering was incompitent for a single shift and they didn't set up the things that give you multiple warnings to set up.
weh
:cl:
add: Radiation Storms will now irradiate the station again if you don't set the shields up.
/:cl:
=> Reverts Skyrat's Radiation Storm edits

code/controllers/subsystem/job.dm
Add back the `|| job.title` fallback for if the user isn't using an alt job title for a given job, because it went missing in https://github.com/Skyrat-SS13/Skyrat-tg/pull/23990 for some reason
Fixes #2214 
<details>
</details>
:cl:
fix: fixed department head arrival radio messages missing their job title
/:cl:
=> Fix job title in head arrival radio messages being empty

_maps/RandomRuins/LavaRuins/bubberstation/lavaland_dauntless.dmm
Due to the change in https://github.com/tgstation/tgstation/pull/86548, Dauntless' vendors began costing money.
This PR undoes the old map varedits to vendors, and uses the new one to appropriately subsidize all the items.
hee hoo
Been doing the var change in game, it should work.
:cl:
fix: Dauntless vendors no longer require money to use, as before.
/:cl:
=> Fixes dauntless vendors costing money

code/modules/power/apc/apc_main.dm
Fixes an APC change in https://github.com/Skyrat-SS13/Skyrat-tg/pull/27358 that was lost in an upstream update.
Closes https://github.com/Bubberstation/Bubberstation/issues/2275
:cl: LT3
fix: APCs again trigger lighting channel before equipment channel
/:cl:
=> Fix APC autochannel priority

code/modules/mob/living/carbon/examine.dm
The examine rework bulldozed the change letting people see how long someone has been SSD for. This fixes it.
🪿
💤
:cl:
fix: SSD timer now visible once more.
/:cl:
=> Fixes the SSD timer when examining

.github/workflows/compile_changelogs.yml
Updates compile_changelogs with Bubberbot information and a different commit name to differentiate the commits from tgstation changelog compiles.
Now that we're a direct downstream, we can automatically compile our changelogs so long as we properly skip tgstation changelog compiles.
n/a
=> Update compile changelogs Github action

_maps/map_files/moonstation/moonstation.dmm
#2242 was a dirty map merge and I reverted it.
@YakumoChen byond's native tools are depreciated. Strong.dmm is far better and robust to use, regardless. https://github.com/SpaiR/StrongDMM
=> Moonstation GMM removal

code/modules/reagents/reagent_containers/cups/_cup.dm, modular_skyrat/master_files/code/modules/mapfluff/ruins/spaceruin_code/oldstation/oldstation_cytology.dm, modular_zubbers/master_files/code/modules/reagents/reagent_containers/cups/_cup.dm, tgstation.dme
Reverts #2263 and changes cryo beaker to 60u
Let me be frank, the beaker nerf pr was just pushed through github with most of the players finding out from the changelog - the reaction on discord has been... rather negative, even the #2263 discussion and reacion on github is mostly negative, yet it was merged anyways.
It was a wide scale nerf to both roundstart medsci and service (which cannot print the upgraded beakers...) and it was poorly supported with the main motivation being to make medical cook plastic... which can be easily obtained by just asking... or in 2 different ways from cargo. Nerfing chemistry, medicine, science and service over it is... bad and annoying? 
Reverting the changes avoids the nerfs and pointless disruption to the game. Also more beaker space is good, as …
=> Reverts #2263 - restoring beaker capacity to original, original values, plus changes cryo beaker for consistency

_maps/RandomRuins/SpaceRuins/skyrat/port_tarkon.dmm, modular_skyrat/modules/tarkon/code/misc-fluff/fax.dm, tgstation.dme
Create a subtype of the fax machine that has Tarkon Command as a contact, replace var-edited fax machine in Port Tarkon with this.
The var-edited one runtimes because `Initialize()` in fax machine code tries to populate the CentCom contact but the variable edit has overwritten `special_networks` with its own list (if the Tarkon one is not intended to have CentCom listed please let me know so I can change the PR to make that the case).
Trust ‼️ 
<details>
</details>
:cl:
fix: The fax machine in Port Tarkon should no longer give a TGUI error.
/:cl:
=> Fix Tarkon Fax Machine

modular_zubbers/code/modules/storyteller/storytellers/tellers/_storyteller.dm
Fixes a semi-frequent runtime in storyteller code that causes CI to fail, see: 
https://github.com/Bubberstation/Bubberstation/actions/runs/11641923588/job/32420967445
https://github.com/Bubberstation/Bubberstation/actions/runs/11641923588/job/32420968238
for examples, this is caused by calculated weights for events often being non-whole numbers, which are then fed into `pick_weight` which is explicitly designed to only handle integers. 
Fixes https://github.com/Bubberstation/Bubberstation/issues/1969
One less cause of checks randomly failing.
Hard to prove lack of errors but I did a unit test that ran `find_and_buy_event_from_track` 200 times in a row and before this change it always failed and after this change it doesn't.
<details>
</details>
:cl: …
=> Fix storyteller null event runtime

code/modules/power/cell.dm
Does as it says on the tin
Bugs bad, full batteries don't look like they're empty.
<details>
</details>
:cl: LT3
fix: Fixed upgraded power cells always showing red/empty.
/:cl:
=> Fixes upgraded power cell not showing a charge indicator

_maps/moonstation.json, modular_zubbers/code/__DEFINES/moonstation_defines.dm, modular_zubbers/code/controllers/subsystem/mapping.dm
Create a separate ZTRAIT for the lowest level of moonstation, use that when running the moonstation-specific ruin generation (still pulls from the lavaland ruin pool). This is because currently ruin generation runs twice on every map, the first time with an area whitelist of Lavaland Wastes (the /area used for the actual lavaland z-level), and then again with an area whitelist of Lavaland Caves (the /area used for the lowest z-level of moonstation). Each map only contains one of those two areas, meaning one of the generation runs will fail for every single ruin, exhausting 100 attempts per ruin, every time. 
Faster server load times and hopefully no CI timing out.
<details>
Before:
After:
</details>
:cl:
fix: The game should no longer run ruin …
=> Makes ruin generation like a million times faster

modular_zubbers/code/modules/vending/wardrobe.dm
Very tiny PR. Adds the science bag to the SciDrobe.
There are only 2 science bags in xeno. If they both get lost, you can't really do Xeno anymore. I mean you CAN, but it really sucks.
Ran the Runtime Station. Spawned a SciDrobe. Science bag is in there.
</details>
:cl: Midiwidi
add: Added science bag to SciDrobe
:cl:
=> Added science bag to SciDrobe

code/game/objects/items/devices/scanners/health_analyzer.dm
Fixes an issue with blind people not actually being able to use the health analyzer.
Pretty self explanatory, lets people with the blindness quirk or echolocation quirk actually use the health analyzer. This seems to be intended behaviour judging by the code, but doesn't actually work. Fixing it was a one line modification.
People with those quirks can actually do surgery. Yay for bluespace braille!
<details>
It's a one line change. It compiles and runs.
</details>
:cl:
fix: Makes blind people able to actually use the health analyzer again.
/:cl:
=> Lets Blind People (Actually) Use the Health Analyzer

modular_zubbers/code/modules/projectiles/ammunition/ballistic/rifle.dm, tgstation.dme
Title
There's no reason people should be running around with it
I didn't test it
:cl:
del: Phasic strilka ammo is no longer printable.
/:cl:
=> Phasic strilka ammo no longer printable

.github/workflows/compile_changelogs.yml
Fixes workflow so auto changelog compile stamps the right dates on changelog entries
Nobody else may notice it's off by a day, but I know, and it bugs me.
=> Fix autochange log entries being off by a day

code/modules/mob/living/basic/pets/cat/cat.dm
Fixes alternate meow/purr from being restricted after an upstream mirror.
<details>
</details>
:cl: LT3
fix: Alternate meow and purr emotes work again
/:cl:
=> Fix alternate meow/purr

modular_skyrat/modules/reagent_forging/code/forge_weapons.dm
Wierdly enough, bokkens revert to 8 force when wielded, and 16 damage when not, i'm not sure if this was intended or not but the description nor commits seem to indicate so, thus I'm setting the force of bokken to 8 and making wielded go up to the original 16 force when unwielded, as it seemed reversed beforehand
<details>
</details>
:cl:
fix: Fixes the bokken having 16 damage when unwielded, and 8 when it is
/:cl:
=> fix bokken wielded damage

modular_zubbers/code/modules/lunchbox/code/lunchbox.dm
Doubles lunchbox storage from 4 to 8 slots, lets them hold condiments, gum, ciggys and lighters
lunchboxes currently kinda suck, there's no real reason to use them over cardboard boxes which you can get from food vending machines
I did compile it to check, it's just a simple edit so...
:cl:
balance: NT's bluespace technology doubles lunchbox storage from 4 to 8 items with special lining
add: lunchboxes can also hold condiments and gum now... and cigarettes and lighters, at the insistence of our sponsors in the space tobacco industry
/:cl:
=> expands your lunchbox

_maps/map_files/moonstation/moonstation.dmm
Issue Summary:
On Moon Station while observing I signed up for nightmare, I was the sole player signed up for it. once the timer ended. I did not spawn in as nightmare, admin responded in chat:
STAFF (Sexmaster) says, "ADMIN LOG: No valid generic_maintenance_landmark landmarks found, aborting..."
Generic_landmark_spawn locations were added to the map in areas that satisfy the specific criteria for a nightmare to spawn.
Was able to repro the issue and fix it in the map.
It allows more antagonists roles to be played on Moonstation, potentially seeing it played more with antag spawn points added.
Fixes #2391 
:cl: Sparex
map: Added generic_maintenance_spawn points to fix the issue with the Nightmare not being able to spawn. They will now spawn as they should.
:cl:
=> Added generic_maintenance_spawn points to Moonstation.dmm

modular_skyrat/modules/cryosleep/code/cryopod.dm
Issue Summary: 
When attempting to use a wallmounted cryopod it simply does not move the player inside causing the message pop up about entering the cryopod. due to this any situation where someone has to use a wallmounted cryopod they're unable to which is a problem for prisoners as they often only have wallmounted cryopods.
The code for the wall-mounted cryopods in modular_skyrat\modules\cryosleep\code\cryopod.dm were not properly calling the close_machine() proc. The code has been adjusted so that it now properly works as intended.  
PR has been tested and is working. Screenshots provided below as proof.
This makes the wall-mounted cryopods fully functional now, giving map creators more ways to add in exit points for players that need to leave for whatever reason.
Fixes #2040
:cl: …
=> Wall-Mounted Cryopod Fix

modular_skyrat/modules/deforest_medical_items/code/injectors.dm
meridine no longer ODs you
the medipen being literally on the edge of overdose feels really silly
it's a single number change
:cl:
balance: meridine has 1u less ammoniated mercury
/:cl:
=> meridine overdose removal

modular_skyrat/modules/food_replicator/code/medical.dm, modular_skyrat/modules/food_replicator/code/replicator_designs/replicator_food.dm
Removes pressure check from the glucose medipen, and changes the description a bit.
Why are we gating glucose behind a pressure check like miner healing pens again? No one uses this thing.
Simple change, but I did actually test it on localhost.
:cl:
balance: removes pressure check from the glucose medipen and changes its description
/:cl:
=> depressurizes your glucose injector

modular_skyrat/modules/customization/modules/food_and_drinks/food/scottish.dm
Fixes #1514 
Issue Summary
Normally when you cut up a cooked sausage with a sharp object, you get a small menu that pops up asking if you want to cut it into pieces of salami or cut it into an "american sausage" with the tip missing. Haha. This wouldn't be a problem if not for the fact that this makes two very, very specific cooking recipes which use the american sausage impossible. Very urgent I know.
Basically, using the knife on the sausage would automatically cut it into Salami. The choice pop-up to choose between salami and American Sausage was not occurring. Now, the dialogue pops up properly so the user can choose between the two ingredients instead of always being forced to cut into Salami.
There is a very specific recipe in tg database "Budae-Jjigae" that is reliant on that sole …
=> American Sausage can now be created again!

code/game/objects/items/devices/scanners/health_analyzer.dm
Early pull of https://github.com/tgstation/tgstation/pull/87109
Closes https://github.com/Bubberstation/Bubberstation/issues/2472
🆑 LT3
fix: Medical should again be able to tell if your heart is missing, hopefully
/:cl:
=> Fix health analyzer not showing missing heart

modular_skyrat/modules/cargo/code/items/gbp_punchcard.dm
Tin, doesn't remove the puncher from code because I don't feel like removing it from maps (if it exists), also gives the option for bussing I suppose.
Requires head access to puch GAP cards. Not much else to comment on, really.
GAP cards are almost never used, and heads ditch the stamp like it's hot. Let's just clear up some of the head clutter and instead make it PDA bound.
Also let's make it worth 150cr, cause 100cr seems a little cheap. This makes the max possible payout now 900 instead of 600.
<details>
https://github.com/user-attachments/assets/6f67b09e-6706-4e40-9720-868fedf73b06
</details>
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Heads no longer start with GAP punchers.
qol: Heads (anyone with command …
=> Make PDAs Able to Punch GAP Cards, Buff Payout to 150cr

modular_zubbers/code/modules/clothing/accessory/accessory.dm
Issue Summary: "With a recent sprite update, flag options were removed from the pride pin, namely the man-man loving pride pin.
i just would like to see it back."
With the recent changes to the pin sprite, they removed a lot of the options that used to exist. The only difference is in how the pin looks on hand but it still looks the same on the mob once attached anyways.
Changing back to the old option of having a pride pin gives back the many different options in the spectrum of sexual and gender orientation/identification. The icon still looks the same anyways when attached to the mob so making it easier for players to identify others through this pin system with more variety.
Fix #1723 
:cl: Sparex
fix: Replaced tg database pride pin sprites with flag versions that allowed more …
=> Man-Man Loving pins are back!

_maps/map_files/VoidRaptor/VoidRaptor.dmm
Change the evac sign outside of Engineering on Void Raptor to point up instead of left because evac is up and not to the left
No trick signs
It's a map change trust me !!
<details>
</details>
:cl:
map: Fixed incorrect evac sign on Void Raptor
/:cl:
=> Fix incorrect evac sign on Void Raptor

modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/queen.dm
ditto as per PR title, TG queens have this, but not skyrat's
mechs nor punches no longer KO queens, confirmed by testing
:cl:
add: Skyrat xeno queen can no longer be KO'd, just like TG queens cannot.
/:cl:
=> xeno queen can't be KO'd anymore

code/modules/mob/emote.dm
As it says
:cl: LT3
fix: Ghosts can use the flip emote again
/:cl:
=> Fix ghosts being unable to flip

_maps/map_files/BoxStation/BoxStation.dmm
This adds a single cable wire under an airlock for the drone bay that I missed out on changing for Boxstation's last PR (https://github.com/Bubberstation/Bubberstation/pull/2545)
:cl:
fix: Places a missing cable leading to the drone bay on Box Station
/:cl:
=> quick fix for a missing cable on Box Station.

modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/romulus_technology/smg.dm, modular_skyrat/modules/sec_haul/code/guns/sec_gun_rs.dm
Removes the starting magazine from the newly-crafted Shaytan SMG. The spontaneous manifestation of live ammo and a spare magazine was an oversight.
Balancing?
I did not test. I have copied code that I've seen for pistols spawning without mags and have prayed that it works.
</details>
:cl: Bangle
balance: rebalanced something
fix: fixed a few things
/:cl:
=> Removes the magical Shaytan magazine when crafted.

code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm, modular_zubbers/code/modules/storyteller/_events/scrubber_overflow.dm
Small changes to scrubber overflow. Reduces the amount of reagent by roughly 30%, Adjustment to ethanol chems.
Flooding people with 120+ units of something has an effect lasting too long, this should tamper it down a bit. The ethanol dose shouldn't mean guaranteed liver death or being drunk for a half hour.
:cl: LT3
balance: Minor reduction to the strength of scrubber overflows
/:cl:
=> Scrubber overflow reagent adjustment

modular_zubbers/maps/offstation/dauntless/mob_spawns.dm
Title.
This has already been merged into persistence, but for parity's sake, it should be added into dauntless.
Enhances interrogations, mostly. Also good for blackmailing people who decide to fuck w/ dauntless.
<details>
</details>
:cl:
add: Dauntless now has exploitables
/:cl:
=> Enables exploitables access for dauntless spawners

modular_zubbers/code/modules/autolathe_components_adv/advpartdisks.dm
Closes https://github.com/Bubberstation/Bubberstation/issues/2530
Turns out when we made the autolathe disks we overrode a bunch of stock part printability code, which would have been fine except mechfabs were left out of the new code.
Bugs are bad
<details>
</details>
:cl:
fix: fixed hyper and super cells not being in mechfabs like the rest of the cells
/:cl:
=> Fixes some cells not being in the mechfab

modular_skyrat/modules/cortical_borer/code/abilities/_borer_abilities.dm, modular_skyrat/modules/cortical_borer/code/abilities/host_movement.dm, modular_zubbers/code/modules/borer_hud/borer.dm
Fixes borer stun ability not working properly, stun and infest abilities should now properly toggle off when they've been used appropiately, borer say will no longer sanitize text itself and allows say to sanitize them to prevent ' being sanitizied into a unreadable mess that lets you meta borers.
Also fixes the action buttons appearing sort of active sometimes, hopefully.
Good fixes are always good.
Thoroughly tested ingame
:cl:
fix: Borer stun should no longer randomly fail to work
fix: Borer say no longer badly sanitizes your messages causing issues with what you say.
fix: Borer action buttons shouldn't stay "active".
fix: Borer Infest will no longer cooldown if you fail to enter a host.
/:cl:
=> Borer action button fixes

modular_zubbers/code/datums/quirks/neutral_quirks/entombed.dm
This has been a long annoyance for me; now, people with the entombed quirk will no longer take tox damage if they're dead  (and their modsuit is dead).
This shouldn't apply after revival, as they'll no longer be dead.
It doesn't make sense with how the quirk is explained, as the suit is keeping the person alive. I don't think the suit's pumping toxins into the user when dead, so this stops that.
TBD
:cl:
fix: Entombed modsuits no longer cause stacking toxin loss if the entombed is dead.
/:cl:
=> Entombed suits no longer add tox damage if their occupant is dead.

code/__DEFINES/maps.dm
We have memory issues and we need to start cutting down on it. I'd rather keep our ghost roles intact and the Interlink intact with this being the first solution.
Halves the amount of ruin Z levels that spawn. (7 to 4 by default)
=> Reduces the amount of ruin Z levels

code/datums/world_topic.dm
If you set up a server without `COMMS_KEY` set it will be blank, which is a valid key
CommKey validation should fail closed not open
https://github.com/tgstation/tgstation/pull/88367
=> [s] ensure key config is set for any secure request (#88367)

code/modules/antagonists/space_dragon/carp_rift.dm, code/modules/antagonists/space_dragon/space_dragon.dm, code/modules/movespeed/modifiers/mobs.dm, code/modules/unit_tests/dragon_expiration.dm
When the dragon runs out of time to make a rift, instead of deleting the dragon, they are given the dragon depression movespeed debuff.
You are forced to get into full on combat with everyone or be literally deleted, this should give people a chance to RP as dragon, with dragon
Tested and it confirmed that it did not break the victory condition
:cl:
del: Dragon no longer gets deleted if you don't do rifts, instead you are given dragon depression, which slows you down heavily.
/:cl:
=> Not doing portals no longer kills the dragon

modular_zubbers/code/modules/mob/living/basic/space_fauna/space_dragon/space_dragon.dm
as PR title says
Currently dragon tends to absolutely get bodied almost always, and dragon depression currently is 100% a death sentence, that is, the slowdown being far too much for a mainly melee antag to survive.
tested the slowdown and the other one's just number changes
<details>
</details>
:cl:
balance: Dragon depression slowdown is now only 2.5, where it used to be 5.
/:cl:
=> Halves dragon portal loss slowdown

code/__DEFINES/~skyrat_defines/DNA.dm, modular_skyrat/modules/cortical_borer/code/cortical_borer.dm
Borers don't show up on manipulate organs, apparently. This is not intended.
This was caused by the organ slot not being set.
Bug bad, also what the fuck we shouldn't have to debrain someone to get them out.
<details>
Also removed the thing and it came out without issues.
</details>
:cl:
fix: Cortial borers can be surgically removed again.
/:cl:
=> Fix Cortial Borers Being Unremovable

code/modules/events/tram_malfunction.dm, code/modules/transport/tram/tram_controller.dm, code/modules/transport/tram/tram_structures.dm, code/modules/transport/transport_module.dm, html/changelogs/AutoChangeLog-pr-88371.yml
Early Pull: https://github.com/tgstation/tgstation/pull/88371
- Fixes emagged tram spoilers from appearing welded/displaying weld hints
- Tram malfunction checks for humans before throwing
- Tram control panel flashes orange when malfunction can be fixed
- Better visual indicator that the tram is malfunctioning and can be reset
- You're correctly told welder or multitool hints depending on if the tram is welded or emagged
- Don't bother running a tram malfunction if nobody is around
=> Tram spoiler/malf fix #88371

code/modules/religion/honorbound/honorbound_rites.dm
Tin, currently the rite checks for no DNA, which would be fine if we didn't have a race that's all about being a machine.
So I'd say we allow them to join said crusade, considering that if they themselves are the chaplain, they're able to be honorbound AND also start a crusade themselves.
**Also, please stop reporting weird inconsistencies and bugs inside the suggestions channel, thanks. There's a bug report channel that actually gets looked at by coders.**
Let synths get in on the action considering they're already fucked over enough as is.
It's a one-line change with an added species check, hard to fuck this up.
:cl:
qol: Synths can now join honorbound crusades.
/:cl:
=> [NON-MODULAR] Make Synths Able To Join Crusades

modular_zubbers/code/__DEFINES/bloodsucker_defines.dm
makes it easier for bloodsucker to level up, setting the percentage to 40% of blood volume
It's kind of really rough to level up as a bloodsucker, hopefully this helps
<details>
</details>
:cl:
balance: Bloodsuckers now only need 40% blood to level up.
/:cl:
=> buffs bloodsucker leveling

code/modules/projectiles/ammunition/ballistic/lmg.dm, modular_zubbers/code/modules/projectiles/projectile/bullets/lmg.dm, tgstation.dme
Buffs the L6 saw ~ 30 percent more damage
The l6 saw has always been left behind for a nukie weapon. This will help get it to a better state. 
- /obj/projectile/bullet/a7mm (normal ammo) 30 --> 39
- /obj/projectile/bullet/a7mm/ap (AP ammo) 25 --> 30
- /obj/projectile/bullet/incendiary/a7mm (Incendiary Ammo) 15 --> 20
- /obj/projectile/bullet/a7mm/bouncy (bouncy ammo) 20 --> 25
It compiles and works.
:cl:
balance: Increases the L6 Saw damage by around 30 percent
/:cl:
=> Buffs the L6 Saw

code/modules/loadout/loadout_menu.dm, modular_zubbers/master_files/code/modules/loadout/loadout_menu.dm
Okay, now this is actually a big issue, I may or may not have entirely forgot to check the clear loadout proc...
It wipes your entire loadout preference! AAAAAAAA!!!
Please merge before another unfortunate soul gets bluescreen'd or loses their whole loadout!
Loadout wipe bad!
<details>
Swap to another loadout to prove it didn't wipe everything
</details>
:cl:
fix: Using the clear loadout button should no longer brick your loadout data. Woops.
/:cl:
=> [FUCK] Unfucks Loadout Clearing

code/game/objects/structures/beds_chairs/sofa.dm
https://github.com/tgstation/tgstation/pull/87368
Fixes the error overlay when buckled to a bench!
Bug bad, fix good!
<details>
</details>
:cl: Profakos
fix: Benches no longer produce an Error overlay when buckled
/:cl:
=> [EARLY PULL] Fixes benches attempting to add a nonexisting armrest overlay (#87368)

code/modules/mob/living/carbon/carbon_defines.dm
Buffs cyborg health to match human health at 135 HP
They are a bit squishy, and while that was fine, the melee changes that slow down borgs got added. I think we should of put cyborg health on par with every other player.
It works.
:cl:
balance: Buffs cyborg health to 135
/:cl:
=> Buffs cyborg health to match human health (135)

modular_skyrat/modules/emote_panel/code/emote_panel.dm, modular_skyrat/modules/emotes/code/emotes.dm
Change key for huff emote from *huffs to *huff
*huffs breaks the pattern that every other emote uses and I thought it was a custom emote people were doing because of it
It compiles
:cl:
qol: *huffs has been changed to *huff.
/:cl:
=> Change huff emote from *huffs to *huff

_maps/map_files/moonstation/moonstation.dmm, modular_zubbers/code/game/area/areas/moonstation.dm
Adds disposal bins to Moon Station arrivals. Trash goes to a conveyor belt in the maint room, allowing ~~assistants~~ janitors to still filter it for ~~anything worth stealing~~ lost items before sending onwards.
It's hell trying to keep Moon Station arrivals clean as the hordes arrive and dump all their starting loadouts on the floor like wild animals.
<details>
https://github.com/user-attachments/assets/23650fd0-989f-4af9-b9e2-60aac46fc062
</details>
:cl: LT3
map: Moon Station now has disposal bins
/:cl:
=> Adds disposal bins to Moon Station arrivals

_maps/map_files/KiloStation/KiloStation.dmm
Adds a maint access requirement to the animal pen on kilostation, so the animals don't just wander out. Fixes a misconfigured package return belt in cargo on Kilo station.
The animals won't wander out, and the belt works properly now.
It compiles.
:cl:
fix: Added a maint access requirement to the animal pen on kilo, so the animals won't wander out.
fix: Fixed the misconfigured package return belt in cargo on Kilo station.
/:cl:
=> Kilo fixes

code/modules/modular_computers/file_system/programs/messenger/messenger_program.dm
Add a missing period to the PDA typing message.
:cl:
spellcheck: Added a missing period to the PDA typing message.
/:cl:
=> Add a missing period to PDA typing message

modular_zubbers/code/modules/antagonists/bloodsucker/clans/clan_nosferatu.dm
As title says, changes the description of nosferatu's examine to make it obvious they are in fact, a bloodsucker.
People tend to kind of ignore the nosferatu examine, either not understanding or simply willingly ignoring it, I'd like it to be a bit more obvious so it's super clear that this is in fact, a bloodsucker, a nosferatu who willingly gives up any pretense at hiding in return for their powers
Text/number changes, not tested
:cl:
add: Added new mechanics or gameplay changes
balance: Nosferatu when examined disgust you doubly as much.
add: Changes nosferatu examine to be more clear on what they are
/:cl:
=> Changes nosferatu examine message and doubles disgust gain per level

_maps/RandomRuins/IceRuins/bubberstation/icemoon_persistence.dmm, _maps/RandomRuins/LavaRuins/bubberstation/lavaland_persistence.dmm
Some more clean up items for persistence
Issues addressed
- Moved initial fish tank spawn over one engine slot in engineering to reduce accidental deaths via zappy eels
- Fixed some lights in places they should not be
- Removed collision on the sustenance vendor ~~How did no one notice it had it~~
- Hopefully fixed an issue with one turret not turning off
We like it when stuff works
Its just some map changes, I'll put something up if I don't forget to before its full merged.
<details>
</details>
:cl:
fix: Persistence Fish based power is now 100% more Osha compliant 
/:cl:
=> Some more clean up items that came up for persistence

_maps/map_files/BoxStation/BoxStation.dmm
This pull request changes a couple of things that needed to be patched since the major update to Box Station. Full changes are below in the changelog.
Rundown: 
Junction disposal pipe in sec maints correctly connects with disposals. Soda vendor in sec maints is gone. Apartment bolt buttons now bolt their respective airlocks. Wall connecting atmos to atmos maints now doesn't break ss13 mapping rules.
While this doesn't directly add features to the game, fixes to maps are important to improve roleplay and quality of the game.
it compiles it 
:cl:
map: Box Station's apartment airlock bolt buttons now work for their respective airlocks.
map: Box Station's disposal pipe in Security Maintenance correctly connects with disposals. 
map: Removed a soda vendor in Box Station's Security Maintenance. …
=> More QoL changes to Box Station

code/modules/client/preferences.dm, modular_skyrat/master_files/code/modules/client/preferences.dm, modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
Add the `visuals_only` argument to `safe_transfer_prefs_to_with_damage` so we can pass it down in the SAD call
Fixes #2273 
Tested it with a breathing tube implant I prommy
:cl:
fix: fixed SAD duplicating your round start implants.
/:cl:
=> Fix SAD duplicating loadout implants

modular_skyrat/modules/implants/code/augments_arms.dm
Mantis blades do very funny levels of damage considering that crew can get these
25 damage is literally as strong as a literal changeling armblade which is if you ask me, a *wee* bit too much, so this PR changes it to 20, which is combat knife levels of damage
The wound bonus also affects the energy mantis blades, but leaves the force otherwise unchanged.
Changeling armblade levels of damage that is nodrop is kinda nuts for crew to make.
Just a number's change
:cl:
balance: Mantis blades now do 20 damage, this is down from 25 force.
/:cl:
=> Nerfs mantis blades from 25 to 20

modular_skyrat/modules/ashwalkers/code/buildings/wormfarm.dm, modular_skyrat/modules/primitive_production/code/primitive.dm
fixes the exploit of farming primitive skill and makes the status effect tick way slower
exploits are bad, i guess, plus this is a 0.5S view call which is Not Good
<details>
</details>
:cl:
add: changes the primitive skill status effect to work every 5 seconds, instead of 0.5 seconds for performance reasons.
fix: It is no longer possible to farm primitive skill using a plant bag on a wormfarm barrel.
/:cl:
=> fixes the exploit of farming primitive skill and makes the status effect tick way slower

modular_skyrat/modules/primitive_production/code/primitive.dm
fixes primitive skill making you stamcrit immune
people abusing a exploit from id conflicts to become stamimmune is bad
<details>
</details>
:cl:
fix: Primitive skill no longer makes you stam immune
/:cl:
fixes #2666
=> fixes primitive skill making you stamcrit immune

_maps/RandomRuins/IceRuins/bubberstation/icemoon_persistence.dmm, _maps/RandomRuins/LavaRuins/bubberstation/lavaland_persistence.dmm, code/__DEFINES/preferences.dm, modular_skyrat/modules/simple_research/research_document.dm, modular_zubbers/code/modules/mob_spawn/ghost_roles/mining_roles.dm
Removes the research paper from everywhere and locks it only to the hermit.
This item was only specifically meant to go to the hermit. I defended it at first, but people are correct that prisoners shouldn't be building entire robotic factories and I think the age of easy alien tools in science should probally pass.
:cl:
balance: The research paper crafting recipe has been locked to the hermit.
/:cl:
=> Locks the research paper only to the hermit

modular_skyrat/modules/escape_menu/code/escape_menu_skyrat.dm
Escape menu has the opfor and ghost entries overlapping the entries TG added a while back, let's fix it.
Bug bad, fix good.
<details>
</details>
:cl:
fix: Fixed escape menu having overlapping entries.
/:cl:
=> Fix Escape Menu Overlapping

modular_skyrat/modules/opposing_force/code/mind.dm
Removes the ability for the ghost cafe to make opfors. The original intention behind this code was to stop ghosts from making opfors, and they all sort of shifted to going to the ghost cafe to circumvent that. It's obviously an oversite.
The senior admin team all sort of said this was fine and it's kind of an annoyance. The system is fine if you're in round asking to beat up the chef, but some people do seriously go to the ghost cafe and ask for ninja (or some other antag) every round and it's always kind of a repeating cycle with new faces doing it.
:cl:
del: Ghost Cafe can no longer make opfors.
/:cl:
=> Fixes an oversite that allows ghosts to make opfors.

modular_zubbers/code/modules/antagonists/bloodsucker/powers/targeted/mesmerize.dm
Mesmerize no longer requires you to face your target, I originally thought this was only required on the original cast, but this essentially makes normal mesmerize useless, as Dominate, tremere's version does not require this, but with this, you can simply look away and Mesmerize will fail
Mesmerize has been reworked heavily and this does not make sense to have anymore, I plan to rework the facing aspect to force you to watch the bloodsucker anyway, and this check is not needed til I add that
Not tested, variable change.
</details>
:cl:
balance: Mesmerize no longer requires your victim to be facing the bloodsucker.
/:cl:
=> Mesmerize no longer requires you to face your target

modular_skyrat/modules/marines/code/smartgun.dm, modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/romulus_technology/ammo/pistol.dm, modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/saibasan/projectiles.dm
Here's a funny thing I noticed with all our projectile falloff code. These numbers need to subtract instead of add.
What the sigma. 
It compiles.
:cl:
fix: Damage falloff across various projectiles should now subtract instead of add.
/:cl:
=> Fixes damage falloff across verious skyrat weapons

modular_zubbers/code/modules/storyteller/event_defines/ghostset/ghostset_overrides.dm, modular_zubbers/code/modules/storyteller/event_defines/moderate/moderate_overrides.dm, modular_zubbers/code/modules/storyteller/event_defines/mundane/mundane_overrides.dm, modular_zubbers/code/modules/storyteller/gamemode.dm
Puts holiday events in the storyteller event pool if it's the appropriate holiday
Currently storyteller just omits the event if it has a holiday assigned
<details>
</details>
:cl: LT3
fix: Santa will now periodically visit the station
/:cl:
=> Fix storyteller running holiday events

modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/bloodsucker.dm, modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/integration.dm, modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/life.dm, modular_zubbers/code/modules/antagonists/bloodsucker/bloodsuckers/procs.dm
Fixes bloodsuckers bleeding forever because the passive bloodloss healing code was not running. 
This also means that bloodloss will do some of it's effects on bloodsuckers
Fixes #2734
It's a meta check and just kind of annoying.
Went ingame, used adjustBleedStacks, saw that bleeding was slowly healed. Also tested that the procs that I moved around to HandleBlood signal also worked, frenzy and HandleStarving in fact, do
:cl:
fix: Bloodsuckers "should" no longer be forever bleeding
/:cl:
=> fixes bloodsuckers bleeding forever

modular_skyrat/modules/shotgunrebalance/code/shotgun.dm
- 5 pellets at a 15 varience spread (a little better then buckshot). This means that the spread will start to miss one or two entire pellets at 4-5 tiles. 
- 10 damage with a damage drop off of 1 per tile. (at five tiles, it'll be halved)
- Removed the AP and made it weak against armor.
- Base wounding is at 10 with a bonus wounding of 15 (25 total) and has a wounding dropoff of 3 per tile. 
Also the tile drop off for antitide and beehive now properly subtracts its damage instead of adding.
Flechett rounds are litterally the best shotgun ammo in the game. You don't need to use anything else. This is one shot on an elite suit.
They can be a great wounding ammo, but their damage should suffer when it begins to not be point blank and against armored targets.
I don't have specific videos but …
=> Flechett ammo rebalance.

modular_zubbers/code/game/machinery/flatpacker.dm, tgstation.dme
Fixes mail sorter name, adds spawn datum
:cl: LT3
fix: Mail sorter is now properly named in the CargoDrobe
/:cl:
=> Fix mail sorter name, add spawn

code/__DEFINES/~~bubber_defines/misc.dm, code/modules/antagonists/space_dragon/carp_rift.dm, code/modules/antagonists/space_dragon/space_dragon.dm, code/modules/movespeed/modifiers/mobs.dm
Dragons can now make a portal after 5 minutes after they loose their portal.
Currently dragon is forever slowed down and practically expected to die if they loose a single portal.
works, tested
:cl:
add: Dragons no longer permanently stuck unable to amke a portal if they loose one, now regaining the ability in 5 minutes
/:cl:
=> Dragons loosing a portal is no longer practically the end

modular_skyrat/modules/modular_items/code/summon_beacon.dm
Change gas miner beacons to be the kind that delete the delivery pod once they've landed
At ten thousand credits a piece you'd think NT would spring for the bluespace ones (the pod staying in the chamber is so ugly and I hate it)
<details>
</details>
:cl:
qol: gas miner delivery pods now delete themselves after landing.
/:cl:
=> Make gas miner beacons clean up after themselves

_maps/map_files/biodome/biodome.dmm
This PR fixes a few issues with the Blueshield Quarters on Biodome and adds a few more essentials for the room.
This fixes the access for the Blueshield Quarters airlock along with missing cable for the APC.
This also expands the room for the addition of a two computers. This also adds: A wall camera, holopad, request console, intercom, windows and curtains, fire door, and a newscaster.
It's usually good for an airlock for a restricted command area to not be accessible to assistants.
StrongDMM:
In a local:
:cl:
map: The Blueshield Quarters on Biodome is no longer free to access by anyone. It has also been expanded.
/:cl:
=> Biodome Blueshield Quarters fixes.

_maps/map_files/moonstation/moonstation.dmm
Removes a pair of sec vendors that escaped into Moonstation's primary hallway.
As funny as it is, the crew should not have readily available access to security gear.
:cl: LT3
map: Moonstation's escaped security vendors have been returned to where they belong
/:cl:
=> Remove sec vendors from Moonstation hallway

_maps/map_files/BoxStation/BoxStation.dmm
This PR makes it so the cells on Box Station properly function with their respective cells. Previously, the door timer on for Cell 1 would interact with Cell 3's windoor. This fixes that.
Brig cell timer should unlock and open their respective cells instead of other cells. Previously, this would be an issue in the case someone in Cell 3 would be let out early from Cell 1's timer ending. This fixes that.
Tested on my local. It werks.
:cl:
map: Box Station's brig cells properly work for their respective cells.
/:cl:
=> Fixes the brig cells on Box Station.

_maps/map_files/BoxStation/BoxStation.dmm
Change the jukebox in boxstation's bar to the `no_access` subtype so anyone can use it
It's in a public area not behind the counter, let people use it
Compiles
:cl:
map: Boxstation's bar jukebox is no longer access locked.
/:cl:
=> Make jukebox in boxstation bar all access

_maps/map_files/KiloStation/KiloStation.dmm
Kilostation's cold room has no freezer/HE setup and the turfs weren't the cold room type that start at -14c, this fixes the latter
It should be cold its a cold room!!!!!!!!!
:cl:
map: The kitchen cold room on Kilostation is actually cold now.
/:cl:
=> Make Kilostation's cold room actually cold

_maps/shuttles/skyrat/cargo_skyrat.dmm
As I have noticed and was told, Skyrat/Stellar Haven's old cargo shuttle uses conveyor IDs different from others: "cargoload" and "cargounload" instead of "QMLoad" and "QMLoad2". I have changed the shuttle's conveyor IDs to the usual QMs, to make it fully functionally compatible with maps in rotation.
It cuts down on needless labor of reinstalling the conveyor lines every shift start.
<details>
</details>
:cl:
fix: replaced a redundant var with actual
map: tweaked SR/SH cargo shuttle
/:cl:
=> Cargonstein; or, The Modern Shuttlefix

_maps/map_files/KiloStation/KiloStation.dmm
Add a gas sensor to the Kilo SM chamber and the map helpers necessary to connect it to the air alarm outside
Currently the air alarm gives you an atmos reading of the engine room itself not the chamber which is useless
<details>
</details>
:cl:
map: fixed Kilostation engine room air alarm not giving readings from inside the chamber.
/:cl:
=> Fix Kilostation supermatter air alarm not being linked to the chamber

modular_skyrat/master_files/code/modules/research/techweb/all_nodes.dm
Add the engineering plumbing constructor design to the chemical synthesis techweb node with the rest of the plumbing constructors because `/datum/techweb_node/plumbing` is not a real thing
Bug fix
<details>
</details>
:cl:
fix: fixed the engineering plumbing constructor not appearing in protolathes.
/:cl:
=> Fix Engineering plumbing constructor not being researchable

modular_skyrat/modules/synths/code/reagents/reagents.dm
In short this makes it so that system cleaner cleans alcohol out of one's system, much like a weaker antihol. So synths can be sobered up.
Getting too drunk as a synth is irksome, since they can't process antihol or water. Also gives more use to system cleaner besides just purging chems.
<details>
Before:
After:
</details>
:cl:
qol: System cleaner now sobers up synthetics.
/:cl:
=> System cleaner sobers up synths.

_maps/map_files/VoidRaptor/VoidRaptor.dmm
Add a growing vat to the Void Raptor cytology pen
It's like the main thing they need to do cytology and there isn't one
Compiled
:cl:
map: added a growing vat to Void Raptor's cytology pen.
/:cl:
=> Add a growing vat to Void Raptor cytology

modular_skyrat/modules/pollution/code/pollution.dm
Check for anosmia trait in `/datum/pollution/smell_act`
Anosmics shouldn't be smelling stuff!!
<details>
</details>
:cl:
fix: fixed mobs with anosmia still smelling pollution.
/:cl:
=> Fix people with anosmia smelling pollution

modular_skyrat/modules/customization/modules/language/te_velu_akko.dm
Because I forgot to do it during the Great Rewrite.
During the Great Akula Lore Rewrite I shortened almost everything Akula-related I could find, but I forgot to shorten the infamous and godsawful text for the sparkledog-sounding Akula language. This changes that.
It shortens that insane wall of text to be more in line with the majority of the language descriptions: short, sweet, and to the point.
:cl:
fix: Fixed the Akula language description to be of consistent length with the rest of the languages, instead of the wordwall it was.
/:cl:
=> Shortening That Godawful Akko Wordwall

_maps/map_files/VoidRaptor/VoidRaptor.dmm
Add a Cytopro to cytology in Void Raptor (this is my first PR on here if I fucked it up sorry)
parity with TG maps 
It compiled fine
<details>
</details>
:cl:
map: added Cytopro to Void Raptor's cytology.
/:cl:
=> Adds Cytopro to Void Raptor

code/__DEFINES/combat.dm, code/datums/actions/action.dm
SPEEDMERGE FROM UPSTREAM TG
This PR reduces the cooldown on selecting which spell to cast using hotkeys. This is because hotkeys have a different cooldown than using your mouse to click the icons. I do not think there should be a reason for using hotkeys to do the same thing as clicking to be clunky to the point shown in videos below.
Previous
https://github.com/user-attachments/assets/91814a17-c753-4c4b-b5cc-68e1be5528ac
Introduced here
https://github.com/user-attachments/assets/d9db3834-fc56-4a77-b4ef-4948c72b3334
Less clunky, easier to chain abilities. **It works on every single ui button, not just spells btw. So modsuit modules that require targetting, pretty much everything.**
(Huge thanks to ArturLang for the help with this)
:cl:
qol: Selecting which spells to cast with hotkeys, and …
=> Speedmerge of Upstream CD delay on all action buttons

_maps/map_files/moonstation/moonstation.dmm
Makes the jukebox in Moonstation's bar the all access subtype
The music must be democratized
It compile
:cl:
map: Moonstation's bar jukebox is no longer access locked.
/:cl:
=> Make moonstation jukebox all access

modular_skyrat/modules/bodyparts/code/roundstartslime_bodyparts.dm
Ditto as title, it's kind of *really strong* especially for bloodsuckers
50% damage resist vs a large majority of damage is horrifying
:cl:
balance: Roundstart slimepeople no longer get 50% burn damage type resist on limbs
/:cl:
=> Makes roundstart jellypeople not 50% resistant to burns

code/datums/actions/items/toggles.dm, code/modules/clothing/glasses/hud.dm, html/changelogs/AutoChangeLog-pr-88825.yml
Adds an action button allowing you to toggle on/off the HUD of wearables, like glasses.
https://github.com/user-attachments/assets/b95b85b7-2598-4bac-be2c-be86f9f90a95
Convenient method to temporarily disable the information for whatever reason.
=> Wearable HUD Toggle #88825

.github/workflows/compile_changelogs.yml
Pushes changelog compile up a bit to give some extra buffer, so that there's less risk of it crossing midnight.
=> Run changelog compile a bit earlier

.github/labeler.yml
Removes DME Edit autolabel. It doesn't add much beyond clutter, and a PR will fail linters if it has files missing from tgstation.dme
=> Remove DME Edit autolabel

modular_zubbers/code/modules/cargo/packs/service.dm
Exactly what it says on the tin. Currently if someone orders a jukebox for their project, it requires bar access to actually operate it. This change makes the crate come with the free access version.
Most if not all map-spawned jukeboxes don't have access requirements, because that makes them harder to actually use for entertaining people. Jukeboxes that people order for a side project shouldn't still need that access.
I forgot to record the testing, but I did test it and it worked fine. If video proof of testing a one-line change is needed, I can go back and do that.
:cl:
tweak: Ordered jukeboxes no longer only work for those with bar access.
/:cl:
=> Makes ordered jukeboxes not require bar access

_maps/map_files/biodome/biodome.dmm
Fixes some backwards elevator doors on Biodome. Adds wall to side of engineering elevator. Relocates medbay TC disposal.
</details>
:cl: LT3
map: Flipped some backwards elevator doors on Biodome
/:cl:
=> Fix Biodome elevators

code/controllers/subsystem/explosions.dm, code/modules/power/lighting/light.dm, modular_skyrat/modules/aesthetics/lights/code/lighting.dm, modular_skyrat/modules/decay_subsystem/code/decaySS.dm
Removes broken flickering lights
Lighting is another one of our massive memory usages. Let's remove this.
:cl:
del: Removes broken light flickering.
/:cl:
=> Memory 2.0: The flickering light removal

_maps/map_files/moonstation/moonstation.dmm
Adds five pieces of wood, a bucket, and a tinyfan to the Moonstation Sauna
Just a few tiny tweaks to moonstation so the sauna is slightly more accessable without needing to go too far out of the way.
Check map dif
:cl:
add: Quality Improvements to the Moonstation Sauna
/:cl:
=> Buffs ERP on Moonstation (Adds a bucket, five wood, and tinyfan to the Sauna)

_maps/map_files/biodome/biodome.dmm
Fixes the broken waste pipe, broken emitter cabling, and broken maint cabling around the SM/SMES in Biodome.
It was amusing watching it catch fire a few times, but it should be fixed.
:cl: LT3
map: Biodome SM waste pipe is properly connected to the vent
map: Biodome SM cabling is properly connected to the emitters
/:cl:
=> Fix Biodome's SM waste and cabling so engineers stop going crazy

modular_skyrat/modules/reagent_forging/code/crafting_bench_recipes.dm, modular_skyrat/modules/reagent_forging/code/forge_clothing.dm, modular_zubbers/code/modules/clothing/shoes/boots.dm, modular_zubbers/code/modules/loadout/categories/shoes.dm
Adds horseshoes as a loadout item. Same as the smithable ones except without any of the armor of reagent stuff.
Bounty by Gavla.
horseshoe
</details>
:cl:
add: Adds horseshoes to loadout
/:cl:
=> Horseshoes Loadout Item

_maps/map_files/biodome/biodome.dmm
Adds a couple missing cables under the floor tile to the Biodome gravity generator
<details>
Old:
</details>
:cl: LT3
map: Added missing cables outside Biodome grav gen
/:cl:
=> Fix wiring to Biodome grav gen

tgui/packages/tgui/interfaces/Orbit/JobIcon.tsx
Add a special case in `JobIcon.tsx` to point the DMIcon element to our modular icon file if it's a custom job.
little job pictures :)
<details>
</details>
:cl:
fix: fixed Bubber-exclusive job icons not showing in observe menu.
/:cl:
=> Fix bubber-exclusive jobs having no icon in observe menu

_maps/map_files/moonstation/moonstation.dmm
Removes this turret controller that controls the core turrets.
This also makes these walls into glass so the AI is better defended the moment someone enters this room and so you can't cheese it as easily
The turret controller being placed only for the AI's direct access is a deliberate mapping thing which holds true across all maps except Moon.
Also Moonstation's AI is very cheesable.
It works
:cl:
balance: Slightly adjusts Moonstation's AI core to be more defendable for the AI.
/:cl:
=> Modifies Moon's AI core to be less cheesable.

modular_zubbers/code/controllers/subsystem/job.dm, tgstation.dme
Changes the ingame chain_of_command variable used to determine who gets the safe code cookie to reflect our SOP (RD before CE, QM and NTC before HoS, include BS).
The safe code should be given to the person who our SOP indicates. When it goes to someone else, there's sometime arguments due to "CC just said I'm the acting" or whatnot. The NTC and Blueshield should also be able to get it if there's nobody higher than them in the chain on duty.
Can't easily test the reprioritization on private, since that requires two separate people readied up at the start of the round, but since the other change work it should too.
:cl:
fix: The Spare ID safe code should now go to the person designated in our SOP
/:cl:
=> Changes ingame chain_of_command to reflect our SOP

modular_skyrat/modules/verbs/code/subtle.dm
Removes the subtler range and allows you to subtler anyone in view. 
I noticed there was a TK exception that allows an increased subtler range, and I don't see the reason why we need to cap it only to just TK.
I tested it on the AI holopad and in person. It works.
:cl:
add: Uncaps subtler range. Now anyone can subtler anyone else in view.
/:cl:
=> Buffs ERP by uncapping Subtler Range

modular_skyrat/modules/interaction_menu/code/interaction_datum.dm, modular_skyrat/modules/verbs/code/subtle.dm
Makes lewd interactions subtle, instead of anti-ghost subtler. It doesn't broadcast target information anyway so it's honestly just doing it in a 1x1 square anyway.
Also to stop the dinging sound with any lewd interaction.
Ding ding ding ding. Also this was an oversight on my part.
Works
:cl:
fix: Lewd interactions broadcasting down the entire hall
/:cl:
=> Lewd Interactions are subtle, not subtler

modular_skyrat/modules/verbs/code/subtle.dm
Per the tin, it will remove clientless mobs from the subtle menu.
Clientless mobs can't hear your sex
Works
:cl:
fix: Subtler will now filter out clientless mobs
/:cl:
=> Subtler filters out clientless mobs

modular_skyrat/master_files/code/modules/clothing/clothing_variation_overrides/under.dm
Makes Pun Pun's suit sensors off by default
No rush between medical trying to turn them off and the bartender killing the monke
:cl: LT3
del: Pun Pun's suit sensors are off by default
/:cl:
=> Pun Pun suit sensors

tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
Adjusts the subtle/subtler message spans on dark mode from notice (darker) to say (lighter)
Feedback that notice class is too dark for long messages
:cl: LT3
qol: Subtle and subtler messages are brighter when using dark mode
/:cl:
=> Brighter dark mode subtle/subtler spans

code/modules/mob/dead/new_player/login.dm
quickly fixes https://github.com/Bubberstation/Bubberstation/pull/2910 which makes the softcap message appear when testing instead of disabling itself as expected
The repo's booting process already has a lot of runtimes and errors, I'd prefer not having to also deal with a popup each time I open it
It works
<details>
</details>
:cl:
fix: makes the softcap config disableable again
/:cl:
=> Makes the softcap message disableable again

modular_zubbers/code/modules/clothing/outfits/bunny.dm, modular_zubbers/code/modules/clothing/suits/jacket.dm, modular_zubbers/code/modules/vending/wardrobe.dm
removes wizard armor from wizdrobe
costumes should not have armor
nope
<details>
</details>
:cl:
del: no more wizard armor in wizdrobe, sorry, 
/:cl:
=> removes armor stats from the magician tailcoat in the costume drobe

code/modules/antagonists/heretic/knowledge/starting_lore.dm
Heretics who are synths no longer have to craft their living heart - making them not reliant on poppies to start antagging - **Putting them on an even playing field.**
The check for making hearts only apply to non-synths was making some people not have a good time, so I deletedi t
<details>
Heart very much beating
https://github.com/user-attachments/assets/409a913c-0a03-4e5a-aa5e-ea4e2882bd0c
</details>
:cl:
qol: Heretic Synths also start with a living heart
/:cl:
=> Synth Heretics Heart QOL

modular_skyrat/master_files/code/modules/clothing/under/jobs/rnd.dm
Roboticst -> roboticist
typo silly
compiled and spawned it and it was spelled right smiles
=> Fix typo in skyrat sleek roboticst jumpsuit name

modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
The original donator for whom this was a donator item for has requested that the taur cropping be removed for their naga character that it was designed for.  I looked into how to use the taur snake grouping to retain the cropping on other taur types, but was not able to figure it out.  If that is possible and preferred, it would be nice if someone could add it in a review as this change causes clipping with other taur species and this clothing item.  This is undesirable, even if this clothing item is rarely used.
Fixes #2931
<details>
Examples of it looking odd on other taur body types:
</details>
=> Remove taur cropping for short-sleeved kimono

modular_skyrat/modules/officestuff/code/officestuff.dm
Exactly what it says on the tin. Makes the soundloop for clocks not make noise through walls.
Constantly ticking clocks are an annoyance that can be hard to escape as command on certain maps like Moonstation. There's no reason that a wall thick enough to hold back vacuum should be letting a clock noise through it like nothing.
Can't really screenshot a sound, but I did test this on local and it works.
:cl:
fix: The ticking of clocks can no longer be heard through walls, filling the bridge with an incessant ticking noise like the Telltale heart's thumping.
/:cl:
=> Makes the clock sound not penetrate walls

code/modules/antagonists/heretic/knowledge/ash_lore.dm, code/modules/antagonists/heretic/knowledge/blade_lore.dm, code/modules/antagonists/heretic/knowledge/cosmic_lore.dm, code/modules/antagonists/heretic/knowledge/flesh_lore.dm, code/modules/antagonists/heretic/knowledge/general_side.dm, code/modules/antagonists/heretic/knowledge/lock_lore.dm, code/modules/antagonists/heretic/knowledge/moon_lore.dm, code/modules/antagonists/heretic/knowledge/rust_lore.dm, code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm, code/modules/antagonists/heretic/knowledge/void_lore.dm
Hello Chat. I have no idea how to test this on a private server, have no clue if we already had these protections and don't know if the freeze will even end in a month. What I DO know is that heretic has a lot of frustration with it and that I want to do my part! So let me first say, if the dorms and ssd part is unneeded/broken and a better coder says it's easier to keep the first part than fix my spaghetti, sure, I can just commit that out, we can go with just the easier rerolls.
Now let me argue my case:
Be a heretic. Roll 5 targets. Doesn't matter when. Someone's at the bar? Oh welp it's either convince them away, success, or fail at that and now you gotta stalk them out or just go guns blazing into 5 people. None of the 6 people over there want to go through all that trouble to do the …
=> [I think it works] Heretic reroll rite earlier, cheaper, Interlink and SSD protections to heretic targets!

modular_zubbers/code/modules/antagonists/pirate/pirate_event.dm, tgstation.dme
So it turns out that the list of possible pirates was only ever populated during the dynamic game mode procs to run the event, since we use story teller and not dynamic, that means the list was empty. Empty list means no pirates. This PR makes it so that if the list is empty (it is only ever populated when an admin uses the trigger-event verb to manually spawn pirates) it will use the combined global lists of heavy and light pirates, pick one, and fire it.
this antag been broke for like a year and 3 months
<details>
</details>
:cl:
fix: pirates spawn again
/:cl:
=> Fixes pirates round event so they spawn in story teller

code/modules/antagonists/heretic/knowledge/flesh_lore.dm
ditto to PR title
Flesh path is kind of really sad, and even on TG, flesh path struggles, as having so little HP means even one shot often crits you, let's give the heretic type that brings back dead people a good fair chance at doing it's thing.
<details>
</details>
:cl:
balance: Flesh ghouls now have 100 HP, while heretic mute ghouls have normal human HP, ie, 135, from 25 and 50
/:cl:
=> buffs flesh heretic ghouls to 100, and mute ghouls to 135

_maps/map_files/KiloStation/KiloStation.dmm, modular_zubbers/maps/kilostation/area.dm, tgstation.dme
Creates a proper area for the abandoned warehouse offstation on Kilostation, and provides an APC frame.
Engineering no longer keeps getting power alerts for a cargo warehouse they can't find, nor care about.
:cl: LT3
map: Kilostation abandoned warehouse now starts unpowered
/:cl:
=> Kilostation abandoned warehouse update

modular_zubbers/code/modules/languages/empathy.dm
Resolves [this issue](https://github.com/Bubberstation/Bubberstation/issues/2991). It should be noted that this fix should be mirrored to any other species with such unique organs, but I can not think of another.
:cl:
fix: Shadekins with the fluffy ears had the fluff trimmed, allowing them to hear the hive mind again
/:cl:
=> Trying to fix Issue #2991

modular_skyrat/modules/synths/code/bodyparts/power_cord.dm
Explicitly set the `slot` var for charging arm implants, the cause of the issue is an upstream issue that I've reported, but this will work in the meantime 
Fixes #2986 
<details>
</details>
:cl:
fix: synths once again start with a charging arm implant
/:cl:
=> Fix synths spawning without charging arm implant

code/controllers/subsystem/processing/quirks.dm, modular_zubbers/master_files/code/modules/entombed_quirk/code/entombed_mod.dm
Sets the fused MODsuit's defence values to be the same as the civilian suit, removes its free insulated gloves and makes it unable to be taken with Bad Back for the free +8 points. Additionally bumps the Mod Complexity of the Entombed suit to 13, it will functionally be 10 since the default storage module the entombed suits has consumes 3, and 10 complexity sets it in line with other suits.
The entombed quirk provides a comical amount of benefits for a so called neutral quirk, including an abusable interaction with the Bad Back Quirk that allows the player to ignore all the downsides of Bad Back and get a free +8 points as a result.
Works on literally everyone else's machine. Glory to Dream-Maker. Tested and maintainer approved.
<details>
</details> …
=> Nerfs Entombed

_maps/map_files/BoxStation/BoxStation.dmm
This update was held back in preparation for the addition of the Torment Nexus, but with that project on hold, this update will still be requested as it includes essential improvements to Box. Following feedback for Box Station, these changes include multiple fixes to multiple hallways and its light fixtures along with the extension of security's fore maintenance.
See the changelog for the full changes.
In addition to certain spots having their light fixtures modified/added to improve visibility in certain areas; The largest change this request brings is an APC is the primary hallway leading into the brig. Therefore the area no longer infinitely powered somehow.
tested on my local. it works. if mapping check issues arrive, I will fix it asap.
</details>
:cl:
map: In Box Station, a couple …
=> Mini fixes to Box Station

modular_skyrat/modules/customization/game/objects/items/tanks/n2_tanks.dm, modular_skyrat/modules/customization/modules/surgery/organs/vox.dm, modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm, modular_zubbers/code/datums/quirks/neutral_quirks/lungs.dm
First of the changes would be the fact that tank which voxes and people with nitrogen breathing quirk get is extremly big, and can store double the amount of any tank in the game and its a belt tank, which means can be stored in the pockets. This changes to initial value of 25 liters, to 12l which seems to be better alternative, and more fiting since the tank looks like double oxy tank, which can be crafter by engineering. 
To compensate the fact, that nitrogen breathers have to keep their internals on all the time, for close to 2:45 as our shifts tend to be, or their risk quick death. Their minimal gas intake value was changed from 10 to 4, which is the value that plasmaman need to stay alive and not choke to death. So it means that, they only need 4 kpa on their tank, to not take any …
=> Maintentance around nitrogen breathers

_maps/bubber/pods/shelter_4.dmm, _maps/bubber/pods/shelter_triage.dmm, _maps/bubber/pods/shelterxenoarch.dmm, modular_zubbers/code/modules/mining/equipment/survival_pod.dm
This PR aims to add two new pods along side adding two long existing pods to departmental orders.
The two new pods, both 3x3 deployables; One contains; a stasis bed, operating equipment for medical triage during dangerous situations. The xenoarcheology pod is available one; carrying a suite of tools for xenoarcheology and useful supplies for your expeditions.
I also applied a small fix to the large medical shelter, which actually makes the robotic repair medkit actually have supplies, I'm shocked no-one told me after this long!
Valued at 1,500cr the triage pod is also available on departmental orders, a useful thing to keep for breaches, fires and blob/xeno breakouts. The xenoarcheology pod is very useful; affordable (400cr) for scientists and a reliable way of getting started. Most …
=> Xenoarcheology and Triage pods

_maps/RandomRuins/IceRuins/bubberstation/icemoon_surface_gas_bubber.dmm, _maps/RandomRuins/LavaRuins/bubberstation/lavaland_surface_gas_bubber.dmm, code/game/objects/items/cards_ids.dm, modular_zubbers/code/game/objects/items/cards_ids.dm
The Lizard Gas Ghost roles use Omni pressure tanks, these are ass in game and don't have layers properly coded in. Also the loop is currently not hooked up. Also the Liquid plasma tank network has been changed to have an exterior store-house, because immediately upon people trying to fix atmos- sparks from the RPD caught the tank on fire and torched the entire backroom, maintenance room, and manager's office in a roaring plasma/trit fire 😔 
p.s the Lizard Gas I.D was added to a non-modular file on accident, this PR switches it to modular.
The mapsize was not altered to accommodate these changes overall and it remains a 25x25 Ghost Role ruin (as it's always been.)
TL;DR:
-Atmos Pipes are colored Red and Blue for Scrubbers and Air Supply, as God intended
-Exterior Scrubber added to suck …
=> Lizard Gas Atmos Fix/I.D transferred to Modular File

modular_zubbers/code/modules/hydroponics/code/grown/rocks.dm
When I changed it, so the joke in the names of "Agbergine" and "Aubergine" were better aligned with the materials, I forgot that sandfruits produced "Aubergine" seeds, which meant they completely skipped silver and shortened progression to diamonds.
Don't get to diamond seeds as quickly and silver seeds are actually accessible outside of xenobio silvers and seed mesh.
:cl:
fix: fixed seed pathing so silver's weren't skipped with the rockfruit mutations.
/:cl:
=> Fixes a seed path.

_maps/RandomRuins/IceRuins/bubberstation/icemoon_surface_gas_bubber.dmm, _maps/RandomRuins/LavaRuins/bubberstation/lavaland_surface_gas_bubber.dmm
Following an issue with Miners and other Lavaland/Icemoon roles ransacking the Gas station of its mats if no attendants spawn in, I've opted to add blastdoors/shutters, along with warning notes to IC'ly notify folk that this is a Ghost Role and should be left undisturbed. Said notes do not use OOC language in doing so, and simply inform the reader that "hey there are people cryosleeping inside, please dont rob this place"
Also I added some things I left out in the original overhaul by mistake
-Added Privacy Shutters to all exterior windows, controllable by a Button in the Break/Spawn Room
-Added Blast-Doors to all exterior Airlocks, controllable by a Button in the Break/Spawn Room
-Added 2x 'Veteran Lizard Gas Beret' to Locker, a Purple, renamed/desc'd Badged Beret
-Added 2x 'Lizard Gas …
=> Lizard Gas Update

_maps/map_files/BoxStation/BoxStation.dmm
Does as the title says.
It was unusable by anyone due to the way its access was set.
It was a simple map edit, it should work.
:cl:
map: modified the jukebox in BoxStation's permabrig to be accessless
/:cl:
=> Makes the jukebox in BoxStation perma accessless

modular_skyrat/modules/company_imports/code/armament_datums/deforest_medical.dm, modular_skyrat/modules/hyposprays/code/autolathe_designs.dm
This PR Readds the Advanced hypo in its already nerfed state to the ~~medical lathe~~ moved to imports and also readds the Large Hypobox that goes on your belt slot, the problem was already solved and i think its silly how you are forced to buy a whole tech kit JUST for the hypo as the PR which removed it from being printable did NOT add it into imports and locked it to said tech kit, its still locked behind research of course.
This stops Medical staff from being forced to fork out 2500 credits, or a 20 minute department order cooldown for a hypo upgrade on a tool that has already had the initial problem solved, ~~allowing for the progression/upgrade path to be returned.~~ This includes re-adding the large hypo box which was also removed.
Complies and works on localhost
:cl:
add: Readds …
=> Readds Advanced hypospray

modular_zubbers/code/modules/loadout/categories/neck.dm
(This is my very first PR. Do bear with me here.) 
This adds the three unique holobadge variants (Detective, Warden, HoS) to the loadout neck menu. Proper job whitelists and all
Badges cool, customization cool, what not to like?
:cl:
add:Added the unique variants of the Holobadge to the loadout neck section.
=> Adds the unique Holobadge variants to the loadout menu.

modular_zubbers/code/game/machinery/crew_monitor.dm
Changes the alarm logic to share the same for consideration if it beeps based on tg's logic for crew monitor entries.
consistency, people wouldn't beep on icebox but would on the same z as the console. 
<details>
</details>
:cl:
fix: crew monitor alarm logic is updated to work with planetary z's
/:cl:
=> Crew Monitor Console Alarm Logic change to TG's logic for determination if someone counts

modular_zubbers/code/modules/storyteller/storytellers/tellers/storyteller_6_house.dm
changes "The House now runs the show..." to "The House always wins."
it's ideal
<details>
</details>
:cl:
fix: changes The House's welcome text "The House now runs the show..." to "The House always wins." because it simply makes More Sense
/:cl:
=> changes "The House now runs the show..." to "The House always wins." because why

modular_skyrat/modules/deforest_medical_items/code/storage_items.dm
This PR adds the hypospray kit (box) to the list of allowed objects to the first responder surgical kit and orange satchel medical kit. There's been an inconsistency since the kit can fit in medical belts and medical technician bags; this allows the kit more options to be placed in.
While this gives the standard kit another option to be placed it, it still suffers the drawback of object interaction inside of a bag inside of a bag. Balance-wise, this is no different than a standard kit being placed and used within an internals box or smugglers satchel.
finally.
:cl:
add: Allows hypospray kits to fit in the first responder surgical kit and orange satchel medical kit.
/:cl:
=> Allows hypospray kits to fit in two more medical bags.

modular_skyrat/modules/deforest_medical_items/code/storage_items.dm
Does what the title says. It adds a single line of code.
For months, this bag was able to hold every surgical tool except for the blood filter. Now, the pink bag is no longer afraid of performing a hemodialysis.
:cl:
fix: Allows blood filters to fit in the medical technician bag.
/:cl:
=> Allows blood filters to fit in the medical technician bag

modular_skyrat/modules/hotel_rooms/apartment.dmm
I believe the original mappers have simply made a mistake by placing a bedsheet bin instead of a towel bin in the bathroom Also put a bedsheet bin in the bedroom, if anyone would ever need it for any reason. Anyways please speedmerge as this is crucial to server operations.
Spessmen no longer have to dry themselves off with bedsheets? Profit?
:cl:
map: changed the bedsheet bin in InfiDorm apartment map to a towel bin.
map: added a bedsheet bin in InfiDorm apartment map bedroom.
/:cl:
=> Changes the bedsheet bin in Infidorm apartment bathroom to a towel bin

modular_skyrat/modules/cryosleep/code/cryopod.dm
- Move cryo item storage behavior to separate proc cause it was getting big
- Don't store `DROPDEL` items (includes implants among other things)
- Empty out storage implants and attempt to store the contents instead of dumping on the floor
- Make the cryo pod angrily launch the nuke disk across the room if someone tries to cryo with it
Fixes #3111 
Imagine a picture of a cryo pod but with no random items dumped on the floor
:cl:
fix: fixed cryoing with a storage implant dumping the contents of said implant onto the floor
/:cl:
=> Fix cryo dumping storage implant items

modular_zubbers/code/game/objects/items/robot/items/storage.dm
Fixes #2992 
It gives them back the ability to grab parts and cells so to fix minor things such as APCs and machinery that has been destroyed. They are still unable to grab circuits and insert on the machinery however, without either the parts device or the circuit gripper upgrade.
It gives them back the ability to grab parts and cells so to fix minor things such as APCs and machinery that has been destroyed.
They are still unable to grab circuits and insert on the machinery however, without either the parts device or the circuit gripper upgrade.
They are also still unable to take the batteries out of chargers. Its a different issue.
https://github.com/user-attachments/assets/47a1c317-a30b-4830-bc82-2960a4c06e1d
</details>
:cl:
add: The ability to …
=> Add for engineering borg - Usage of gripper for stock parts and cells

modular_zubbers/code/datums/quirks/neutral_quirks/nameless.dm, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/bubbers/nameless.tsx
Adds the nameless quirk with the option to have a prefix. Without a prefix, you will spawn is as your [job] #[number]. If you don't have a job or prefix, you have some random prefixes I threw together that it chooses from.
Adds an option for characters to spawn in as a random number. Adds to the bubber roleplay experience. You can be mass produced or something.
:cl:
add: Nameless Quirk
/:cl:
=> nameless quirk

modular_skyrat/modules/modular_items/lewd_items/code/lewd_items/size_items.dm
This makes the size collar item from the lustwish vendor modify Teshari & Vox Primalis size (Both of which have bodysize restrictions). It has the same restriction as before (infinidorms/interlink areas) and does NOT affect NIF Polymorph or the Character Creation bodysize slider.
More ERP options regarding size stuff for birds. It's unlinked to the main course of the game and shouldn't affect that - teshari and vox primalis deserve to be the big bird (or small bird) for scenes in areas where it can't get them an advantage (the size collar only works in dorms areas.
Compiled and tested on a localhost, large bird image provided below
<details>
</details>
:cl:
code: Teshari and Vox primalis can now use size collars in dorms/interlink areas.
/:cl:
=> Allows the size collar to work for teshari and vox primalis

modular_skyrat/master_files/code/datums/components/damage_tracker.dm
Add code to `/datum/component/damage_tracker/human` to keep track of wounds and reapply them as needed.
Fixes #3162
I tested with both the permanent limp quirk and breaking one of my arms with force and both wounds stayed after using the SAD
:cl:
fix: fixed the SAD deleting wounds
/:cl:
=> Fix SAD not transferring wounds

modular_skyrat/modules/verbs/code/looc.dm
Makes admins who are ghosted show by their ckey when they LOOC instead of their character name.
Makes it more clear if an admin is LOOCing to you in game if it's needed
:cl:
admin: ghosted admins who LOOC now show by their ckey
/:cl:
=> Admins show ckey on LOOC when they're ghosted 

code/modules/mob/living/living_defense.dm, modular_skyrat/modules/indicators/code/combat_indicator.dm
CI should only work while the mob has an active client
Due to how basic AI works, it also flashes CI. This is stupid. Let's be less stupid.
It works
:cl:
del: Clientless mobs should no longer flash CI.
/:cl:
=> Makes CI require a client to activate

modular_skyrat/modules/cryosleep/code/cryopod.dm
Uses `mob_occupant.get_equipped_items()` instead of `mob_occupant.contents`. This results in skipping 
Also, abstract items will not be stored, similar to how `DROPDEL` items aren't stored.
~~Currently untested, but it will at least solve the linked issue, assuming it doesn't introduce any new ones.~~
I tested it, works fine.
Fixes https://github.com/SPLURT-Station/S.P.L.U.R.T-tg/issues/158.
<details>
</details>
:cl:
fix: fixed cryopods dropping prosthetic bodyparts of despawned mobs
/:cl:
=> Fix cryopods dropping prosthetic bodyparts

modular_zubbers/code/modules/storyteller/event_defines/crewset/malf.dm
Reduces the weight of round-start MALF from 10 to 2.
I was told that MALF "rolls every round" so I went to investigate and discovered that roundstart malf has a weight of 10. For reference, heretic has a weight of 3. Traitors have a weight of 16. Changeling has a weight of 8. 10 is really common compared to the rest of things that can roll.
MALF shouldn't be more common than Changeling or Heretic, especially considering that malf ai is an extremely destructive antag type.
:cl: BurgerBB
del: Reduces the weight of round-start malf ai from 10 to 2.
/:cl:
=> Reduces the weight of round-start malf ai from 10 to 2.

modular_zubbers/code/modules/surgery/organs/internal/eyes/_eyes.dm
Makes it so shadekin no longer blink, most other species that have special eyes don't currently blink (moths, slimepeople), this brings them in line with the others.
Currently when they blink they have a little error icon, this fixes that.
fixes #3203
It was a two line change, it SHOULD work.
:cl:
fix: shadekin no longer blink
/:cl:
=> Fixes shadekin blinking

code/controllers/subsystem/statpanel.dm
Removes the 516 beta warning, since we now require 516.
<details>
</details>
=> Remove 516 beta message

modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/defender.dm, modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/drone.dm, modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/praetorian.dm, modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/queen.dm, modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/ravager.dm, modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/rouny.dm, modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/sentinel.dm, modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/spitter.dm, modular_skyrat/modules/xenos_skyrat_redo/code/xeno_types/warrior.dm
Replaces create_internal_organs with default_organ_types_by_slot bringing Skyrat xenos in line with /tg/ and fixing them in the process.
Xenos are once again able to xeno.
It compiled, ran, and worked.
:cl:
fix: fixed xenos lacking their abilities
/:cl:
=> Fixes xenos lacking their abilities

code/modules/mob/living/carbon/human/human_update_icons.dm
Closes https://github.com/Bubberstation/Bubberstation/issues/3250
Title. Cropping works ALMOST as intended now, with the downside that underwear renders over your mod for wahtever reason. I dont know how to fix this. I am not a good render-coder.
bugs bad
<details>
</details>
:cl:
fix: Taur clothing rendering is mostly functional
/:cl:
=> Partially fixes taur clothing

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage/hemophage_tumor.dm
Remove a `!.` check in `on_mob_insert` because organ refactoring means it'll always fail now (parent proc no longer returns anything)
Fixes #3214 (I cannot reproduce the part about missing the drink ability, it's most likely a separate issue so I'll wait for a new report on it if it persists)
<details>
</details>
:cl:
fix: fixed hemophages missing their blood meter
/:cl:
=> Fix hemophages not having blood meter

modular_skyrat/master_files/code/datums/components/prone_mob.dm
What it means is that there shouldn't be any more sprite stuttering* when crawling under racks or tables due to the elevation elements attached to them.
*Under normal cirumstances, it should be offset vertically but for some reason the offset is reset, perhaps from some of your modular changes, leaving only the animation in.
Fixing a nominal issue.
It works for xeno larvas upstream. It'll work here as well.
:cl:
fix: You no longer jitter when crawling under tables and the likes as a borer or from of army crawling.
/:cl:
=> being prone (army crawling, borers) now adds the TRAIT_IGNORE_ELEVATION trait

tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/loadout/index.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/index.tsx
slightly increase the height of the character panel and fix create loadout button
char creator UI kinda requires you to scroll to see your name and stuff, this fixes that, and the add loadout button didn't work, broken shit working is better, i'd say
i tested it, no pic, sorry
:cl:
fix: Character setup panel is now slightly bigger
fix: Character setup panel's add loadout button now works again
/:cl:
=> slightly increase the height of the character panel and fix create loadout button

modular_skyrat/modules/pixel_shift/code/pixel_shift_component.dm
When I was reworking the pixel shift component to accommodate upstream changes to mob pixel offset behavior I changed it to track offset in the component instead of reading pixel x/y directly, but forgot to remove the calculations that take the base pixel x/y into account, which would no longer be needed
Fixes #3341 
<details>
</details>
:cl:
fix: fixed larger sprite size mobs being unable to pixel shift properly
/:cl:
=> Fix incorrect pixel shift behavior for mobs with nonzero base pixel x/y

modular_zubbers/code/modules/mob/living/carbon/human/species/akula.dm
Does as the title says.
https://github.com/user-attachments/assets/43dbe941-d8f1-4b9d-a845-4a152076a5e3
It's funny and adds a bit more soul to the akula tongue.
It compiled and ran, see the above video for proof.
:cl:
add: akula tongues now have the fish chat bubble effect tied to them
/:cl:
=> Adds the fish infusion chat bubble to the akula tongue

modular_skyrat/modules/synths/code/species/synthetic.dm
so there was a typo
Fixes #3284 and fixes #3198
<details>
</details>
:cl:
fix: fixed synth chassis taking their color from the head
/:cl:
=> Fix synth chassis taking color from head

_maps/map_files/BoxStation/BoxStation.dmm
This PR brings mapping additions from upstream to box station. New features include: the Captain-Cast in the captain's office, feature sheers in genetics, and wall fish display in the bar. Some fixes are: More reinforced iron walls to match IceBox's cells, misplaced floor decals in the firing range, redsec pauldrons in security lockers removed (Since they can be found in the secdrobe vendor anyways) hanging cobwebs from after Wallening. 
This also re-adds maints access to airlocks that exit to space. Turns out scared mice in maints run into space if they wanted to.
This also adds a pipe in Atmos that fully connects a mix pipe to the SM, if someone wanted to do that. Don't know how I never spotted this. Someone else did.
New features are good, which is why we should stick with being …
=> Adds Captain-Cast (and more features and fixes) to Box Station

config/bubbers/bubbers_config.txt, config/bubbers/storyteller.txt, config/config.txt, modular_zubbers/code/modules/storyteller/config.dm
I guess the latest upstream nuked the configs from the repo and the default code values never worked. So storyteller just went uncapped and wild on downstreams. 
We have the configs still on the server itself, so it didn't effect us. Storyteller did not break or change.
:cl:
config: Storyteller default configs now exist and should work again
/:cl:
=> Fixes the storyteller default configs

modular_skyrat/master_files/code/modules/language/language_holder.dm
Adds Marish, Chitinclick and Carptongue to known languages for borgs and AI
Adds Marish ( the shadekin Mar language) and Chitinclick to known languages for silicons because shadekin and bug people are often workers on NT stations and I dont see why NT would not provide the ability for silicons to understand and communicate with these crew.
Adds Carptongue for the same reason that silicons know how to speak with monkeys and slimes.
It compiles and was tested locally.
<details>
</details>
:cl:
add: Adds Marish, Chitinclick and Carptongue to Silicon's Known languages
/:cl:
=> Adds Marish, Chitinclick and Carptongue to Silicon's Known languages

modular_zubbers/code/modules/research/designs/medical_designs.dm, modular_zubbers/code/modules/research/techweb/all_nodes.dm
This removes the handheld crew monitor from the medical lathe.
Alright, I just want to start out with all sources of the handheld crew monitor after this PR
- Paramedics spawn with them
- Blueshield (command only)
- The medical vendor premium section.
- Borg upgrades
Overall while there's been a lot of QOL to the crew monitor which I enjoy, it's all gradually made it so deaths are very noticable and often times with someone in medical 1 second later running towards an active fight to drag corpses away. 
- I think overall we have a sort of medical omnipresence issue, especially with an easy research destroying a level of scarcity with the hand held crew monitor. 
Anyone can print it if they have the materials and access to the lathe versus only a few existing outside of the paramedic …
=> Reverts "Adds crew monitors to Advanced biotech and lathes"

modular_zubbers/code/modules/emotes/emotes.dm
Silicons can now emit a singular yip so they can express their inner kobold but not too much.
Silicons can yipyip but not yip. This fixes it.
It compiles and was tested locally.
</details>
:cl:
fix: Silicons can now yip. 
/:cl:
=> Silicons can now Yip

code/modules/shuttle/mobile_port/variants/emergency/emergency.dm, modular_skyrat/modules/autotransfer/code/shuttle.dm, modular_zubbers/code/controllers/subsystem/security_level.dm, modular_zubbers/code/modules/shuttle/emergency.dm, tgstation.dme
Triggers the automatic map vote when the round is about to end due to a station threat, if it hasn't happened.
Saves it delaying the next round if no admin catches it in time, causing a delay as the vote and another restart needs to occur.
:cl: LT3
admin: Map vote is automatically triggered near the conclusion of station ending threats
fix: Only a single announcement is sent when the shuttle is called, fixing the overlapping sounds
/:cl:
=> Map vote is called automatically on blob/nukies/etc. round end

modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/carwo_defense_systems/magazines.dm, modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/romulus_technology/magazines.dm, modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/szot_dynamica/magazines.dm, modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/trappiste_fabriek/magazines.dm
Puts the Sol/Carwo/Romulus/Szot/Trappiste gun magazine sizes in line with /tg/ standards (tiny for everything but rifles which are normal)
Size inconsistencies between items results in confused players; it's good to keep this sort of thing synced up so that we're not having players ask why one pistol magazine fits in a box while another pistol magazine doesn't fit in a box when the air tank that's bigger than both of them does fit in the box.
If I find other guns with weird weight classes I'll fix those too.
Single-line changes, weight classes is a proven working system already.
:cl:
qol: Puts the Sol/Carwo/Romulus/Szot/Trappiste gun magazine weight classes in line with /tg/ standards for magazine weight classes (tiny for everything but rifles or larger which are normal)
/:cl:
=> [MODULAR] Puts the Sol/Carwo/Romulus/Szot/Trappiste gun magazine sizes in line with /tg/ standards (tiny for everything but rifles which are normal)

code/modules/mob/living/carbon/emote.dm, modular_skyrat/modules/emotes/code/emotes.dm
Fixes the meow emote to use the correct emote if you have a cat tongue
MEOW.
:cl: LT3
fix: Mobs with cat tongue get their alternate meow sound back
/:cl:
=> Fix meow emote for cat tongues

code/controllers/subsystem/vote.dm
There's a redundant override in `vote.dm` to enclose the vote results in a purple examine box, this is the default way votes are displayed now so it's making vote results appear as a box within a box
Looks wrong
<details>
Before:
After:
</details>
:cl:
fix: fixed vote results in chat having an extra box around them
/:cl:
=> Fix double box on vote results chat message

_maps/map_files/KiloStation/KiloStation.dmm
Makes sure Kilo Station's dorms area actually is a Dorms area.
Other stations' dorms are inside actual Dorms areas, effectively granting protection from events like sudden brain trauma/heart attack, but Kilo Station didn't have this, they were classified as lockers instead.
<details>
</details>
:cl:Goku
map: Kilo Station's Dormitories area type is now classified as dormitories, not as a Locker room.
/:cl:
=> [MAPPING]: Change Kilo Station dorms area type from Locker to Dorms.

modular_zubbers/code/modules/storyteller/scheduled_event.dm
The chat messages that get sent when a storyteller event is about to run try to call `Topic` on the scheduled event datum but there isn't actually a `Topic` proc defined for them
It's mean to trick admins with fake buttons
<details>
</details>
:cl:
admin: the cancel and refund buttons in storyteller event notifications will actually do something now
/:cl:
=> Fix admin chat buttons to cancel/refund storyteller events not working

modular_skyrat/modules/modular_items/code/bags.dm
Adds hypospray and cable to the allowed list of items in the medical pouch
Commonly held items, other reagent containers are accepted but hypo is missing.
:cl: LT3
qol: The medical pouch can now hold hyposprays and cable coil
/:cl:
=> Allow hypospray in medical pouch

modular_skyrat/modules/xenoarch/code/modules/research/xenoarch/xenoarch_machine.dm
Clean up the code for xenoarch machines some because it made me sad. 
- Changes `attackby`'s to `item_interaction`
- Keep a list of xenoarch items in contents instead of storing them in **an instance of `/obj/item` (yes the abstract concept of an item)**
- Add context tips for all item interactions and removes that info from examine text
- Switched a list to `static`
- Add assoc list of `broken_item` types to reward pools instead of having a nightmare ladder of `istype` checks
Fixes #3442 
Scout's honor
:cl:
qol: xenoarch machines have context tooltips now
fix: fixed xenoarch diggers not working
/:cl:
=> Xenoarch machines cleanup

modular_zubbers/code/game/machinery/burger_reactor/reactor.dm, tgui/packages/tgui/interfaces/RBMK2.tsx
A significant [rework of the RB-MK2 GUI](https://github.com/NovaSector/NovaSector/pull/5136) that I did over on Nova. The one you guys have now is painful to use in comparison so let's get it up to snuff.
More information makes the RB-MK2 easier to use and teach in character. With how the GUI is currently, it gives no intuitive explanation for what it's doing. You can't tell what's going on with it.
<details>
https://github.com/user-attachments/assets/7a178ac2-df8e-40d3-a6f3-b6aa617b69fd
</details>
:cl: Chestlet
admin: Improved RB-MK2 logging so admins have a full trace of exactly what happened with it.
fix: Corrected 'tritium usage' math in the RB-MK2.
code: We've noticed that the Radioscopical Bluespace Reactor Mark Two blueprints provided to our …
=> Nova Port: RB-MK2 GUI Rework (#5136)

code/game/objects/structures/crates_lockers/closets/secure/engineering.dm, code/modules/jobs/job_types/chief_engineer.dm, code/modules/jobs/job_types/station_engineer.dm, code/modules/vending/engivend.dm, modular_skyrat/modules/modular_vending/code/engivend.dm
moves RCD's from engineers backpacks to their lockers roundstart - to accommodate the stowaway change aswell as keep a tab on infinite station resources. 
Above point
<details>
</details>
:cl:
balance: reenabled the RCD vendors and moved RCD's from spawning in backpacks to lockers. 
/:cl:
=> restores RCD vending, moves RCD's to lockers

modular_skyrat/modules/xenoarch/code/modules/research/xenoarch/designs_and_tech.dm, modular_skyrat/modules/xenoarch/code/modules/research/xenoarch/xenoarch_item.dm, modular_skyrat/modules/xenoarch/code/modules/research/xenoarch/xenoarch_machine.dm, modular_skyrat/modules/xenoarch/code/modules/research/xenoarch/xenoarch_tool.dm
A little treat for xenoarch
- The xenoarch bag can now hold broken items and useless relics in addition to strange rocks
- You can use the bag on both the researcher and the recoverer to dump the contents in
- The digger and the researcher make a sound now
A bag that holds only one type of item is annoying, you get a lot of the other two items too
<details>
</details>
:cl:
qol: the xenoarch bag can now hold broken items and useless relics
qol: you can use the bag on the researcher and the recoverer to dump items in
sound: the digger and researcher now make a sound when they complete a cycle
/:cl:
=> Xenoarch Machine QOL

code/modules/mob/living/basic/vermin/frog.dm
Revert a skyrat edit that changed frogs `attack_sound` and `stepped_sound` to null
This is a very specific change that I don't really see a point in, the sounds aren't terrible and the shitty way this was coded means now we get runtimes (causing flaky CI) whenever it tries to play one of their sounds because you can't pass null to `playsound`
If it compiles it works
:cl:
sound: frogs make sounds again
/:cl:
=> Restore frog mob sounds

code/game/objects/items/surgery_tray.dm
Fixes a merge conflict error in the upstream, trying to populate the surgery tray with more items than the storage capacity.
:cl: LT3
fix: Surgery tray has the correct starting items
/:cl:
=> Fixes surgery tray starting items

modular_zubbers/code/modules/vending/multisec.dm
Removes the insane metrocop armor from vendors. This not only has full protection unlike standard armor, but it also has a riot varient. Why can you buy full prot armor (defeats the point of swat armor) and riot armor (that should be in armory only) from a clothing vendor that's in every outpost???
I didn't. It's removing two lines from a vendor.
<details>
</details>
:cl: UvvU
del: Removed metro cop armor from the sec vendors
/:cl:
=> S.W.A.T part 2

modular_skyrat/modules/aesthetics/storage/storage.dm
Removes the skyrat override for emergency medkit sprite
The skyrat sprite is so out of sync with other medkits that its hard to tell its supposed to be a medkit. Doing this makes it look like the other medkits and be easier to pick out from lockers since its red and stuff.
No
:cl:
image: removes the sprite override for emergency medkits
/:cl:
=> remove the skyrat emergency medkit sprite override

modular_zubbers/code/modules/jobs/job_types/blacksmith.dm
Makes the blacksmith suffer less by giving them a bunch of wood in their backpack
Lets you get forging right away without having to steal wood from chapel or wait for cargo/botany
also the apron makes sense and lets you put your hammer in there or whatever
I didnt test it
:cl:
add: blacksmith starts out with wood and a leather apron
/:cl:
=> give blacksmith wood and apron

modular_skyrat/modules/sec_haul/code/misc/gun_redemption.dm, modular_zubbers/code/modules/syndicate_offstation/selection_beacons/weapon_redemption.dm
Weapon beacons had bad grammar in the headset message. This fixes that.
better :)
no
:cl:
spellcheck: The headset message from weapon beacons have been changed to have better grammar.
/:cl:
=> Grammar fix for weapon beacons

tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/MainPage.tsx
Add the `backwards` param to the `handleRotate` function in the main character prefs page
Fixes #3553 
<details>
</details>
:cl:
fix: fixed both rotate buttons in character prefs rotating in the same direction
/:cl:
=> Fix rotate buttons in character tab rotating in same direction

modular_skyrat/modules/GAGS/greyscale_configs.dm
Remove the word `digi` that is just sitting in a random code file from years ago and also counts as a type declaration for some reason
Digi
Digi
No
=> Remove the random "digi" from greyscale_configs.dm

_maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/VoidRaptor/VoidRaptor.dmm, _maps/map_files/biodome/biodome.dmm, _maps/map_files/moonstation/moonstation.dmm, modular_skyrat/master_files/code/modules/research/techweb/all_nodes.dm, modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
As per adding the SAD to be roundstart available as per admin request, eliminates the research requirement to build new ones. Places a SAD on the Bubberstation specific maps. Updates the logging to properly log instead of spitting into the admin chat.
Now everyone is free to be SAD, anytime, anywhere.
<details>
</details>
:cl: LT3
balance: SAD is now available to be built roundstart
map: Added roundstart SAD to Bubberstation maps
/:cl:
=> Self-Actualization Device is available without research

code/__DEFINES/~skyrat_defines/_HELPERS/lighting.dm
Change `pixel_x` and `pixel_y` to `pixel_w` and `pixel_z` in the helper function to create an emissive overlay
Fixes #3538 
<details>
</details>
:cl:
fix: fixed emissive overlays on body parts being offset
/:cl:
=> Fix bodypart emissives being incorrectly offset

modular_skyrat/modules/shotgunrebalance/code/shotgun.dm
Fixes windoors being immune to the destructive effects of frangible slugs.
Bugfix :)
I had fun on icebox destroying the armory windoors. It works.
<details>
</details>
:cl: UvvU
fix: Windoors are no longer immune to frangible slugs effects.
/:cl:
=> Fixes a oversight with frangible slugs.

modular_skyrat/modules/cargo_teleporter/code/cargo_teleporter.dm
Move the handling for removing cargo teleporter destinations from the mark to the teleporter itself
Fixes #3564 
<details>
</details>
:cl:
fix: removing cargo teleporter destinations by clicking on them should work again
/:cl:
=> Fix being unable to remove cargo teleporter marks

code/modules/mob/living/carbon/human/human_update_icons.dm, modular_skyrat/modules/taur_mechanics/code/taur_clothing_offset.dm
update a `pixel_y` to `pixel_z` and move a bit of code higher up in a proc call and switch which mutable appearance it works on, because upstream added another step in clothing overlay drawing
Fixes #3563 
<details>
</details>
:cl:
fix: taur clothing should now draw on the body properly
/:cl:
=> Fix taur clothing being broken

modular_zubbers/code/modules/storyteller/storytellers/tellers/storyteller_3_default.dm
Default Andy seems to be a little bit high on the high-impact events towards the end of the round, so I want to try temporarily setting TAG_CHAOTIC to 0.8 rather than 1.0, which should have a noticeable impact on them on this storyteller.
This should reduce the weight of chaotic rulesets by about 20%, I'm curious to see what effect this will have on default Andy shifts. Right now, all the low-impact storytellers are at 0.1, whereas the Default is at 1.0, and the Gamer is at 1.3. There isn't much of a midpoint, Default Andy feels a lot stronger than the low impact rulesets.
This is good for the game because it makes Default Andy feel closer to a midpoint between low and high impact shifts with regards to round-ending events, rather than the 3/4 it currently is.
Can't compile on 516, but it …
=> Adjusts Default Andy's chaotic tag multiplier to 0.7

modular_zubbers/code/controllers/subsystem/vote.dm, modular_zubbers/code/modules/storyteller/event_defines/crewset/_antagonist_event.dm, modular_zubbers/code/modules/storyteller/event_defines/crewset/malf.dm, modular_zubbers/code/modules/storyteller/gamemode.dm
- Improves formatting of the storyteller description broadcast, using the vote span.
- Don't announce roundstart storyteller rule purchases.
:cl: LT3
code: Improved storyteller vote formatting
code: Storyteller doesn't announce the roundstart event purchase
/:cl:
=> Storyteller message formatting

code/modules/mob/living/silicon/robot/robot_defense.dm
Fixes a reversion from fca806da0c5ed9fb6889d7611eba4c5b7476e12b, which removed the balloon alert.
*beep :]
*no :[
:cl:
fix: Cyborgs once more get an alert if their cover is being pried open.
/:cl:
=> Borgs now get alerted that someone's prying their cover

modular_zubbers/code/modules/storyteller/divergency_report.dm
This PR changes the number of station goals selected to be random, weighted towards zero. There's still a chance that more, or all three, are selected, albeit much rarer.
In the original port of the storyteller system, the divergency report would always roll for station goals with a budget of 20. While this might otherwise fine, all three current goals (BSA, DNA Vault, Meteor Shields) each had a cost of 1, meaning all three rolled every single round.
This changes the budget to be weighted with the following weights:
```
0 Goals - 65%
1 Goal  - 20%
2 Goals - 10%
3 Goals -  5%
```
Numbers subject to change.
Having all three goals roll every single round has been a point of contention (especially amongst Engineering players), and having them be rarer means that they're more interesting when …
=> Weighted number of station goals

code/game/objects/items/rcd/RLD.dm, modular_zubbers/code/modules/research/designs/mechfab_designs.dm, modular_zubbers/code/modules/research/techweb/all_nodes.dm, modular_zubbers/code/modules/silicons/borgs/code/robot_upgrade.dm
Adds an RLD to the cyborg engineering upgrades, in the same techweb. No longer shall man live in darkness.
PLEASE I DONT NEED TO SPEND 6000 YEARS MAKING LIGHTS!! 
I want FLOORLIGHTS, I want CHEMLIGHTS, let me SEE!!
<details>
</details>
:cl:
add: With a new upgrade, Borgs get an RLD. Let there be light.
/:cl:
=> Adds an RLD upgrade to engineering borgs

modular_zubbers/code/modules/arcades/code/minesweeper/minesweeper.dm
`ui_act` for minesweeper was using args that weren't correct so it was taking the ui it was passed and treating it like a mob which makes it very unhappy, fixed the args and got the mob another way
Fixes #3588 
<details>
</details>
:cl:
fix: gamers rejoice, minesweeper works again
/:cl:
=> Fix Minesweeper

modular_zubbers/code/modules/storyteller/event_defines/crewset/heretic.dm
This PR brings the value of players necessary for the game to consider spawning heretics down to 35, which is 5 more than bloodsuckers. 
A foreword, this is a mechanical PR. The heretic was taken out behind the shed due to what I assume were oppressive mechanics and roundending, so a fair portion of this explanation will be defending said mechanics and disproving the notion that heretics are the worst thing since the bread unslicer machine of 1791- Roleplay is an individual matter of players and every player has a choice to make, the heretic uses standard RP escalation.
Let's begin. Heretic as is right now, is a non-existant antagonist. They are technically ingame, and technically you can roll it, but the pop requirement is almost TWICE the size of any other antagonist or dangerous event. …
=> Heretic spawn changes, minimum pop 50 -> 35

modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
`req_components` needs to be an empty list, not null, otherwise it doesn't call parent and the circuitboard doesn't get added to `component_parts`. Also removed the extra (Machine Board) in the name
Fixes #3602 
I didddd
:cl:
fix: fixed SADs spitting out a circuit board when you open them
/:cl:
=> Fix SAD throwing up circuit board

modular_skyrat/modules/modular_implants/code/nif_persistence.dm, modular_skyrat/modules/modular_persistence/code/modular_persistence.dm
`modular_persistence.json` on player saves holds the path of any NIFs they have installed and ended the round with, but when we refactored `/obj/item/organ/internal` to just be `/obj/item/organ` these save files weren't updated, meaning people lost their NIFs and now we get runtime errors when an affected person joins the game. This code will check their save on load and update the path appropriately (which will then be written to the file at round end)
They lost NIFs due to a bug
I can't really do pictures for this but I got a save file that had invalid NIFs installed and used it to test locally and it worked, also tested save files without NIFs and clients that don't have a `modular_persistence.json` at all, no runtimes
:cl:
fix: characters who had their NIFs disappear a few months ago …
=> Add code to migrate old invalid NIF paths in save files

modular_skyrat/master_files/code/modules/loadout/categories/uniform.dm
Simple tweak to clothing in loadouts to allow corrections officers and security medic to access some more clothing that was restricted to generic security officers.
Basically lets Secmed and corrections officer access:
security skirts (all generic types that were available to normal sec officers)
security jumpsuit
security trousers
More customization options for players. They all have access to the vending machine that sells these, and it is reasonable to believe that some people working jobs would wear these uniforms given their ubiquitous nature in security.
Haven't tested locally but its a very minor tweak.
:cl:
add: Adds some new loadout options for Security Medics and Corrections Officers
/:cl:
=> adds new options to secmed and corrections officer

code/game/objects/structures/crates_lockers/closets/secure/security.dm, modular_zubbers/code/game/objects/structures/crates_lockers/closets/secure/security.dm
The HOP locker structure has had the two items, 
/obj/item/stamp/granted
/obj/item/stamp/denied
added to them. Meaning this affects every map with a hop office. 
Community supported, lets people larp as their favourite Arstrotzkan booth-man without stealing cargo's stamps (which are objectives already to make it funnier, just pointing out the humor).
No way this fails... There is no way. Worst case scenario? My comments are bad, but the code compiles.
:cl:
qol: Heads of Personnel have been given a bonus by Nanotrasen for their hard work, they now are provided big "granted" and "denied" stamps to assert dominance on any requesters in their line.
/:cl:
=> HOP lockers now contain a "granted" and "denied" stamp

code/game/machinery/computer/orders/order_computer/cook_order.dm, modular_zubbers/code/game/machinery/computer/orders/order_computer/cook_order.dm, tgstation.dme
As it turns out, despite the console having lowered prices for ordering normally - it had the original ones for express consoles. 
This means, that instead of paying, say, 5 credits for an item, you pay 15 credits for an item, as the actual gap between them is not double, but TRIPLE the price.
Now, instead of making it a 2x gap, I have decided that it's not entirely a bad idea to make it a 1.5x practical gap with the modifier = 1. 
Since cooks make large orders, I do not think the option of getting express orders and ignoring cargo is always convenient. 
We shouldn't punish cooks for trying to quickly make a meal. What is the crime? Trying to cook? To cook a succulent meal?
<details>
</details>
:cl:
qol:  Ordering groceries from the service produce …
=> Fixes express grocery pricing

tgui/packages/tgui/interfaces/OpposingForcePanel.jsx
`NumberInput` `onChange` doesn't pass an event, meaning this code was storing the new number in `e` and `value` was null
Fixes #3628 
<details>
</details>
:cl:
fix: fixed opfor menu crashing when changing requested equipment amount
/:cl:
=> Fix opfor crashing when changing equipment number

tgui/packages/tgui/interfaces/AmmoWorkbench.jsx
Same rationale as #3631, I'll probably do a pass through all our TGUI to look for these later but this is the other one I know 100% is broken
Buggg
I didn't but I just fixed something else caused by the same issue so if this breaks feel free to kill me
:cl:
fix: fixed ammo workbench crashing on changing amount of materials to release
/:cl:
=> Fix ammo workbench crash on changing materials amount

modular_skyrat/modules/company_imports/code/armament_datums/vitezstvi_ammo.dm
speedloaders were 50 on imports and 100 on goodies before. now it's 100 on both
Normalizing numbers is probably good, also fixes https://github.com/Bubberstation/Bubberstation/issues/3385
trust me bro it's a one line change
<details>
</details>
:cl:
fix: Speedloaders now cost the same between cargo goodies, and company imports.
/:cl:
=> Normalized speedloader price between cargo goodies and imports

code/game/machinery/scanner_gate.dm, tgui/packages/tgui/interfaces/ScannerGate.jsx
A previous PR re-introduced the removed contraband option for scanner gates so it was blue screening because none of the other supporting code was there. Also fix the broken gender option
Bug fix
Ohh I did
:cl:
fix: fixed the scanner gate UI bluescreening as soon as you open it
/:cl:
=> Fix scanner gate TGUI blue screening

code/modules/power/supermatter/supermatter.dm
lol
:cl: LT3
fix: Those jerks over at Cybersun can no longer trigger your station's supermatter delam suppression system
/:cl:
=> Fix non-station SM crystals from activating the delam suppression system

modular_skyrat/modules/multicellcharger/code/multi_cell_charger.dm, modular_zubbers/code/game/machinery/cellchargers/cell_charger.dm, tgstation.dme
Borgs can now remove cells from (multi)cell chargers. Does not touch the way carbons remove individual cells.
Engineering and Science borgs can put cells in cell chargers to recharge them but cannot remove them without help or destroying the charger. This fixes it by allowing borgs to make full use of cell chargers.
It compiles and was tested locally.
<details>
<summary>
https://github.com/user-attachments/assets/56fe06ed-4ffe-49b4-b67b-2331cd528bce
</summary>
</details>
:cl:
add: Adds ability for borgs to eject cells from cell chargers by alt clicking on the charger
add: Changes popping cells out on multicell chargers from right click to alt click to keep the actions the same between chargers
/:cl:
=> Lets Borgs pop out cells from cell chargers

modular_skyrat/master_files/code/modules/client/preferences/quirks/death_consequences.dm, modular_skyrat/modules/death_consequences_perk/death_consequences_trauma.dm
Changes the minimum value for two death consequences related settings to be 1 instead of 0, because these are percentages that get divided and end up causing div by zero runtimes. Also it doesn't make sense to even let these be zero
I didddd
:cl:
fix: the minimum values for "stamina damage end degradation percent" and "crit threshold end degradation percent" are now 1 instead of 0
/:cl:
=> Fix hundreds of divide by zero runtimes in death consequences perk

code/modules/antagonists/ashwalker/ashwalker.dm
It seems as of https://github.com/Bubberstation/Bubberstation/commit/224b8362c7a7117cba6682904fefbc9c28badf87 ashwalkers can't make arrows anymore. Arrow quivers and bows in the camp are useless.
Ashwalkers need arrows to hunt legions, which is currently extremely difficult. The arrow quivers in the ashwalker camp are also useless now.
<details>
</details>
:cl:
fix: Ashwalkers unable to craft arrows
/:cl:
=> Let ashwalkers make arrows

code/game/machinery/computer/crew.dm
The logic for monitoring nanites adding people to the suit sensors list was fucked up such that if someone had monitoring nanites installed and were also wearing a jumpsuit, the runtime log would flood with erroneous stack traces about them not wearing a suit sensors compatible uniform but still being in the suit sensors list. This fixes that and cleans up a couple random things in there too (mainly that the logic for broken suit sensors sending scrambled data was there twice fsr)
There's like 300+ runtimes if someone in round gets monitoring nanites
I swear I prommy
Doesn't impact anything player-facing
=> Fix buggy nanite suit sensor logic

code/modules/surgery/organs/internal/eyes/_eyes.dm
If you play a lizard or get brain damage, you'll notice your character's eyes getting stuck closed.
https://github.com/tgstation/tgstation/issues/90269
It's very noticeable and offputting to be one-eyed.
<details>
</details>
:cl:
del: Remove asynchronous blinking due to eyes getting stuck closed
/:cl:
=> Remove asynchronous blinking until TG fixes their code

code/modules/mob/living/living.dm
Skyrat added a condition so that people who didn't pass `can_be_revived()` (DNR people) could still be admin healed, but they didn't put brackets so the branch is taken every aheal, and it's only supposed to be used for dead people so it does things like makes them unconscious and lie down for a second
It's dumb as fuck
Imagine
:cl:
fix: getting admin healed no longer makes you drop to the floor and then get up
/:cl:
=> Fix admin heal making you drop to the deck and flop like a fish

modular_skyrat/modules/indicators/code/combat_indicator.dm
Combat indicator code incorrectly treats `COMSIG_LIVING_STATUS_UNCONSCIOUS` being sent when the mob isn't unconscious as a bug and throws a stack trace, in reality that signal is sent whenever the unconscious status of the mob is adjusted at all, like when a negative amount is applied to wake someone up. Change the logic to return if the mob isn't actually going unconscious
several dozen meaningless runtimes gone
Imagine an empty runtime list
Nothing player facing
=> Fix runtimes in combat indicator

modular_skyrat/modules/filtersandsetters/code/filtersandsetters.dm
This code is ugly as fuck because the base boneset proc is just a `treat` proc so it got copy pasted here but whats supposed to happen is you're able to heal hairline/compound fractures instantly with an alien bonesetter, otherwise you have to use bone gel and tape and wait. but due to a bug (this override blocks the base bone wound treat with gel/tape, and it doesnt check if its actually a bonesetter we're using) it would use this alien bonesetter treatment path with bone gel and tape.
Fixes #3658 
<details>
</details>
:cl:
fix: hairline and compound fractures are no longer instantly healed with bone gel, sorry!
/:cl:
=> Fix hairline and compound fractures being instantly healed with bone gel

modular_zubbers/code/modules/antagonists/traitor/uplink/uplink_items/syndimaid/clothes.dm
refactor maid armor stuff into using no_equip flags so it works way more solidly, plus nerfs it's acid/bio armor because it's clothing
fixes https://github.com/Bubberstation/Bubberstation/issues/3327
bug fix good plus this way it gives you visual indicator of this slot can't be used, that and i don't really like clothing having same exact stats as a hardsuit, it makes it a bit more logical that a maid outfit does not give you the same benefits as a spacesuit or a bio suit
<details>
</details>
:cl:
fix: Refactors syndi maid armor, it should work more reliably, or break more hilariously.
balance: Syndi maid armor no longer has maximum bio/acid armor
/:cl:
=> refactor maid armor stuff into using no_equip flags & slightly nerf it

modular_zubbers/code/datums/components/crafting/furniture.dm
Added Detective's Notice board to craftable recipes.
Otherwise those boards cannot be crafted or acquired in any way. And it makes the Detective Job just so much more fun and engaging when you can present your cases in this way.
(Or just flex all the cool things you gathered despite everything already having been resolved, but yknow - just in case)
Tested it and the board showed up in the crafting menu and was able to be crafted just fine.
<details>
</details>
:cl:
add: A way to craft the Detective's Notice Board with wooden planks.
/:cl:
=> Make Detective's Notice Board being craftable.

code/modules/antagonists/pirate/pirate_shuttle_equipment.dm, modular_zubbers/code/game/machinery/syndiepad.dm
TG added it so the pirate pad exports to a separate market that has like 3 things in it (hostages, parrots, cash) and so I added a var on the computer to determine which market it sells to and overrode it to station for interdyne/tarkon pads
Fixes #3661 
<details>
</details>
:cl:
fix: fixed port tarkon bounty pad returning 0 for all sales
/:cl:
=> Fix tarkon bounty pad being broken

modular_skyrat/modules/cargo/code/export_gate.dm
The export gate would runtime whenever someone cryoed that was a cargo tech because it looped through the locked manifest to get a mind reference and then a current mob (which wouldn't always exist) for some godawful reason, changed the logic to just use the `bank_accounts_by_job` list on `SSeconomy`
Fixes #3663 
Trust
N/A
=> Fix export gate runtime

code/modules/loadout/loadout_helpers.dm
Loadout equipping code checks mob equipment when running `on_equip_item` which would normally be fine because it eventually loops to the items in the case but if a job has the same type path as something in the loadout, say `/obj/item/clothing/head/beret` in the loadout and `/obj/item/clothing/head/beret/blueshield` in the job, it'll apply the loadout prefs to the job item because that's earlier in the list and that can break shit
Fixes #3667 
<details>
</details>
:cl:
fix: fixed loadout item customization breaking job equipment under certain circumstances
/:cl:
=> Fix bug with loadout items replacing properties of similar job items

modular_skyrat/master_files/code/_globalvars/configuration.dm, modular_skyrat/modules/advanced_shuttles/code/shuttles.dm
Yeah
Fixes #3680 
Yeag
:cl:
config: the arrivals shuttle should automatically return to the interlink again
/:cl:
=> Add default to arrivals shuttle auto return config

modular_skyrat/modules/exp_corps/code/clothing.dm, modular_skyrat/modules/quirks/echolocation/echolocation.dm, modular_zubbers/code/modules/client/client_color.dm, modular_zubbers/code/modules/status_effects/buffs/frenzy.dm, tgstation.dme
Fix screen color not cleaning up and add erroring on invalid usage, this includes the echolocation quirk, NV helmet, frenzy.
https://github.com/tgstation/tgstation/pull/89843 refactored the procs and we didn't update our usage of it
Bug fixes
<details>
:blushes: umm
</details>
:cl:
fix: Fixes NV helmets, frenzy, echolocation quirk leaving screen colors permanently on
/:cl:
=> Fix screen color not cleaning up and add erroring on invalid usage

modular_skyrat/modules/customization/datums/dna.dm
Pending my eventual attempt to eliminate this file completely and the subsequent spiral into madness, copies over the appropriate code from the tg `dna.dm` to transfer hair/facial hair gradient style and color when updating appearance from DNA
Fixes #3690 
<details>
me and the bestie
</details>
:cl:
fix: fixed changelings/paradox clones not copying victim hair gradients
/:cl:
=> Fix hair gradients not working for changelings

modular_skyrat/modules/assault_operatives/code/sunbeam.dm
Trust me
:cl:
balance: The Icarus Sunbeam weapons system melts all tiles in it's flame's reach
balance: The Icarus Sunbeam weapons system husks direct hits and deals damage in a wider range
/:cl:
=> Icarus Sunbeam is better now

modular_skyrat/modules/colony_fabricator/code/appliances/chem_machines.dm, modular_skyrat/modules/food_replicator/code/reagents.dm, modular_skyrat/modules/food_replicator/code/replicator_designs/replicator_food.dm
This PR aims to solve this issue by making any ways to obtain the non-crafting-friendly hot chocolate powder give the regular hot chocolate powder instead
Unintuitive, now with less hassle, now with more ease, harms noone, makes people happy. 
I swear if hot chocolate causes the destruction of the server or controversy on merge I will eat a sheet of paper. 
Basic replacement, trust me bro
:cl:
qol: unifies the two existing coco powder related reagents into one
/:cl:
=> Unifies coco powder to one reagent instead of two

code/controllers/subsystem/statpanel.dm
Fixes the station time on the stat panel, cleans up the code edit a bit.
It kills me inside to see the stat panel clock not match all the other clocks in game.
<details>
</details>
:cl: LT3
fix: Stat panel now shows the correct station time
/:cl:
=> Fix station time on stat panel

code/game/machinery/iv_drip.dm, modular_zubbers/code/game/machinery/iv_drip.dm, tgstation.dme
Restores the ability for borgs to attach IV drips to people again which was removed in an upstream PR refactoring mouse drag interactions.
This should have never been restricted from borgs. Medical borgs can actually restore blood to patients efficiently again.
IV drips and Automated IV drips are able to be used by both silicons and crew.
:cl:
fix: Silicons can attach IV drips again
/:cl:
=> Borgs can use IV drips again

modular_skyrat/modules/aesthetics/lightswitch/code/lightswitch.dm
Removes a Skyrat add that turns off lights by default in rooms that have light switches
There's no reason to make you hunt for the lights shift start. It also means the janitor can't tell what rooms have broken lights at a glance unless someone hit the switch.
:cl: LT3
del: Removed lights being turned off by default in various locations
/:cl:
=> Remove Skyrat lights off override

code/datums/mood.dm
Disables the mob hallucination caused by low hunger/mood
Having this status effect adds an annoyance and food is not readily available.
:cl: LT3
del: Removed hallucinations caused by high hunger/low mood
/:cl:
=> Removes hallucination on hunger/mood

code/game/turfs/closed/wall/reinf_walls.dm
`/turf/closed/wall/r_wall/update_icon_state` had a hard-coded icon file in it that the `syndicate` subtype doesn't use so it was getting changed to that
Fixes #3717 
<details>
</details>
:cl:
fix: fixed persistence walls being error on some maps
/:cl:
=> Fix persistence walls being error

modular_zubbers/code/modules/antagonists/bloodsucker/powers/gohome.dm
Fixes the issue of the ability "GoHome" aka "Vanishing Act" from bloodsuckers to bypassing the "NoDrop" from certain items
Bug/Oversight Bad
compiles and tested on localhost
:cl:
fix: Fixes "Vanishing Act" ignoring the "NoDrop" from certain items 
/:cl:
=> Fixes bloodsucker ability "Vanishing Act" ignoring NoDrop

modular_skyrat/modules/opposing_force/code/opposing_force_datum.dm, modular_skyrat/modules/opposing_force/code/opposing_force_subsystem.dm, modular_zubbers/master_files/skyrat/modules/opposing_force/code/opposing_force_subsystem.dm, tgstation.dme, tgui/packages/tgui/interfaces/OpposingForcePanel.jsx
- Change some text areas to have `fluid` so they're not small
- Move information that was on a hover button into the placeholder text for the text area for two inputs
- Bump window height slightly so it doesn't get scrollbary
- Change some `onChange` to `onBlur` so it doesn't hammer the server with `ui_act` calls literally every single time someone types a character
- Fix the intensity slider just saying NaN
- Change the intensity slider so the slider itself colors to what "interval" of intensity you're in, uses the color of the button below it
- Remove a line in the backstory placeholder text that says to check a discord channel we don't have
- Moved some stuff in `ui_data` to `ui_static_data` that absolutely did not need to get sent every update
- Fixed an incorrect variable in …
=> OPFOR Panel Fixes

code/modules/antagonists/fugitive/hunters/hunter.dm, code/modules/mob/living/basic/trooper/russian.dm, code/modules/surgery/organs/internal/tongue/_tongue.dm, code/modules/vending/sovietsoda.dm, modular_zubbers/code/modules/languages/_language_holder.dm
resolves https://github.com/Bubberstation/Bubberstation/issues/3716
idk man i didnt change anything
:cl:
refactor: changed bounty hunter and tongue default languages from spinwarder to panslavic
/:cl:
=> Cleans mentions of 'spinwarder' in code

code/modules/mob/living/blood_types.dm
read title. it's red again.
Also we're getting the blood customization quirk soon and I know that'll also remove this but honestly I'm not waiting several weeks for that
I commented it out and added //BUBBER EDIT REMOVAL
<details>
</details>
:cl:
remove: Lizard blood is no longer inherently green
/:cl:
=> Reverts the tg change of making lizard blood green

modular_skyrat/modules/goofsec/code/department_guards.dm
Upstream introduced `base_inhand_state` for batons that needs to be set or it'll default to `base_icon_state`
Fixes #3760
<details>
</details>
:cl:
image: departmental stun batons have an inhand icon again
/:cl:
=> Fix departmental stun batons missing inhand icon

modular_skyrat/modules/bodyparts/code/ghoul_bodyparts.dm
Ghoul limbs drop meat instead of the limb when they come off and they do that by `qdel`ing in `drop_limb` but if `drop_limb` was originally called as part of `Destroy` they'll qdel twice and you can't do that and it runtimes
Fix flaky CI failure
Trust
N/A
=> Fix flaky runtime related to ghoul limbs

code/modules/loadout/loadout_helpers.dm, code/modules/loadout/loadout_menu.dm, code/modules/loadout/loadout_preference.dm, tgui/packages/tgui/interfaces/PreferencesMenu/types.ts
Is this user a donator validation was being done in the `deserialize` proc for the pref which is bad because if someone was auto reconnected to the server after restart and joins right as it restarts it'll be run before the ranks system has loaded meaning this check will always fail and remove the item from their loadout. Moved the validation to when the player spawns in, so ranks is guaranteed to be loaded. Also changed something that was checking the donator list directly to use the proc for it. Also removed two unused variables that got deprecated in #3747 
Fixes #3773 
Tested it on a local before and after
:cl:
fix: fixed donator-only loadout items disappearing from donator's loadouts
/:cl:
=> Fix donator loadout items being removed

code/modules/surgery/organs/internal/heart/heart_ethereal.dm, code/modules/unit_tests/ethereal_revival.dm
Somehow Ethereals revives were changed back to TG's version. This fixes it back to bubbers version which gives them magical traumas instead of absolute traumas. Thus this is a bugfix, restoring how it originally was for bubber.
Getting a trauma that cannot be removed via any method is exceptionally annoying, and often just leads to the player immediately cryoing. Ethereals cannot control whether they revive via their passive. It is not something they can refuse without just flat out going DNR. A magical trauma is very difficult to remove, but not impossible, thus it is balanced.
:cl:
fix: ethereal revives gives magical trauma instead of permanent
/:cl:
=> ethereal-revive-bugfix

code/modules/surgery/organs/internal/eyes/_eyes.dm, config/bubbers/bubbers_config.txt, modular_zubbers/code/controllers/configuration/entries/blinking.dm
#3703 introduced a config value to enable blinking but it doesn't work because it defaults to true and config entries are disabled by commenting them out, but the lack of an entry will make it use its default value meaning you can never actually disable blinking. This switches it to be an option to disable blinking that defaults to false instead
we need to steal their eyelids
yeag
:cl:
config: fixed blinking config option
/:cl:
=> Fix blinking config

modular_skyrat/modules/ghostcafe/code/hilbertshotel_ghost.dm
The `AMBIENCE_` defines are supposed to be used with `ambience_index` not `ambientsounds`
Bug fix
I didn't
:cl:
fix: fixed the winter woods not playing ambience
/:cl:
=> Fix winter woods ambience

modular_zubbers/code/modules/credits/credits.dm
`/atom/movable/screen/credit/Initialize` added custom args but failed to include one from the parent type so the values were misaligned and it threw runtimes every time it instantiated. Also change a `QDEL_NULL` to `QDEL_LAZYLIST` cause it doesnt like it when you `QDEL_NULL` lists
No bugs
Imagine an empty runtime list
N/A
=> Fix two runtimes in round credits

modular_skyrat/modules/extra_vv/code/extra_vv.dm, modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm, modular_zubbers/code/controllers/subsystem/processing/quirks.dm, tgstation.dme
SAD and VV load prefs overrides quirks, instead of simply adding if missing
This is me trying to get people to pester admins less about quirks
Tested, seems to work
<details>
</details>
:cl:
add: SAD will now remove any quirks you don't have set in prefs, please don't abuse it.
admin: VV load prefs now loads and overrides quirks as well.
/:cl:
=> SAD and VV load prefs overrides quirks

modular_skyrat/modules/admin/code/player_ranks.dm, modular_skyrat/modules/player_ranks/code/subsystem/player_ranks.dm, modular_skyrat/modules/player_ranks/code/world_topic.dm
Changes verbs for managing player ranks (donator and mentor rank) to only require `R_ADMIN` instead of `R_PERMISSIONS`
`R_PERMISSIONS` is the flag for managing admin ranks, like changing an admin's rank, which is only given to senior staff. This is overkill, donator and mentor ranks should be changeable by regular admins
Hehehe I didn't
:cl:
admin: manage player ranks only needs R_ADMIN now
/:cl:
=> Change required perms for player ranks management to R_ADMIN

code/modules/loadout/loadout_items.dm, code/modules/loadout/loadout_menu.dm, tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/loadout/ItemDisplay.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/loadout/base.ts, tgui/packages/tgui/interfaces/PreferencesMenu/types.ts
I unhid ckey-locked and donor-locked items in #3747, but it's been expressed that people don't want to see items they'll never be able to obtain, so this re-hides them (while still keeping donor-locked ones visible, so people can see what they'll be getting if they donate)
Hide items you'll never be able to use
Tested both with and without having a ckey-locked item for my ckey
:cl:
qol: ckey-locked loadout items that you can't obtain are hidden again
/:cl:
=> Hide unobtainable ckey-locked loadout items again

_maps/moonstation.json
Give Moonstation players a little something extra for their shifts.
:cl: LT3
fix: Moonstation players are now begrudgingly given emergency hooks in their survival boxes
/:cl:
=> Provide hookers to all moonstation players

modular_skyrat/modules/synths/code/reagents/reagents.dm
This isnt really my original idea.
Original PR: https://github.com/Bubberstation/Bubberstation/pull/1040/files
This is part of a PR that was testmerged but wasnt maintained due to various amount of changes it had, hence why im only doin it partly one at a time if i were to do more from it.
Title is self explanator.
It should help synthetic humanoids with repair of their organs that doesnt exactly equal with overdosing themselfs on nanite slurry that even on lowest overdose, barely doesnt crit you and it barely heals.
Tested if its working in the first place aka healing organs and if it still heals brain damage and even traumas.
Everything seems to be working on my side as far as I have seen it.
<details>
</details>
:cl:
balance: Liquid solder now also …
=> Liquid solder now heals organs on top of brain damage.

code/modules/surgery/organs/external/_visual_organs.dm, code/modules/surgery/organs/external/wings/moth_wings.dm
tg changed mutant part hiding logic some upstreams back and our override hiding logic stopped getting called
Fixes #2790 
<details>
I have hiding antennae and wings enabled in this pic
</details>
:cl:
fix: fixed moth antennae and wings not hiding properly
/:cl:
=> Fix being unable to hide moth antennae or wings

code/modules/surgery/cavity_implant.dm, modular_zubbers/code/modules/surgery/robotic_cavity_implant.dm, tgstation.dme
A simple PR that adds a new surgery for augmented/synthetic characters, allowing them to have cavity implants like organics.
More options for characters and it always felt silly to me that synthetics/augmented characters could not have cavity implants.
Tested locally on synthetic and augmented character, worked flawlessly.
:cl:
add: Adds cavity implantation surgery for synthetic/augmented/robotic characters
/:cl:
=> Robotic cavity implant

modular_skyrat/modules/modular_vending/code/cigarette.dm
There was a bug that was preventing the base contraband list from being added to the cigarette vendor
Modularity fix - the baseline contraband lists was just not appearing at all for the cigarette vendors. I confirmed that none of the other modular vending machines have this issue, (they don't have a base `contraband()` list in them.)
<details>
This shows it contains both:
https://github.com/Bubberstation/Bubberstation/blob/dfb11b4f7171ec4aec141fbe5db047af9cfde769/code/modules/vending/cigarette.dm#L19-L22
https://github.com/Bubberstation/Bubberstation/blob/dfb11b4f7171ec4aec141fbe5db047af9cfde769/modular_skyrat/modules/modular_vending/code/cigarette.dm#L7-L14
</details>
:cl:
fix: Fixed a small bug with combining contraband lists between baseline and …
=> Fixes the Cigarette Vendor Contraband lists

tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/loadout/ItemDisplay.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/loadout/index.tsx
Adds the ability to search loadout menu items by the things in their tooltips (job whitelist/blacklist, donor-only, recolorable, etc.) 
Sometimes you wanna see just items your job can equip
<details>
</details>
:cl:
qol: added an option to the loadout menu search that lets you also search in tooltip text
/:cl:
=> Add option to search loadout item tooltip text

modular_skyrat/modules/customization/modules/client/augment/organs.dm, modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/tajaran.dm, modular_skyrat/modules/teshari/code/_teshari.dm
Title.
Allows Teshari/Tajara to breathe on icemoon by default. Sure, you could just take the lungs, but teshari are a frigid species, and should be adaptive to the cold out-of-the-box.
<details>
lol i forgot to record. trust me tho the lungs get applied and the birds can breathe icebox air
</details>
:cl:
add: Teshari spawn with cold-adapted lungs
add: Default lungs to the augment menu
/:cl:
=> Teshari/Tajara now start with cold-adapted lungs + adds default lungs to the augment menu

modular_skyrat/modules/customization/modules/clothing/storage/belts.dm
see title
its really arbitrary that it only lets you carry skyrat hypos and not medipens and such, especially because it lets you carry DNA injectors and syringes...
line change
:cl:
add: medical bandolier lets you carry all hyposprays/injectors and test tubes
/:cl:
=> lets the medical bandolier hold all 'hyposprays' and vials

modular_skyrat/modules/primitive_structures/code/wall_torch.dm
Does as the title says and makes it so you can actually *craft* the wall-mounted torches.
It makes it possible to actually light your rooms if you want to try to make a low-tech base on Lavaland or something along those lines.
I tested it and it was working as intended.
:cl:
qol: wall-mounted torches can now be crafted
/:cl:
=> Craftable Wall Mounted Torches

modular_skyrat/modules/alternative_job_titles/code/alt_job_titles.dm
Adds the following job titles
Clown - Prankster
Detective - Gumshoe
Psych - Shrink
Cargo Technian - Crate Pusher
Removes Janitor's "Maintenance Technician" alternate title.
More alt titles are fun.
Maintenance Technician sounds more like an alternate job title for engineering, and I swear to god half the time I see someone with that alt job title my brain goes "oh, engineering!"
<details>
hehehehohoohoehehehe
</details>
:cl:
add: Adds four new job titles! Prankster, Gumshoe, Shrink, and Crate Pusher.
del: Removes Janitor's "Maintenance Technician" job title.
/:cl:
=> Adds 3 new alt job titles, removes one.

modular_zubbers/master_files/code/modules/entombed_quirk/code/entombed_alt_actions.dm, tgui/packages/tgui/interfaces/StripMenu.tsx
Override for back slot strip alt actions was written wrong
Bug
<details>
</details>
:cl:
fix: fixed set internals button missing in the strip menu for tanks worn on the back
/:cl:
=> Fix set internals button missing in strip menu

modular_zubbers/code/modules/pen_medipens/pen_medipens.dm
After thinking about it and learning from people just how insanely strong pills are, I decided it was a knee jerk nerf and wasn't necessary
the chemical
yeah
:cl:
balance: revert medipen volume back to 25u
/:cl:
=> Revert "Nerf printable medipen volume from 25 to 12"

code/datums/components/irradiated.dm
Non-living beings no longer glow from being irradiated.
Massive GPU lag on the client from the amount of radiation filters any time something is irradiated is not good. This PR makes it so that radiation is no longer visible on things that aren't living. You can still check if something is irradiated by scanning it with a Geiger counter.
Untested.
:cl: BurgerBB
del: Non-living beings no longer glow from being irradiated.
/:cl:
=> Non-living beings no longer glow from being irradiated.

code/modules/loadout/loadout_helpers.dm
Since when previewing your character it doesn't actually put the loadout items in a case it needs to be searching in the mob like normal
Fixes #3860 
Tested it before and after with all 3 loadout pref options
:cl:
fix: fixed GAGS modifications to loadout items not showing in preview when using place all in case pref
/:cl:
=> Fix GAGS loadout item recolors not showing in char preview with place all in case pref

modular_skyrat/modules/synths/code/species/synthetic.dm
This PR does two things (three things)
Lack of/non-functional lungs causes you to overheat.
Lack of/non-functional heart will cause you to be slowed down. (edited from paralysis to slowdown)
Add additional messages to indicate lack of liver equivelant.
CURRENT ISSUE: (RESOLVED)
Removing it does the effects.
Having non functional organs doesnt apply it.
The fact that you didnt needed half of your organs is just dumb.
Lungs definitely work when you remove them and EMP them to death
Heart works when you remove them and EMP. (Again with new effect) 
Replacing it with any other organ also works as long as its in the heart/lungs slot.
Liver messaging workin when missing or non-functional
<details>
</details>
:cl:
add: Synths now require their lungs. Lack of …
=> Synth now require a heart and lungs to function.

_maps/RandomRuins/IceRuins/bubberstation/icemoon_persistence.dmm, _maps/RandomRuins/IceRuins/bubberstation/icemoon_surface_gas_bubber.dmm, _maps/RandomRuins/LavaRuins/bubberstation/lavaland_surface_gas_bubber.dmm, _maps/RandomRuins/SpaceRuins/skyrat/port_tarkon.dmm, _maps/bubber/automapper/templates/IceBoxStation/iceboxstation_icecats_lower.dmm, _maps/bubber/automapper/templates/lavaland/lavaland_persistence.dmm, modular_skyrat/modules/hotel_rooms/prisoninfdorm.dmm, modular_skyrat/modules/primitive_catgirls/code/map_items.dm, modular_zubbers/maps/offstation/lizard_gas.dm, modular_zubbers/maps/offstation/persistence/turf.dm, tgstation.dme
Cleans up active turfs in the lizard gas ruin (lavaland and icemoon), the ice cats camp, port tarkon, and some but not all in persistence (lavaland and icemoon)
Less roundstart active turfs
I tested it 
No player facing changes
=> Some active turfs fixes

modular_skyrat/modules/drone_adjustments/drone.dm
As with the title. Removes common from Maintenance Drones' blocked languages list, and adds it to the understood languages list. Keeps it out of the spoken languages list, still, though -- communication is one-way.
Additionally, tweaks drone law as follows:
```diff
- You may not involve yourself in the matters of another being, even if such matters conflict with Law Two or Law Three, unless the other being is another Drone
+ You may not hinder the freedom or actions of other beings, nor undo the results of said actions, unless the other being is another Drone.
```
Similarly, in the drone rules clarification, I removed "communication" from the list of barred interactions, and added a qualifier and a different example of going too far:
```diff
- Interacting with living beings …
```
=> Allows Maintenance Drones to Understand Common. Loosens Drone Law slightly.

code/__DEFINES/time.dm, code/modules/holiday/holidays.dm, modular_zubbers/master_files/code/modules/holiday/holiday.dm
Adds the other five in game pride flags to the tile colouring system. Also adds a 20% chance of pride tiles on non-holiday days.
<details>
</details>
:cl: LT3
add: The station tiles may now be gay, bi, trans, lesbian, pan, or ace if they want to
/:cl:
=> Makes the server (more) gay

modular_skyrat/modules/modular_implants/code/soulcatcher/ghost.dm
Moves the 'Enter soulcatcher' verb to the IC tab, because TG eliminated the Ghost tab
<details>
</details>
:cl: LT3
fix: Enter soulcatcher is now on the IC stat panel tab
/:cl:
=> Move soulcatcher verb to IC tab

modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/saibasan/mode_datums.dm, modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/saibasan/projectiles.dm
**Sniper module:**
damage: 50 -> 40
Proj. Velocity: 2.5 -> 2
AP: 0->15
**Blade:**
Force: 18 -> 20
Wound bonus 0 -> 5
Bare wound bonus 10 -> 15
**Big Shotgun:**
Pellets: 5 -> 4
**Small Shotgun:**
Variance: 15 ->20
**Shotgun Pellets:**
Damage falloff: -0.5 -> -3
Damage: 10 -> 15
No longer weak against armour
The PR's goals are:
- Making the ERT modular shotguns stronger than lasers at their designated ranges
- Prevent shotguns from dominating over other modules in return 
- Allow the blade module to be a reliable fallback melee weapon in comparison to the modern arsenal
- Decrease the killing power of the sniper module
- It's goal is **not** to create an unfairly high TTK for the ERT
- It's goal is **not** to modify the overall power level of the ERT squads, rather making them consistent at …
=> ERT gun balance adjustments

modular_skyrat/modules/colony_fabricator/code/repacking_element.dm
Make the repackable element return COMPONENT_CANCEL_ATTACK_CHAIN in its signal handler so the interaction is properly cancelled and it doesn't do stuff like open GUIs
Bug fix
Yeah
:cl:
fix: fixed repackable things like colony synthesizers opening their GUI when you right click to repack
/:cl:
=> Add COMPONENT_CANCEL_ATTACK_CHAIN to repackable element

code/datums/brain_damage/creepy_trauma.dm, code/modules/events/creep_awakening.dm
Because obsessed is treated as a weird antagonist not antagonist in the code there's no checks for antag ban status before someone rolls it meaning if someone with an antag ban rolls it it polls ghosts to take over their body and then just forces them out. which sucks. Changes the code so during the Obsessed Awakening event they will be passed over for the role and if they end up with it from admin shenanigans it simply won't apply 
Randomly being wrenched out of your body for something you can't control (storyteller picking Obsessed Awakening) sucks
Tested it on a local with two clients
:cl:
fix: antag banned people will no longer roll obsessed and be forcefully ghosted
/:cl:
=> Fix antag banned people being able to roll obsessed

modular_skyrat/modules/aesthetics/vending/access_vending.dm
This thing uses special bad copy paste code that became out of date since GAGS vending machine spritesheets became a thing but I'm lazy so I copy pasted the updated code instead of rewriting it to be better 
You can see the icons
<details>
</details>
:cl:
fix: fixed command outfitting station having broken sprites for everything
/:cl:
=> Fix all the sprites in the Command Outfitting Station being broken

_maps/bubber/automapper/templates/centcom/interlink_adminoffice.dmm, _maps/map_files/generic/CentCom_skyrat_z2.dmm
Changes all public shutters on the interlink to pre-opened variants. Removes all medical and surgical kits from the medbay to avoid unfair advantage. Makes all vending machines free, as is the standard for the interlink. NT Rep and Blueshield office have remained unchanged, but they only have a set of CC clothing and a clipboard within them
It's been a long requested item, for the rest of the interlink to be opened for scenes.
</details>
:cl:
map: The interlink is now (almost) fully accessible to crew.
/:cl:
=> Opens up the Southern Half of the Interlink

modular_zubbers/code/modules/jobs/stowaway.dm
Change the target areas for this to just be the arrivals shuttle hallway instead of random maintenance areas
Hopefully fix the bug
It works locally but the only way to test if it un-flakys CI is to try this
No player-facing changes
=> Fix flaky runtime related to stowaway landmark

modular_skyrat/master_files/code/modules/client/preferences/species_features/digitigrade_legs.dm
We have an override to make the default digigrade option for species `DIGITIGRADE_OPTIONAL` but for some reason this override code was still enforcing the pref being locked behind the species having mutant digigrade legs
Greater customization as was intended
Checked a good handful of species in the character creator and it looked fine
:cl:
fix: fixed certain species being unable to access the digigrade legs pref
/:cl:
=> Fix certain species being unable to spawn with digigrade legs

modular_skyrat/master_files/code/modules/loadout/categories/inhands.dm
Replaces the Full Toolbox in loadout with Emergency Toolbox
Starting with a full suite of tools is arguably a tad much, why grab tools from tool storage/autolathe/the vendor when you start with everything but a multitool anyways?
<details>
</details>
:cl:
balance: Replaced toolboxes in loadout with emergency toolboxes.
/:cl:
=> Replaces the Full Toolbox in loadout with Emergency Toolbox

modular_skyrat/modules/modular_implants/code/nifs_tgui.dm, tgui/packages/tgui/interfaces/NifPanel.jsx
Data was being sent to `e` instead of `value`, also changed it so it will autofill with your current examine text because it apparently didn't have that already
Fixes #3966 
Tested on a local
:cl:
fix: fixed being unable to edit NIF examine text
/:cl:
=> Fix being unable to change NIF examine text

_maps/map_files/biodome/biodome.dmm
Before it looked like this 
<details>
<summary>BEFORE</summary>
</details>
and now it no longer has these horrible no good visual issues
<details>
<summary>After</summary>
</details>
oh right bug is bad
<details>
</details>
:cl:
fix: Makes biodome's supermatter room not have a floating camera and misaligned decals
/:cl:
=> Minor Visual Fixes To Biodome's SM Room

modular_zubbers/code/modules/storyteller/event_defines/major/major_overrides.dm
Increases the minimum players for blob to spawn from 20 to 50.
20 players minimum for blob to spawn is absurd. Note that this does not mean 20 crew, but 20 living human non-afk players on the server.
Untested.
:cl: BurgerBB
balance: Increases the minimum players for blob to spawn from 20 to 50.
/:cl:
=> Increases the minimum players for blob to spawn from 20 to 50 because I saw a suggestion in #suggestions about it once.

_maps/map_files/KiloStation/KiloStation.dmm
WHAT WERE THEY THINKING 
At least now the airlock isn't connected to fucking nothing
Look man this shit pisses me off and I'm doing this just to quell my own insatiable hatred of this one corner
<details>
</details>
:cl:
Fix: Makes the walls in kilo lesser port maint slightly less infuriating
/:cl:
=> Makes the walls in kilo lesser port maint slightly less infuriating

_maps/RandomRuins/SpaceRuins/skyrat/drones_derelict.dmm
The base TG russian derelict and the babylon station derelict both use these vault door controller setups where you have to power them to unlock the vault, but they both use the same ID so if both ruins spawn it will sometimes open the doors in the other ruin and you get nothing
I was swindled
<details>
</details>
:cl:
map: fixed the russian and babylon derelicts vault doors interfering with each other
/:cl:
=> Fix russian and babylon derelict ruins interfering with one another

config/maps.txt
This situation is a mess because the map config on this repo, the map config on the config repo, and the map config on the live server all differ from each other, most concerningly the live server one has almost no minimums set, and no maximums either, this changes the config file here to consolidate changes from TG (using their minimums for their maps) and here (the values set in the config repo for our maps)
Kilo is currently running with 80 people online
Yeah
:cl:
config: clean up the map config and ensure all maps have minimums/maximums set as necessary
/:cl:
=> Clean up the damn map config

modular_skyrat/modules/exp_corps/code/gear.dm
Title explains it. Goes from 6.7 hits/crit to 9
A circular saw having the damage of more dedicated melee weapons (on par with the bowie knife/cap's sabre minus the block and AP) whilst also being pocket sized - AND being included in a medkit just don't make sense. A little less damage than a regular circular saw is reasonable given it's more compact. In its current state it does more damage than the upgraded medical tools. There is very little reason for this to do as much damage as it does.
<details>
</details>
:cl:
balance: Moved the Bone Saw's force from 20 > 15
/:cl:
=> Changes the Medtech kit's bonesaw's force from 20 > 15

_maps/map_files/moonstation/moonstation.dmm
Turns out those particular items would superglue to your hand if you picked them up. 
Replaced them with non-superglue sombrero.
oversight = bad
trust me bro
<details>
</details>
:cl:
fix: Replaces the superglue sombrero in Moon EVA with ones that dont stick to your hands forever.
/:cl:
=> [FIXES OVERSIGHT] Removes Shamebrero From Moonstation EVA

modular_zubbers/code/modules/mob/living/carbon/human/species_types/zombie.dm
This fixes HFZs to allow them to select their hair in character creation
Bugs are bad, and this lets HFZs pick their hair properly.
Tested locally, works fine
:cl:
fix: high functioning zombies can now choose hair in character creation
/:cl:
=> High functioning zombie hair bugfix

config/game_options.txt
Disables random events in the config. It should already be this way on the box config. Either way this change is just for people running their own fork. 
look man I've been testing stuff on local and halting storyteller and going "hm what the fuck man why are anomalies still spawning" only to realize it's because this shit is on in the config if you run a local and you have to manually turn it off. Saves people from a pitfall. 
<details>
</details>
no
=> [DO NOT MAKE THE CHANGES ON BOX CONFIG] Disables random events in config (not storyteller)

_maps/bubber/automapper/templates/IceBoxStation/iceboxstation_persistence_roof.dmm
For whatever reason, a total of seven open air tiles got lost at some point between my testing on the final version and the merged version. This readds them which makes the elevator work again.
Its preferred to have stuff working usually. 
<details>
</details>
:cl:
fix: The elevator on persistence works again. Pretty sure we had Jimmy Hoffa stuck there or say the SOSHA folks say.
/:cl:
=> Quick Persistence hotfix to make the elevator work on icebox

_maps/map_files/biodome/biodome.dmm
no longer are the sec posts AA
they're supposed to have the access helpers (medbay had one, the rest didnt). bug bad.
yep I sure added them
<details>
</details>
:cl:
fix: Biodome departmental guard posts no longer have AA
/:cl:
=> Gives biodome guard post airlocks access helpers

config/game_options.txt
An extremely simple pull request changing one value. Ups the max positive quirks from 6 to 8. Obviously this requires a config change.
People have been asking for this limit to be increased for a long long time now, its a very very popular suggestion on the discord. And letting people have more positive quirks allows for further customization of characters.
:cl:
balance: ups the limit of positive quirks to a max of 8
/:cl:
=> more positive quirks

modular_zubbers/code/modules/antagonists/bloodsucker/powers/tremere/dominate.dm, modular_zubbers/code/modules/antagonists/bloodsucker/structures/crypt.dm, modular_zubbers/code/modules/antagonists/bloodsucker/vassal/vassal_datum.dm
fixes some bloodsucker-related text and ghouling mindshielded people.
Seems like it broke at some point.
Stuff working is good, if we want to remove this feature should be done in a separate PR, but is better to have working features than broken ones.
<details>
</details>
:cl:
fix: Fixes/changes some conversion messages to make it make more sense
fix: mindshielded conversion
/:cl:
=> fixes text and ghouling mindshielded people

modular_skyrat/master_files/code/modules/loadout/categories/gloves.dm
Removes pay-to-win military gloves from the loadout (they were free insulated + temp resist + could shoot guns available to server donators only lol)
For some reason Skyrat added the best gloves in the game to the loadout and then made them donator only. That's wack as hell considering these are
1. high strip delay(6 seconds to take them off of someone)
2. fully insulated
3. fully temperature proofed for space
4. able to fire guns while using even though it's insulated
this is pay 2 win as hell lol
deletes a loadout item
:cl:
del: Removes pay-to-win military gloves from the loadout
/:cl:
=> Removes pay-to-win military gloves from the loadout (they were free insulated + temp resist + could shoot guns available to server donators only lol)

code/modules/projectiles/guns/energy/stun.dm, code/modules/projectiles/projectile/energy/stun.dm
https://github.com/Bubberstation/Bubberstation/pull/3534 missed adding two modular comments and didn't change a `RegisterSignal` to `RegisterSignals` when passing a list of multiple signals
Runtime fix + documented non-modular changes
If it compiles it works
No player facing changes
=> Taser runtime fix

code/datums/components/squashable.dm
Having WALK MODE on makes it so you don't give micros any wounds/damage. Knockdown still applies.
Giving people a way to not accidentally squish micros is good, having it tied to walkmode which everyone can turn on willingly and not just a quirk like before (Pacifism) is also good. The knockdown is still there. 
Tested it on a localhost
<details>
</details>
:cl:
balance: Having WALK mode on makes you not squish micros.
/:cl:
=> Makes it so having WALKMODE on doesn't crush people with the micro quirks

modular_zubbers/code/modules/status_indicators/status_indicator.dm
Reduces the status indicators from POINT_PLAIN to ABOVE_GAME_PLANE
Makes them more visible if your mob is only visible, while also maintaining a clickthru.
It works
:cl:
fix: Status indicators will no longer show through certain effects like smoke.
/:cl:
=> Reduces status indicators from POINT_PLAIN to ABOVE_GAME_PLANE so they don't show through effects like smoke.

modular_zubbers/code/modules/nanites/nanite_programs/healing.dm
lets nanite defib revive client-less mobs
Nanite defib is outwardly very unclear why it fails, so you'd think the program itself doesn't work if it doesn't defib even if all other conditions are correct, so why not let this defib ghost-less mobs
<details>
</details>
:cl:
balance: Nanite defibs can defib client-less mobs
/:cl:
=> lets nanite defib revive client-less mobs

modular_zubbers/code/modules/customization/species/proteans/__DEFINES.dm
Per title. Removes burn weakness and brute resistance from proteans
The idea behind this was you shoot proteans with laters, but it comes to be an issue when these are multiplicative. So a Protean wearing riot armor would have an armor rating much higher to brute damage. Also, these sources of damage are not entirely uniform. Antags don't have too many lasers to be shooting proteans with, on top of the regeneration they already have.
- Players aren't going to be inately aware of this. They're just a damage spounge.
- Players won't really realize you can just shoot off their limbs, which you still can. (Which is why I'm not touching the regen yet)
- Players won't really know that bleeding will make metal consumption shoot up signifigantly. (Another reason I'm not touching the regen yet)
4 …
=> Protean Balance: Removes the brute and burn modifiers from Proteans

code/datums/quirks/positive_quirks/settler.dm, code/datums/quirks/positive_quirks/spacer.dm, modular_zubbers/code/modules/customization/height_scaling/preferences.dm
These changes modularly remove the forced height changes for the quirks Settler and Spacer by commenting out the part that applies them on creation and removal
Blubberstation is about roleplaying and character creation.  In my mind, a "Settler" character would be a giant equine man with a cowboy hat who can carry flatpacks over one shoulder but he also drives around his ranch in a pickup so he's not very fast.  Or maybe he's just not in much of a hurry from the idyllic farm life.  Also, Settler is a great perk and people should use it more.
And a Spacer is like, someone's special spacefaring race that's small for getting inside of engine compartments.  (Though the tallness fits equally as well)  Spacer honestly needs some buffs to be as good as Settler is.
:cl: Stonetear
balance: Spacer …
=> Remove forced size changes on Settler and Spacer

modular_skyrat/modules/company_imports/code/armament_datums/jarnsmiour.dm, modular_skyrat/modules/knives/knives.dm, modular_skyrat/modules/modular_weapons/code/melee.dm
Adjusts the damage of the cargo-orderable bowie knife to 17 and sabre to 15 force, as opposed to the 20 they both were.
Gives the cargo bowie knife 20 throwforce. Throwing knifes is cool. Also also makes it cheaper because it's weaker now.
20 force is a LOT. There are VERY few crew-accessible weapons that have this much force. The captain's sabre is one of them (by merit of skyrat override but whatever the cap can have that). The vast majority of crew-accessible melee weapons have 15 force, these include circsaw, butchers cleaver, etc. 
For reference, heretic blades start with 20 force.
The soulscythe (bubblegum reward) has 20 force.
The captain's sabre has 20 force.
These 2 weapons having the extra damage is far out of tune with the rest of crew-side melee weapons.
These weapons are …
=> Rebalances the cargo sabre and cargo bowie knife

modular_zubbers/code/datums/weather/weather_types/sand_storm.dm
Reduces the chance of Moon Station sandstorms from 40% to 20%.
Reduces the duration of Moon Station sandstorms from 2-4 minutes to 1-3 minutes.
People don't like how common these are.
:cl: BurgerBB
balance: Reduces the chance of Moon Station sandstorms from 40% to 20%. Reduces the duration of Moon Station sandstorms from 2-4 minutes to 1-3 minutes.
/:cl:
=> Reduces the frequency and duration of Moon Station sandstorms because I died to it once.

code/datums/emotes.dm, modular_zubbers/code/modules/client/preferences/sounds.dm, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/bubber/sounds.tsx
Add a new volume pref in game options that controls how loud emotes that have sound effects are.
Note: This PR was made to fulfill a bounty by @NanoCats
Quality of life improvement, we have many emotes that play sounds here and not everyone wants to hear them. Also there's that one scream that's insanely fucking loud
<details>
Note: the emote cooldown was disabled in this video for demonstration purposes
https://github.com/user-attachments/assets/1e465ad1-6be9-4113-a564-72ace0c78118
</details>
:cl:
qol: added a volume slider for emote sounds to game options
/:cl:
=> Add volume slider pref for emote sounds

modular_skyrat/modules/customization/modules/mob/dead/new_player/body_markings/body_marking_sets.dm, modular_skyrat/modules/customization/modules/mob/dead/new_player/body_markings/body_markings.dm, modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/horns.dm, modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/snout.dm, modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm, modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/wings.dm, modular_zubbers/code/modules/customization/sprite_accessories/ears.dm
One of our server rules is that you can't play species from other canons 1:1 so it's a bit misleading to have parts named after them. Headmin wanted them to be renamed. Will probably do the same for eevee+scolipede when they come up with names for it. Leaving the datum names the same and the like so it's still clear what it's meant to be if you decide to codedive.
code follows standards set by server rules this is a good thing
yeah it works
<details>
</details>
:cl:
code: Renames the guilmon + renamon parts to toraxen + cyvian respectively.
/:cl:
=> renames the guilmon + renamon parts to toraxen + cyvian by headmin request

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage/corrupted_tongue.dm
Hemophages couldn't drink blood from anyone with a non-standard bloodtype, even if they had blood, like lizards with L bloodtype.
Bug fix. (I don't want to die from blood loss because the only willing donor at the time was a lizard but oops I can't bite them.)
i tested this so fucking much to figure out a way to actually make it work 
<details>
</details>
:cl:
fix: hemophages can drink from lizards and other hemophages once more
/:cl:
=> fix hemos to be able to drink from each other and lizards again

code/__HELPERS/~bubber_helpers/mobs.dm, code/modules/mob/living/silicon/robot/robot.dm
As cyborg by flashing light while bucked to chair(flashlight call has `update_icons()` in it), I figured out that tallborgs have their sprite changed, but game does not update that sprite. I think I fixed that.
Checking if we have any AI to not cause runtimes each time cyborgs get spawned when there no active AI.
I think it supposed to be that way
<details>
</details>
:cl:
fix: Tallborgs now have have their sit sprite when they buckled to chairs
/:cl:
=> Cyborg sprite update on buckle/unbuckle

modular_skyrat/modules/company_imports/code/armament_datums/deforest_medical.dm, modular_skyrat/modules/deforest_medical_items/code/storage_items_robotics.dm, modular_skyrat/modules/modular_items/code/bags.dm
prevent premium robo kits from storing normal sized, reduces total storage to 12 * 2 & make all skyrat pouches bulky
currently you can store pouches in backpacks meaning you can fit normal sized items in (some) pouches, same deal with the robo kit, and while it is comparable to the surgical medkit, it it can store 12*3=36 total storage in w_class of items, vs the surgery medkits 24, then, haha.
<details>
</details>
:cl:
balance: Premium robo repair kits can only hold small items now and hold 24 w_class worth of items and costs 900 to account for this removal, as it still contains cargo-order items
balance: All skyrat pouches are now bulky.
/:cl:
=> prevent premium robo kits from storing normal sized & make all skyrat pouches bulky

modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
de-lobotomizes everyone's favorite megafauna
Essentially makes him capable of speech and fighting again- he will no longer just stand there like a potato and take hits for no reason. Basically: no one else wanted to maintain this code, so I'm kinda taking it upon myself to get the marked one acting as he should.
Megafauna should *probably* hit you back when your hitting them. 
I spawned him in in his arena on a private server, and watched as my ass majestically flew across the room and was promptly gutted by Markiplier 
:cl:
fix: fixed the marked one's ability to do anything, as well as his ability to speak.
/:cl:
=> fixes the marked one

modular_zubbers/code/datums/components/weatherannouncer.dm, tgstation.dme
Weather announcers now warn for Sol, within 90-60 with seconds before it starts
Sol is hard for non-hemophages to predict, so letting weather announcers warn them with some randomness should make it more possible to play around bloodsucker sol on the opposing side
<details>
</details>
:cl:
balance: Weather announcers will now detect Sol cycles within 60-90 seconds before it starts
/:cl:
=> weather announcers now warn for Sol

modular_skyrat/modules/modular_items/lewd_items/code/lewd_clothing/bdsm_mask.dm, modular_skyrat/modules/modular_items/lewd_items/code/lewd_clothing/deprivation_helmet.dm, modular_skyrat/modules/modular_items/lewd_items/code/lewd_items/_sex_toy.dm, modular_skyrat/modules/modular_items/lewd_items/code/lewd_items/dildo.dm
A few months ago action buttons were refactored so that you set a var, `action_slots`, that controls what slots an item needs to be equipped into to grant the associated action buttons, it defaults to whatever slots the clothing occupies. We have a few items that work a little differently or explicitly block using the action button when equipped, so adding `ITEM_SLOT_HANDS` to their `action_slots` was necessary.
Fixes items that were broken
Yes
:cl:
fix: fixed the latex gasmask, deprivation helmet, and double-ended dildo not properly granting associated action buttons when held
/:cl:
=> Fix a few action button related bugs

modular_skyrat/modules/filtersandsetters/code/filtersandsetters.dm
Quick fix to let cyborgs add filters to the combitool with CTRL click.
Ideally, the cyborg click code would be fixed for this. But I am not skilled enough at coding or modularization to do that
Cyborgs should have access to the same functions of the tools they are given that carbons do
Compiled, CTRL clicking as cyborg opened whitelisting menu
:cl:
fix: Cyborgs can now add filters to medical Combitools with CTRL click
/:cl:
=> Lets cyborgs filter medical combitool

html/changelogs/AutoChangeLog-bubber-pr-4296.yml, modular_skyrat/modules/gladiator/code/datums/ruins/lavaland.dm, modular_skyrat/modules/gladiator/code/game/objects/items/gladiator_items.dm, modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm, modular_zubbers/code/datums/components/crafting/tailoring.dm
Basically: we're re-adding the marked one, nerfing the stats on it's armor into the ground- (and technically below ground too!) so it's more in line with the design goals of the maintainers. The concept is simple; by directly making it so you'll take *more* damage by wearing the armor, it would be monumentally idiotic to go out and try to "frag out for valids" in armor which renders you more vulnerable to conventional weapons. You'd be better off using a basic survival suit than this set of armor.
re-adds a long, long lost fight from a while ago- essentially putting more content back in the game and a optional "final boss" for the experienced, or not-so-experienced shaft miner to try their hand at. 
It also addresses a long standing gripe- that shaft miners take their fancy new toys and …
=> Marked One re-add

modular_skyrat/modules/blueshield/code/modsuit/mod_theme.dm, modular_skyrat/modules/novaya_ert/code/mod_suit.dm
/tg/ added modsuit based ear protection for all combat-rated suits, this adds that to ours. 
parity is good and cool
works on my machine
:cl:
add: adds the Hearing Protection Module to Skyrat-added MODsuits
/:cl:
=> Adds the Hearing Protection Mod to our combat MODsuits

code/modules/holiday/holidays.dm
Fix floor tile decals from having a 20% chance of receiving a color. Disables the proc until I finish fixing it.
I done fucked up
:cl:
fix: Station tile decal color should be back to normal
/:cl:
=> Fix decal colors from initializing as randomized garbage

modular_zubbers/code/modules/synths/code/surgery/robot_brain_surgery.dm
Fixes #4294 
The synth surgery "Reset Posibrain Logic", aka the synth brain surgery, is currently bugged. Right now, it cannot be completed due to the only tool that can complete the final step, instead always doing the optional step. To finish the surgery properly, you must use a screwdriver to close the synth, but the optional step takes priority, and since the screwdriver is a ghetto option for that specific surgery step, it will always do the optional step.
This PR removes the screwdriver as a ghetto option for ```/datum/surgery_step/fix_robot_brain```, which allows the final step to process normally. While this does remove an option for completing surgeries on a synth, and does affect other surgeries than this one in the same way, it was destined to cause a conflict from the very …
=> Fixes Synth "Reset Posibrain Logic" Surgery

code/modules/mob/living/carbon/carbon.dm, code/modules/reagents/chemistry/reagents/impure_reagents/impure_medicine_reagents.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm, modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
#3947 moved colorful reagent's application to the mob instead of bodyparts/organs, however this left it unable to be washed off (in effect, permanent.)
Fixes washing, removes the hair color component, adds the changes to the inverse reagent reaction, adds color removal to the SAD.
I don't like a dozen ahelps when the clown throws a colorful reagent grenade
:cl: LT3
fix: Fixed washing colorful reagent off mobs
qol: The SAD removes colorful reagent when regenerating
/:cl:
=> Fix washing off colorful reagent

_maps/map_files/Blueshift/Blueshift.dmm
Adds a door button to the Blueshift medbay reception desk
<details>
</details>
:cl: LT3
map: Blueshift medbay reception desk now has a door button
/:cl:
=> Blueshift medbay door button

code/datums/sprite_accessories.dm
This PR fixes 4 already greyscaled fish tail sprites and allows them to be colored, because they couldnt be colored previously for some reason
Tails which are now colorable are:
> Simple
> Crescent
> Long
> Chonky
Better customization is poggers :3
It works!!
<details>
</details>
:cl:
fix: Simple, Crescent, Long and Chonky Fish/Shark tails are now colorable!
/:cl:
=> Fish Tail Fixes

modular_skyrat/modules/liquids/code/liquid_systems/liquid_effect.dm
`/datum/reagents/expose()` was changed upstream to not accept a `volume_modifier` argument of 0, which can happen if liquid code passes along an empty reagent holder. Changes the code to just return if this happens, as there's nothing to do.
Fixes https://github.com/Bubberstation/Bubberstation/actions/runs/16816835574/job/47635694919
Yes
No
=> Fix flaky CI failure related to liquids

code/__DEFINES/~~bubber_defines/research/techweb_nodes.dm, modular_zubbers/code/modules/research/designs/comp_board_designs.dm, modular_zubbers/code/modules/research/designs/machine_board_designs.dm, modular_zubbers/code/modules/research/techweb/all_nodes.dm
Fixes #2820 
Adds Mech Launchpads into the techweb after mech research and bluespace research is completed.
Bugfix, allows for people to actually use the mech launchpad again.
(I'm pretty sure this is a bug, let me know if this was an intentional removal, either on our end or TG's end)
:cl:
fix: Mech Launchpad Boards Are Researchable Again
/:cl:
=> Mech Launchpads Are Now In the Techweb

modular_zubbers/code/modules/quirks/neutral_quirks/body_temp.dm
Fixes https://github.com/Bubberstation/Bubberstation/issues/4260
who knew just changing post_add() to add() would fix it? not me for sure.
People probably shouldn't have their body temperature try to equalize to 0k
<details>
</details>
:cl:
fix: abnormal body temperature is no longer skrunkled by the SAD
/:cl:
=> Fixes abnormal body temp being skrunkled by the SAD

_maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/IceBoxStation/IceBoxStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/generic/CentCom.dmm, _maps/map_files/tramstation/tramstation.dmm
Reset several TG maps to the upstream state they were in in the latest commit of our last upstream pull (https://github.com/tgstation/tgstation/commit/7e87521ba4c6fa88ac8836e88083873d6f1a259a)
**NOTE: This has absolutely no effect on the maps contents, the differences in our version and upstream's were purely in TGM keys**
At some point, presumably years ago, edits were made to these TG maps and then undone by way of editing the map instead of reverting the commit, the way the TGM map format works made it change some of the map keys in such a way that it differed from upstream's files, but remained identical in terms of map contents. The purpose of the PR is just to reset the files so that during upstream pulls it doesn't have to do auto merge resolution because of the differing keys.
``` …
```
=> [MDB IGNORE] Reset TG maps to TG

modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/roundstartslime.dm, modular_skyrat/modules/modular_implants/code/nifsofts/shapeshifter.dm
Title.
Consistancy, for one. As it stands, polymorph completely breaks your colors in a way the SAD can't even fix (wow). This prevents that, while making it far more predictable.
Also, I can't think of a good reason polymorph doesn't let you change your color.
<details>
</details>
:cl:
qol: Polymorph/Shapeshift now takes from your pref's colors when making a new part
add: Polymorph can now let you change your general colors
/:cl:
=> Polymorph/Shapeshift now takes colors from your prefs + Polymorph gets color changing now

_maps/map_files/VoidRaptor/VoidRaptor.dmm
Fixes https://github.com/Bubberstation/Bubberstation/issues/4360
It makes it in-line with every other map
It was a simple map edit, it SHOULD work.
:cl:
fix: fixed the SMESes on Void Raptor not having cables under them
/:cl:
=> Adds cables under the SMESes on Void Raptor

modular_skyrat/modules/modular_weapons/code/gun_launches_little_guys_element.dm, modular_skyrat/modules/shotgunrebalance/code/shotgun.dm
Title.
Teshari anmd other small guys are thrown exactly one tile when firing a shotgun. This does no damage, cannot stun, and does not knockdown. Its almost entirely flavor.
Drafted due to freeze (Im assuming its okay to keep PRs open and drafted due to that one verb PR being open?)
Funny!
<details>
I forgor... to record...
</details>
:cl:
add: Little guys now get flung by shotguns
/:cl:
=> Makes !little guys! get thrown exactly one tile by shotguns

tgui/packages/tgui/interfaces/BubberChangelog.jsx
(Port of https://github.com/effigy-se/effigy/pull/131)
The selected index variable wasn't shared between the date dropdowns in the header and footer of the changelog, this meant if you used the arrow buttons on either side of the dropdown to change which month you were viewing, it wouldn't change in the other dropdown, if you then used the buttons in the other dropdown it would break
Bug fix
Yes
:cl:
fix: fixed buggy behavior in the forward and back buttons of the changelog UI
/:cl:
=> Fix bug with changelog arrow buttons

modular_skyrat/modules/blueshield/code/blueshield.dm, modular_skyrat/modules/goofsec/code/department_guards.dm, modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm, modular_skyrat/modules/sec_haul/code/corrections_officer/corrections_officer.dm, modular_skyrat/modules/telecomms_specialist/telecomms_specialist.dm, modular_zubbers/code/datums/components/fantasy/weight_overrides.dm, modular_zubbers/code/modules/jobs/job_types/blacksmith.dm, modular_zubbers/code/modules/jobs/job_types/warden.dm, tgstation.dme
Disables some of the harmful RPG loot affixes, so that the event can be run without dealing with players ending up cursed, polymorphed, etc.
Also adds some missing RPG titles.
Allows admemes to run this event without worry it's gonna fuck things up.
:cl: LT3
balance: RPG Loot event will no longer add certain negative traits to items
/:cl:
=> Disable harmful RPG loot affixes

_maps/RandomRuins/SpaceRuins/skyrat/port_tarkon.dmm, code/__DEFINES/~~bubber_defines/cameranets.dm, modular_zubbers/code/modules/tarkon/code/cameras.dm, tgstation.dme
Does as the title says; also fixes https://github.com/Bubberstation/Bubberstation/issues/4367
"Xenos in xenobiology!!! Wait, that's just Tarkon." gets annoying after a while.
I didn't see the Tarkon cameras in the network.
<details>
</details>
:cl:
fix: fixed Tarkon cameras not having their own network
/:cl:
=> Replaces all tarkon cameras with their own network

code/__DEFINES/~~bubber_defines/traits/declarations.dm, code/datums/quirks/positive_quirks/bilingual.dm, modular_skyrat/master_files/code/modules/client/preferences/middleware/languages.dm, modular_skyrat/modules/customization/modules/jobs/_job.dm
This PR removes a bunch of extra, unneeded code related to bilingual by making it function the same as Linguist, giving an extra language point in the language menu. Atomized from #4513 
Simplifies accessing new languages by making both language quirks work the same
add: The Bilingual trait now grants an extra language point.
/:cl:
=> Makes bilingual function the same as Linguist

code/modules/mob/living/basic/clown/clown.dm
Killing simplemob normal clowns creates gibs instead of corpses
Clown bombs are a thing and once you kill all of them, the amount of overlays on screen increases substantially, creating a ton of GPU lag clientside.
:cl: BurgerBB
qol: Killing simplemob clowns creates gibs instead of corpses because I lagged to them once.
/:cl:
=> Killing simplemob clowns creates gibs instead of corpses because I lagged to them once.

code/__DEFINES/research/anomalies.dm
Currently, taur parts cause a nightmare for both staff/maintainers and the players that receive them from the bioscrambler due to them being near unremovable.
Fixes https://github.com/Bubberstation/Bubberstation/issues/2797
It was a one line addition, it should work but I'm not sitting and waiting to see if I get the parts or not.
:cl:
fix: fixed unremovable taur limbs being granted from bioscramblers
/:cl:
=> Adds taur parts to the bioscrambler blacklist

modular_zubbers/code/modules/quote_of_the_round/ticker.dm
Adds the upcoming map to the new game announcement
:cl: LT3
qol: New round discord notification now includes the upcoming map name
/:cl:
=> Include next map on new round announcement

code/modules/mob/living/carbon/examine.dm
Title.
From 26-35, you are listed as being an adult. I can't think of a better term for this - "average" adult?
Bugs bad.
<details>
so i didnt actually test this
</details>
:cl:
fix: Carbons 26-35 are now described as "an adult"
/:cl:
=> Adds missing age-text for an age range

code/__DEFINES/~skyrat_defines/traits.dm, code/__DEFINES/~~bubber_defines/traits/sources.dm, code/modules/mob/living/carbon/human/human_update_icons.dm, modular_zubbers/modules/taur_mechanics/taur_body.dm
Title.
A verb is probably not the best way to do it, but also I can't be assed to find a better solution (an action button is overkill)
Theres so many clothing sprites that would work on taurs, but they dont have the flag set - and let's be honest, noone is gonna go through every clothing sprite they see to set the flag. This lets the taur players decide what works for their sprite.
<details>
</details>
:cl:
add: New taur verb that lets you disable/enable taur clothing cropping
/:cl:
=> Adds a verb for disabling taur clothing cropping

modular_zubbers/code/modules/clothing/neck_wearing.dm
Title. Neck wearing is the stuff that lets you wear suits on your neck.
If a suit is damaged, say the nobility dresscoat, its functional_suit_values is null. This should fix that.
bugs bad
<details>
i cant actually test rn but this should work
</details>
:cl:
fix: Neck wearing shouldnt runtime if the item is damaged
/:cl:
=> Fixes a runtime in neck wearing code

code/modules/surgery/organs/internal/stomach/_stomach.dm
This is a salt PR.
Makes gravity sickness, the status effect given by spacer (and to my knowledge nothing else), cause the holder to be immune to level 1 nausea's stuttering effect.
Spacer is a good quirk. I like it. Adds nice flavor to my character. But oh my god, the stuttering. The only thing stuttering does it be annoying and make it hard to talk, which is generally not a very good thing for "roleplay". Theres a reason very few people take social anxiety and instead opt to just stutter and stammer with their own fleshy fingers.
This is especially bad on bubber where we have three whole planet maps, and it seems they're voted very often.
<details>
</details>
:cl:
balance: Spacer no longer causes disgust stuttering
/:cl:
=> Gravity sickness no longer causes stuttering

modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
In response to https://github.com/Bubberstation/Bubberstation/issues/4620 this fixes the broken Texture on the Golden NTRep Coat.
It's just a minor bug fix.
Tested it on local, it works fine now.
<details>
</details>
:cl:
fix: Fixed Golden NTRep Coats missing Texture on Digitigrade mobs
/:cl:
=> Fixing Golden NTRep Coat missing Texture

modular_skyrat/modules/multicellcharger/code/multi_cell_charger.dm
Turns out you could take cells out of a multi-cell charger from range, this adds a check to stop that.
Minor bugfix 
<details>
</details>
:cl:
fix: Multi-Cell chargers can't be withdrawn from range anymore.
/:cl:
=> Fixes Multi-Cell Chargers working at range

modular_skyrat/modules/modular_items/code/summon_beacon.dm
Most folks seem to like to geek out in Tarkon and do things on their own pace, so why not let people experiment with the things that you can achieve with gas mining beacons? Tarkon is a particularly good place for this, and you have slimmer chances of imposing a bad day upon someone else but yourself if you somehow manage to screw things up. Yes, Tarkon already have pre-existing gas miners in each respective gas tank, but there's a lot of things you can do with some more in enclosed areas. 
Basically, this PR merely adds the Port Tarkon atmospherics area to the whitelist of gas miners.
=> Updates the gas miner whitelist variables to include the Port Tarkon atmospherics area.

modular_zubbers/modules/taur_mechanics/taur_body.dm
Title.
Two seconds is kind of ridiculous for regaining your mobility. Plus, what taur takes??? This long to get uo??
<details>
</details>
:cl:
qol: Taur laying recovery: 2 secs -> 1 sec
/:cl:
=> Lowers taur laying recovery to 0.5 secs

code/controllers/subsystem/processing/quirks.dm, code/datums/quirks/positive_quirks/settler.dm
This is a reversion of [this](https://github.com/tgstation/tgstation/pull/92425) TG PR. 
If somebody considers the items to be "clutter", they can be tossed away; I, and other people who select this quirk, use it, at least partially, for the items.
Compiled, it works.
<details>
</details>
:cl: sunnyaries
balance: re-clutters settler
/:cl:
=> Re-"Clutters" the Settler quirk

modular_zubbers/code/modules/vehicles/mecha/equipment/weapons.dm, modular_zubbers/code/modules/vehicles/mecha/ripley.dm, tgstation.dme
TG decided to take the paddy out back and break it's knees after a CERTAIN INCIDENT. This puts the speed in between the 1 and 2 chassis for better balance, and ensures we don't have any low pressure lightspeed tomfoolery anymore. 
This also drops the exosuit disabler to 4 bolts with variance instead of 5. 
The paddy was unrightfully nerfed into the fucking ground, but at the same time the disabler was really strong with 5 bolts. 
worked on my machine 
</details>
:cl:
balance: Upped the paddy's speed to sit between the mk1 and mk2 
balance: Nerfed the exosuit disabler to 4 projectiles instead of 5 
/:cl:
=> Re-Buffs the Paddy a bit + Nerfs the Exosuit Disabler

tgui/packages/tgui/interfaces/Orbit/constants.ts
Exactly as the title says - adds modular jobs to their relevant department's DEPARTMENT2COLOR, making the orbit menu sort them alongside their coworkers.
<h5>Any that aren't sorted, are TG jobs that should be sorted upstream - namely the Veteran Advisor, Big Brother, and 'Busser' (monkey-day).</h5>
<h5>Technically Bridge Assistant is too, and could probably just be sorted up there too. But since it's actually common, I figured it's best just included here.</h5>
<h6>This is my first Bubber PR so I hope I did this right 🙏 I don't know that this can be fully modularized because of this being a .js file but I did the comments</h6>
Consistency - keeps coworkers sorted with coworkers. Makes the whole thing actually work as advertised.
Couldn't test with color because I don't have 50something …
=> Adds modular jobs to Orbit Menu department sorting

modular_zubbers/code/modules/antagonists/bloodsucker/clans/clan_nosferatu.dm
nosferatu can ventcrawl with a backpack again
it was probably too rough a nerf given the other changes
it compiles
<details>
</details>
:cl:
balance: Nosferatu can ventcral with a non-smuggling satchel now, no limitations on their back slot
/:cl:
=> nosferatu can ventcrawl with a backpack again

modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/lustwish.dm, modular_zubbers/code/datums/quirks/negative_quirks/well_trained.dm, modular_zubbers/code/datums/quirks/positive_quirks/dominant_aura.dm, modular_zubbers/code/modules/research/designs/mechfab_designs.dm, modular_zubbers/code/modules/research/techweb/all_nodes.dm, modular_zubbers/code/modules/silicons/borgs/code/robot_upgrade.dm
Adds a brand new cyborg module to the exofab and lustwish; the borg obedience module. As a sister module to the dominatrix module, it functions identically the same, but instead of applying the dominant aura trait, applies the well trained trait. This also makes it so the quirk functions on silicons properly.
Some borgs want to have the funny toys but not the dominant aura, or would prefer to just be able to have access to this trait, even if it may be a negative one on paper, not to mention it's a bit odd that only the one side of this two sided quirk is available.
It compiles, only one dominatrix or obedience module can properly be used at the same time, borgs react how they should with the quirk.
<details>
</details>
:cl:
add: Obedience cyborg …
=> Adds a borg obedience module

modular_skyrat/modules/hurtsposals/code/pipe.dm
Improves disposals code so it actually deals damage to you on direction changes.
Nerfs disposals damage so that it has a 20% chance to apply instead of an 80% chance to apply.
You no longer take disposals damage if you're in hard crit or dead.
Disposals damage when it procs deals 4 damage instead of 5.
Making disposals damage work as intended is always good.
With the new 100hp change, people are feeling the (disposals) burn, so the damage was reduced.
Draft because I literally coded this from scratch in the github online code editor.
:cl: BurgerBB
balance: Nerfs disposals damage so that it has a 20% chance to apply instead of an 80% chance to apply. You no longer take disposals damage if you're in hard crit or dead. You take 1 less disposals damage when it applies, now, a total of 4 per …
=> Improves disposals code so it actually deals damage to you on direction changes and nerfs disposals damage.

code/modules/mob/living/carbon/carbon_defense.dm
Reverts a skyrat change that caused shocks by default to knock you down instead of paralyze (stun).
Also reverts the secondary stuns stamina knockdown thing for secondary shocks as well.
Overall grille shocks and airlock shocks now paralyze (knockdown + stun) instead of knock you down and do stamina damage. Other shock sources generally already don't stun you by flags set from the shock source.
This change created an unintended consequence by making it so by not blocking movement with a stun you can just repeatedly move into the shocked airlock and grille and crit yourself/straight up die, similar to a conveyer grille shock trap but caused by not being able to react to the fact a grille is shocked, you continue moving into the grille or airlock and repeatedly get shocked over and over …
=> Airlocks/Grilles Stun You Instead of Knockdown (Skyrat Revert)

modular_zubbers/code/modules/wizard_dize/wizard_dice_object.dm
unrigs the wizard die
it's kinda ass that it's super hard to roll the wizard die even if it spawns near people now, and it has limited uses now, considering to reduce the uses as a fallback so wizard isn't too common
it builds
<details>
</details>
:cl:
balance: wizard die isn't rigged
/:cl:
=> unrigs the wizard die

modular_zubbers/code/datums/quirks/neutral_quirks/pet_owner.dm
You can now take stoats as pets! Yippee!
Kinda sucks that the only mustelid mob in the game isn't available as part of the pet owner quirk.
Now they are!
<details>
It's literally just adding stoats to the pool of mobs for petowner. It works as intended.
</details>
:cl:
add: Stoats can now be taken as pets with the Pet Owner Quirk! Enjoy your little squirmy fella.
/:cl:
=> Adds stoats to pet owner quirk!

modular_skyrat/modules/mapping/code/space.dm
Per my #suggestions post which received overwhelming support, adds the 'always_place' flag to the BMD ruin, forcing it to generate when possible. Like Tarkon!
I literally changed one line to add the 'always_place' flag to `mapping/code/space.dmm` under the blackmarket ruin. The same flag that the Tarkon ruin uses to always generate when possible. 
BMD occupies a space that no other ghost role does; a small-scale off-station role with the sole purpose of making use of space ruins that would otherwise go ignored, **_WITH_** station interaction and RP _facilitated and encouraged._ 
It also hardly ever generates in favor of something like Charliestation or the Derelict Drone station-- Or Tarkon, which always generates and basically takes up an entire z-level. 
Making it always available would …
=> Makes Black Market ruin always generate when possible

modular_skyrat/modules/horrorform/code/horror_form.dm, modular_skyrat/modules/horrorform/code/true_changeling.dm
Cleans up `modular_skyrat\modules\horrorform\code\true_changeling.dm` and `modular_skyrat\modules\horrorform\code\horror_form.dm` to make them significantly more readable. This also fixes https://github.com/Bubberstation/Bubberstation/issues/4656 by making the action get added correctly.
Readability + No Bugs = Good
It worked fine on my end, I was able to transform to horror form, then turn back into John Ling.
:cl:
fix: Fixed the horror form not being able to turn back into humanoid form
/:cl:
=> Horror Form Code Cleanup + Fixes

modular_zubbers/code/modules/mob/living/carbon/human/species_types/ghost.dm, tgstation.dme
Fixes exception when choosing Ghost species.
Most of species have overrides in
modular_zubbers\code\modules\mob\living\carbon\human\species_types
which returning lists instead of strings.
https://github.com/Bubberstation/Bubberstation/issues/4785
<details>
</details>
:cl:
fix: Fixed ghost species crashing character preferences menu
/:cl:
=> fixed exception with ghost species

modular_zubbers/code/modules/customization/sprite_accessories/horns.dm
Title. Someone did an oopsie, and used "wisteria" as their horns name, meaning the wisteria antennae couldn't be used.
Please, my bug looks bald.
<details>
<summary>Screenshots/Videos
</summary>
</details>
=> Fixes "Wisteria Antennae" being unselectable

config/game_options.txt, tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/QuirksPage.tsx
A bit of our modular code was reverted that shouldn't have been, and upstream added a config for starting quirk points that defaults to -2 when we're currently set up for 0, so that is changed as well
The server borked
I tested and was able to add/remove quirks as normal
:cl:
fix: fixed quirk balances being broken
/:cl:
=> Fix quirk balances being broken

modular_zubbers/code/modules/clothing/glasses/hud.dm, modular_zubbers/code/modules/implants/code/augments_eyes.dm
tg changed the trait name it used so i had to change it too yaaaay
fixes #4794 
I tested it but also it's like. changing the HUD_traits of the implant and the glasses it's not that hard
:cl:
fix: Civilian HUDs once again work.
/:cl:
=> Fixes civilian huds not working
